### ISSUE TITLE
Yii2 documentation mismatch for amOnPage()

### ISSUE THREAD

**Issue by mikehaertl** [Codeception/Codeception#5631] opened 2019-08-06 08:33 UTC
* Example on this page: https://codeception.com/for/yii:
 `$I->amOnPage(['site/contact']);` (A route in array form is used)
* Documentation for Yii2 module: https://codeception.com/docs/modules/Yii2#amOnPage:
  *Opens the page for the given relative URI.* ( `param string $page`)

I guess the module documentation should be updated.

**Comment by SamMousa** [comment] 2019-08-06 15:16
PR welcome!

**Comment by mikehaertl** [comment] 2019-08-06 16:10
@SamMousa Sure, but it seems the docs are autogenerated. I couldn't find the code where `amOnPage()` is overridden for Yii2. In `src/Codeception/Module/Yii2.php` there's only `amOnRoute()`. Any ideas?

**Comment by alexkunin** [comment] 2019-08-06 16:28
This is just a guess, but I think that method is documented here: https://github.com/Codeception/Codeception/blob/3.0/src/Codeception/Lib/Interfaces/Web.php. But as you can imagine, same interface is used for many other modules, and fixing docs at that place will "break" docs for other modules.

Probably the correct way would be editing docblock here: https://github.com/Codeception/Codeception/blob/3.0/src/Codeception/Module/Yii2.php. The problem is: there is no `amOnPage` as it is not overriden (not in Yii2, anyway). So, to add docs it is probably needed to add stub method too (it should just call `parent::`).

But again, that's just a guess.

**Comment by alexkunin** [comment] 2019-08-06 16:31
https://github.com/Codeception/Codeception/blob/3.0/RELEASE.md describes release process; you can do `php robo.phar build:docs` instead of step 7 do generate only docs and see if it works as I describe above. But note that docs that are committed in repo are outdated, and calling `build:docs`, then adding method, and then doing `build:docs` and comparing with previous results would be the right thing to do (to avoid lots of noise due to outdated committed docs).

**Comment by mikehaertl** [comment] 2019-08-06 16:35
Hmm, grrr. :stuck_out_tongue: I've already started manually fixing the file in `docs/modules/Yii2.md`. But ok, will try to merge that into the `Yii2.php` module file.

Can anyone confirm that the docs are really autogenerated? If not, it would not make much sense to edit the module comments and not the docs files itself.

**Comment by alexkunin** [comment] 2019-08-06 16:39
I can confirm that they are auto-generated. I did fair amount of docs editing for `Doctrine2`, but only once I did that for inherited method (and it was not from interface, and was already overridden in the module -- thus my 'guessing', not my 'sure thing').

**Comment by SamMousa** [comment] 2019-08-06 17:20
You can add a docblock to the class header. `@method amOnPage(array|string $uri)` that might work for the doc generator; it works in IDEs

**Comment by mikehaertl** [comment] 2019-08-06 17:25
@SamMousa Too late, sorry. Created PR. I've also included the generated docs file for Yii2.

**Comment by mikehaertl** [comment] 2019-08-06 17:29
@alexkunin Do you maybe know, when the website is updated from the generated docs in the repo? As you said, the files there are really outdated. There are only recent changes for Laravel (3 weeks ago) which are not available on the website, though.

**Comment by alexkunin** [comment] 2019-08-06 17:36
Sorry, I don't know. My minor fix (#5596) was merged 7 days ago, but still cannot be seen on the site. But updated version was not released yet, so, I guess I should not expect the site to be updated. Releases seem to happen roughly once in a month, as far as I can tell. The most recent one was like 3 weeks ago.

**Comment by Naktibalda** [comment] 2019-08-16 11:03
Website is only updated when a new version is released.

**Comment by Naktibalda** [comment] 2021-01-03 15:57
Yii2 module docs were improved by #5636

**Closed by Naktibalda** 2021-01-03 15:57 UTC
