### ISSUE TITLE
fillField and implicit wait

### ISSUE THREAD

**Issue by nkovacs** [Codeception/Codeception#1697] opened 2015-02-05 17:35 UTC
I'm using codeception 2.0.11

If I set implicit wait to e.g. 10 seconds (using the wait config option of webdriver), and then use `$I->fillField('input[name="TestForm[name]"]', 'Test');`, codeception will do two xpath finds that wait 10 seconds each.
I cannot change implicit wait from the test (well, maybe with getModule, but I haven't figured that out and in any case I can't change it back to the original value). This makes it pretty much useless, and I have to put waitFor* everywhere.

**Comment by Naktibalda** [comment] 2016-09-26 21:01
Duplicate of #2511

This is an earlier issue, but another one has a better description.

**Closed by Naktibalda** 2016-09-26 21:01 UTC
Labels: WebDriver
