### ISSUE TITLE
Accepting javascript alerts while codecovering

### ISSUE THREAD

**Issue by FnTm** [Codeception/Codeception#915] opened 2014-03-14 10:08 UTC
I am trying to do some accept testing using the Selenium Webdriver. Its not going so great.

I have a page, that has a form, which upon filling, should be submited. Submit button would then launch a javascript confirmation, which, if confirmed, submits the form. 

The weird part is, that the test runs smoothly, without the `--coverage` parameter. Here's the test:

``` php
$I = new WebGuy($scenario);
$I->wantTo('login, delete my account and try to unsuccessfully login with deleted account');
$I->amOnPage('/');


$I->fillField("//input[@name='email']", "c@c.com");
$I->fillField("//input[@name='password']","xxxx");
$I->click("//input[@name='submit']");
$I->dontSeeElement(".alert-error");

$I->amGoingTo("try to delete my account with incorrect current password");
$I->amOnPage('/xxx/settings/');
$I->fillField("//input[@id='current-password-delete']","parole2222");
$I->click("click me");
$I->acceptPopup();
```

This is how it fails:

```
 $ vendor/codeception/codeception/codecept run acceptance backend/UserDeleteCept.php --steps --coverage
Codeception PHP Testing Framework v1.8.3
Powered by PHPUnit 3.7.32 by Sebastian Bergmann.

Acceptance Tests (1) -----------------------------------------------------------------------------------------------------------
Trying to login, delete my account and try to unsuccessfully login with deleted account (backend/UserDeleteCept.php)       
Scenario:
* I am on page "/"
* I fill field "//input[@name='email']","c@c.com"
* I fill field "//input[@name='password']","parole"
* I click "//input[@name='submit']"
* I don't see element ".alert-error"
* I am going to try to delete my account with incorrect current password
* I am on page "/admin/settings/"
* I fill field "//input[@id='current-password-delete']","parole2222"
* I click "click me"
 ERROR 

--------------------------------------------------------------------------------------------------------------------------------


Time: 6.27 seconds, Memory: 12.75Mb

There was 1 error:

---------
1) Failed to login, delete my account and try to unsuccessfully login with deleted account in backend/UserDeleteCept.php
Sorry, I couldn't click "click me":
UnexpectedAlertOpenException: Modal dialog present: Please click on OK to continue.
Build info: version: '2.40.0', revision: 'fbe29a9', time: '2014-02-19 20:54:28'
System info: host: 'nfcteam-1', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.5.0-17-generic', java.version: '1.7.0_51'
Session ID: 42896444-2b30-4a5e-95bc-a0f9551328a8
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, browserConnectionEnabled=true, webStorageEnabled=true, nativeEvents=false, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=27.0.1}]

Scenario Steps:
9. I click "click me"
8. I fill field "//input[@id='current-password-delete']","parole2222"
7. I am on page "/admin/settings/"
6. I am going to try to delete my account with incorrect current password
5. I don't see element ".alert-error"
4. I click "//input[@name='submit']"
3. I fill field "//input[@name='password']","parole"

#1  /var/www/nfcmore/vendor/facebook/webdriver/lib/remote/HttpCommandExecutor.php:253
#2  /var/www/nfcmore/vendor/facebook/webdriver/lib/remote/HttpCommandExecutor.php:153
#3  /var/www/nfcmore/vendor/facebook/webdriver/lib/remote/HttpCommandExecutor.php:117
#4  /var/www/nfcmore/vendor/facebook/webdriver/lib/WebDriverOptions.php:94
#5  /var/www/nfcmore/vendor/facebook/webdriver/lib/WebDriverOptions.php:79
#6  /var/www/nfcmore/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:164
#7  /var/www/nfcmore/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:53
#8  /var/www/nfcmore/tests/acceptance/WebGuy.php:477
#9  /var/www/nfcmore/tests/acceptance/backend/UserDeleteCept.php:15

FAILURES!
Tests: 1, Assertions: 1, Errors: 1.
```

If I skip the `--coverage` option, it passes

```
 $ vendor/codeception/codeception/codecept run acceptance backend/UserDeleteCept.php --steps           
Codeception PHP Testing Framework v1.8.3
Powered by PHPUnit 3.7.32 by Sebastian Bergmann.

Acceptance Tests (1) -----------------------------------------------------------------------------------------------------------
Trying to login, delete my account and try to unsuccessfully login with deleted account (backend/UserDeleteCept.php)       
Scenario:
* I am on page "/"
* I fill field "//input[@name='email']","c@c.com"
* I fill field "//input[@name='password']","parole"
* I click "//input[@name='submit']"
* I don't see element ".alert-error"
* I am going to try to delete my account with incorrect current password
* I am on page "/admin/settings/"
* I fill field "//input[@id='current-password-delete']","parole2222"
* I click "click me"
* I accept popup 
 PASSED 

--------------------------------------------------------------------------------------------------------------------------------


Time: 5.45 seconds, Memory: 10.00Mb

OK (1 test, 1 assertion)
```

This is my `acceptance.suite.yml`:

``` yml
class_name: WebGuy
modules:
    enabled:
            - WebDriver
            - Db
    config:
          WebDriver:
              url: 'http://example.coim'
              browser: firefox
              wait: 0
              capabilities:
                unexpectedAlertBehaviour: 'accept'
                takesScreenshot: 0

          Db:
              dsn: 'mysql:host=localhost;port=3306;dbname=example'
              user: 'example'
              password: 'example'
              populate: true
              cleanup: true
              dump: tests/_data/test.sql
```

What makes this even more weird is, that I can't reproduce the bug within Codeception test suite. 

I made minor changes to the `view/index.php` file:

``` html
<html>
    <title>TestEd Beta 2.0</title>
<body>

<h1>Welcome to test app!</h1>

<div class="notice"><?php if (isset($notice)) echo $notice; ?></div>

<script type="text/javascript">
    function AlertIt() {
        var answer = confirm ("Please click on OK to continue.")
    }
</script>

<a href="javascript:AlertIt();">click me</a>
<p>
    <a href="/info" id="link" >More info</a>
</p>


<div id="area1">
    <a href="/form/file"> Test Link </a>
</div>
<div id="area2">
    <a href="/form/hidden">Test</a>
</div>

A wise man said: "debug!"

<script>

</script>
</body>
</html>
```

And wrote this test:

``` php
public function testClickEventOnCheckbox()
    {
        $this->module->amOnPage('/');
        $this->module->click("click me");
        $this->module->acceptPopup();
        $this->module->click("More info");
    }
```

All of this works smoothly. I have no idea how to explain this kind of behaviour. Maybe the codecovering sends some command to selenium, which would then mean, that it is no longer expecting the popup? But then it would have to return another error. 

At a loss for words.

**Comment by b108** [comment] 2015-11-17 16:53
I have the same trouble with Codeception version 2.1.3.

**Comment by Naktibalda** [comment] 2015-11-17 16:55
Report it to Selenium.

**Comment by bev-ru** [comment] 2016-05-25 10:36
I think it's not selenium bug.
This issue is dup of [#1485](https://github.com/Codeception/Codeception/issues/1485).
See my comment in [#1485](https://github.com/Codeception/Codeception/issues/1485).

**Comment by Naktibalda** [comment] 2019-03-25 14:24
Duplicate of #1485.

**Closed by Naktibalda** 2019-03-25 14:24 UTC
