### ISSUE TITLE
$I->click submit in wordpress is not working. 

### ISSUE THREAD

**Issue by cloudEdwards** [Codeception/Codeception#2288] opened 2015-08-18 20:19 UTC
After upgrading to 2.1, When using acceptance tests in wordpress, and I am unable to see that my settings have been saved after clicking the Save button.
It seems like the $I->click command is not working as expected, when I am trying to publish a post. 

The click command is working fine in other contexts, like navigating between "Posts", and "Pages". This  is working as expected. Clicking the publish/update button in posts or pages is also working fine, it is just when I am changing settings.

I reverted back to codeception 2.0.16 but the issue is still persisting.  I reverted back to 2.0.12 and it started working again. Phew!

Thanks in advance 

Cloud

**Comment by DavertMik** [comment] 2015-08-20 01:13
If you are testing basic wordpress installation can you publish a repository with test which reproduces your issue?

**Comment by mipon** [comment] 2015-08-27 04:01
Got a similar problem. Looks like `?` in the clicked url gets encoded to `%3f` and resulting in loading a non-existent page.

**Comment by cloudEdwards** [comment] 2015-08-27 09:15
Hi DavertMik sorry for taking so long, I just got back from holidays.
I am testing a larger suite of custom wp plugins, so I will try to reproduce the problem in isolation, then I will send that as a repo.
Thanks

**Comment by Naktibalda** [comment] 2015-10-27 20:52
@cloudEdwards Have you managed to reproduce this issue?

**Comment by cloudEdwards** [comment] 2015-10-29 16:51
I haven't been able to reproduce this, we just kept the older version.

**Comment by Naktibalda** [comment] 2015-10-29 17:27
You will have to stay with it forever :)

Do you use WebDriver or PhpBrowser in your tests?

**Comment by cloudEdwards** [comment] 2015-10-30 17:05
Yea, I've been to busy to give it another try. I use both PhpBrowser and Webdriver. I'll try to upgrade again and see how it goes. I'm getting a new work computer so I will be able to experiment with it on my home computer.

**Comment by dwenaus** [comment] 2016-02-20 01:17
The problem was that in 2.1 clicking on a submit button no longer adds that to the $_POST array. feel free to close this.

**Closed** 2016-02-20 02:49 UTC

**Comment by cloudEdwards** [comment] 2016-02-20 02:50
dwenaus figured this out! Removed a thorn in my side.
