### ISSUE TITLE
Test name is different in `startTest` and `endTest` methods if `@example` is used

### ISSUE THREAD

**Issue by SvetlanaZem** [Codeception/Codeception#4124] opened 2017-04-11 16:04 UTC
1) I created a test with `@example` doc parameter:
```
<?php
class GoogleCest
{
    /**
     * @example {"url": "https://www.google.com/", "text": "Google" }
     */
    public function checkWeb(\AcceptanceTester $I, \Codeception\Example $example) {
        $I->wantTo('Ensure that i am able to view page and find a text in it');
        $I->amOnPage($example['url']);
        $I->see($example['text']);
    }
}
```

2) I've implemented custom ResultPrinter and override `startTest` and `endTest` methods.
```
class PhpStorm_Codeception_ReportPrinter extends PHPUnit_TextUI_ResultPrinter
{
    public function startTest(PHPUnit_Framework_Test $test)
    {
        $testName              = \Codeception\Test\Descriptor::getTestAsString($test);
        $this->write("\nSTARTED: $testName\n");
    }

    public function endTest(PHPUnit_Framework_Test $test, $time)
    {
        $testName              = \Codeception\Test\Descriptor::getTestAsString($test);
        $this->write("\nENDED: $testName\n");

    }
}
```
3) I've executed the test with custom result printer.

I expect to see the same test name in `startTest` and `endTest`.
```
STARTED: GoogleCest: Ensure that i am able to view page and find a text in it | "https://www.google.com/","Google"

ENDED: GoogleCest: Ensure that i am able to view page and find a text in it | "https://www.google.com/","Google"
```
#### What do you get instead?
```
STARTED: GoogleCest: Ensure that i am able to view page and find a text in it | "https://www.google.com/","Google"

ENDED: GoogleCest: Ensure that i am able to view page and find a text in it
```

### Details

* Codeception version: 2.2.10
* PHP Version: 7.1.1
* Operating System: Ubuntu
* Installation type: Phar

**Comment by Naktibalda** [comment] 2022-12-29 18:07
Won't fix.

The root cause of this issue is that `wantTo` method is called in the test.

`wantTo` was intended to be used in Cept format and has unexpected effects in other formats.
Cept format is deprecated and it is quite likely that `wantTo` method will be removed in the future version of Codeception, together with Cept format.

**Closed** 2023-01-13 18:28 UTC
