### ISSUE TITLE
[Yii2] returning 204 No content status header gives [Exception] No content was sent from Yii application

### ISSUE THREAD

**Issue by mikk150** [Codeception/Codeception#5418] opened 2019-03-01 14:06 UTC
#### What are you trying to achieve?

I want to test if deleting elements work

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
 Test  tests/functional/ThingCest.php:testDelete
                                                        
  [Exception] No content was sent from Yii application  
                                                        

Scenario Steps:

 1. $I->sendDELETE("thing/1") at tests/functional/ThingCest.php:307

/app/vendor/codeception/codeception/src/Codeception/Lib/Connector/Yii2.php:356
/app/vendor/symfony/browser-kit/Client.php:405
/app/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php:202
/app/vendor/codeception/codeception/src/Codeception/Module/Yii2.php:658
/app/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php:134
```
> Provide test source code if related

```php
/**
 * @param FunctionalTester $I
 */
public function testDelete(FunctionalTester $I)
{
    $I->sendDELETE('thing/1');
    
    $I->seeResponseCodeIs(204);

    $I->dontSeeRecord(Thing::class, ['id' => 1]);
}
```
### Details

* Codeception version: 2.5.4
* PHP Version: 7.2.14
* Operating System: Alpine linux on docker
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
suite_namespace: tests\functional
actor: FunctionalTester
modules:
  enabled:
    - Asserts
    - REST:
        depends: Yii2
    - Yii2:
        cleanup: true
```

since Yii2 2.0.16.1 204 content is now null and will not pass https://github.com/Codeception/Codeception/blob/2.5/src/Codeception/Lib/Connector/Yii2.php#L355

**Comment by SamMousa** [comment] 2019-03-01 14:09
That condition should pass.
Specifically:
```
 if (empty($content) && !empty($response->content) && !isset($response->stream)) {
```
checks if no content was sent, but content was loaded into the `Response` via its `$content` or `$stream` properties.

To debug this, try changing the line you linked to dump `$response->content` or `$response->stream`. I'm also interested to see your delete action code.

**Comment by mikk150** [comment] 2019-03-01 14:19
Controller
```php
namespace backend\controllers;

use yii\rest\ActiveController;

class ThingController extends ActiveController
{
    /**
     * @inheritdoc
     */
    public $modelClass = Thing::class;
}
```

```php
        var_dump($content); // string(0) ""
        var_dump($response->content); // string(4) "null"
        var_dump($response->stream); // NULL
```

content is string(4) "null" because json_encode of NULL is "null"

**Comment by SamMousa** [comment] 2019-03-01 15:41
After some digging this line is the actual cause:
https://github.com/yiisoft/yii2/blob/master/framework/web/JsonResponseFormatter.php#L121

@samdark I'm not 100% convinced that fixing this in codeception by creating a special case for response code 204 is the best solution.

The `ResponseFormatterInterface` uses the whole `Response` for a reason.
In my opinion it should make sure not to set content `"null"` when the response code is 204...

For Yii3 it might make more sense to throw an error in the response when setting content and a status code that must not include a body. This seems a more robust approach than silently not sending it.

Your thoughts?

**Comment by samdark** [comment] 2019-03-01 15:54
Is it still the case in 2.0.16.1?

**Comment by mikk150** [comment] 2019-03-01 16:02
@samdark it is issue with 2.0.16.1

**Comment by mikk150** [comment] 2019-03-01 16:11
Also @SamMousa 
https://github.com/yiisoft/yii2/blob/master/framework/web/JsonResponseFormatter.php#L121 does exactly what it should do

**Comment by SamMousa** [comment] 2019-03-01 16:16
Well that depends on how you interpret the contract of the interface:
```php
interface ResponseFormatterInterface
{
    /**
     * Formats the specified response.
     * @param Response $response the response to be formatted.
     */
    public function format($response);
}
```
Since the whole response object is passed and not just the data, it would be valid to rely on other information like headers or response code to decide how to format the data. 

I really like your suggestion to not do any formatting in case response code is 204. That way we keep the special behavior contained in the `Response` object and we save some CPU cycles as well.

I vote for that solution +1

**Comment by samdark** [comment] 2019-03-05 09:35
Fixed in the framework thanks to @mikk150.

**Closed by samdark** 2019-03-05 09:35 UTC

**Comment by SamMousa** [comment] 2019-03-05 09:36
@mikk150 would you be up for creating a test case PR at https://github.com/codeception/yii2-tests?

That way we can prevent a regression in the future!
