### ISSUE TITLE
Test with examples ignored when running with group parameter

### ISSUE THREAD

**Issue by teeencho** [Codeception/Codeception#2990] opened 2016-04-14 14:34 UTC
Hi,

I'm using the following command to run my test

`vendor/bin/codecept run --env docker,dev -g example`

and it doesn't run. If I run the whole cest or suite without the group parameter, it does run.

```
     /**
     * @group example
     * @example(foo="a", bar="b")
     * @example(foo="c", bar="d")
     */
    public function tryExample(AcceptanceTester $I, Example $example){
        $I->comment($example['foo']);
        $I->comment($example['bar']);
    }

```

When it doesn't run, I can see that the test is counted though, because the console outputs the amount of tests that the suite has 30:

```
Acceptance (docker, dev) Tests (30) --------------------------
Modules: WebDriver, Asserts, Db, \Helper\Acceptance, Filesystem
------------------------------------------------------------
------------------------------------------------------------


Time: 5.43 seconds, Memory: 13.00Mb

No tests executed!
```

And if I remove the ignored test, it outputs 29:

```
Acceptance (docker, dev) Tests (29) --------------------------
Modules: WebDriver, Asserts, Db, \Helper\Acceptance, Filesystem
------------------------------------------------------------
------------------------------------------------------------


Time: 5.43 seconds, Memory: 13.00Mb

No tests executed!
```

I'm using Codeception 2.2.0-beta

Thank you.

**Comment by TehJoE** [comment] 2016-08-18 21:43
The fix for this only works if the method is annotated with `@group`. If the test class is annotated with `@group`, the problem persists.

**Comment by eXorus** [comment] 2021-01-19 17:02
I can't reproduce the bug.

tests/acceptance/FirstCest.php
```
<?php 

class FirstCest
{

    /**
     * @group g1
     * @example(foo="a", bar="b")
     * @example(foo="c", bar="d")
     */
    public function tryToTest(AcceptanceTester $I)
    {
        $I->comment('FirstCest test');
    }
}

```

tests/acceptance/SecondCest.php
```
<?php 

use Codeception\Example;


/**
 * @group g2
 */
class SecondCest
{
    /**
     * @example(foo="a", bar="b")
     * @example(foo="c", bar="d")
     */
    public function tryToTest(AcceptanceTester $I, Example $example)
    {
        $I->comment('SecondCest test');
    }
}

```


When I run codecept run --group g2 I have the correct behaviour now:
```
Codeception PHP Testing Framework v4.1.15
Powered by PHPUnit 9.5.1 by Sebastian Bergmann and contributors.
[Groups] g2

Acceptance Tests (2) -----------------------------------------------------------------------------------------------------------
✔ SecondCest: Try to test | "a","b" (0.00s)
✔ SecondCest: Try to test | "c","d" (0.00s)
--------------------------------------------------------------------------------------------------------------------------------

Functional Tests (0) -----------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------

Unit Tests (0) -----------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------


Time: 00:00.034, Memory: 10.00 MB

OK (2 tests, 0 assertions)
```

I'm closing this issue, feel free to reopen if it is not resolved.

**Closed by eXorus** 2021-01-19 17:02 UTC
