### ISSUE TITLE
Yii2 and REST modules causing PHPUnit_Framework_ExceptionWrapper

### ISSUE THREAD

**Issue by ThePeach** [Codeception/Codeception#1666] opened 2015-01-24 22:25 UTC
I've got the following functional test:
```php
$I->amGoingTo('ensure viewing someone else is forbidden');
$I->sendGET('users/'.($user['id']+1));
$I->seeResponseCodeIs(403);
```

which causes the following exception:
```
[snip]
* I am going to ensure viewing someone else is forbidden
* I send get "users/2"
  [Request] GET http://basic-dev.yii2.sandbox/v1/users/2
 ERROR 

[snip]

1) Failed to test the user rest api in UserAPICept (/mnt/workspace/yii2-book/tests/codeception/functional/UserAPICept.php)
Couldn't send get "users/2":
yii\web\ForbiddenHttpException: 

Scenario Steps:
22. I send get "users/2"
21. I am going to ensure viewing someone else is forbidden

  [PHPUnit_Framework_ExceptionWrapper]

FAILURES!                           
Tests: 1, Assertions: 11, Errors: 1.
```

If I manually test this scenario using PostMan I get the expected response header 403, which is generated from Yii by a simple: `throw new ForbiddenHttpException;`

**Comment by Ragazzo** [comment] 2015-01-24 22:30
yes , it is a know problem , unfortunatly currently we dont know how to test such situations when you throw an exception in functional tests and it does not catched by any code. As a workaround you can try to write your own `RestExceptionHandler` or set to `Yii::$app->response->setStatusCode(403)` in your controller

**Comment by Ragazzo** [comment] 2015-01-25 00:28
duplicate of https://github.com/Codeception/Codeception/issues/1666

**Comment by ThePeach** [comment] 2015-01-25 11:08
Ouch, interesting one. I'm just throwing this one, but won't be a try-catch on CodeCeption side solve this or it's impossible? I haven't spent enough time on CodeCeption internals to know if this is feasible.

Of the two solutions, which one would you suggest to implement?

**Comment by DavertMik** [comment] 2015-02-02 02:34
`PHPUnit_Framework_ExceptionWrapper` is expanded in 2.0.10 (and current 2.0 branch)

**Closed by DavertMik** 2015-02-02 02:34 UTC
Labels: yii

**Comment by m8rge** [comment] 2015-03-02 09:42
Personally, I wrote this codeception module https://gist.github.com/m8rge/8daa019c02e39420c024
