### ISSUE TITLE
HTML report aggregates results from scenarios called more times

### ISSUE THREAD

**Issue by mirao** [Codeception/Codeception#4158] opened 2017-04-23 18:16 UTC
#### What are you trying to achieve?
I have a Cest test where one scenario `$confirmPasswordPage->openConfirmation()` is called twice:
```
    public function verifyConfirmation(AcceptanceTester $I, ConfirmPassword $confirmPasswordPage, Headers $headersPage) {
        // Open invalid confirmation link
        $confirmPasswordPage->openConfirmation(ConfirmPassword::$urlInvalid);
        ..... 
        other scenarios
        .....
        // Open valid confirmation link from the email
        $confirmPasswordPage->openConfirmation($confirmPasswordPage->getConfirmLink());
        .....
        other scenarios
    }
```
I would expect that HTML report shows results in two separate scenarios

#### What do you get instead?

HTML report shows steps from both scenarios in one section, see the attached screenshot.
![selection_027](https://cloud.githubusercontent.com/assets/12584138/25316144/b5ba5608-2861-11e7-84a8-aa438ac08d51.png)
### Details

* Codeception version: 2.2.10
* PHP Version: 7.0.15
* Operating System: Ubuntu 17.04
* Installation type: Composer
* List of installed packages
---
ahmedsamy/codeception-smtp-mail    v0.6   Test emails in your Codeception acceptance tests
behat/gherkin                      v4.4.5 Gherkin DSL parser for PHP 5.3
codeception/codeception            2.2.10 BDD-style testing framework
doctrine/instantiator              1.0.5  A small, lightweight utility to instantiate objects in PHP without invoking their constructors
facebook/webdriver                 1.4.0  A PHP client for Selenium WebDriver
guzzlehttp/guzzle                  6.2.3  Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1 Guzzle promises library
guzzlehttp/psr7                    1.4.2  PSR-7 message implementation that also provides common utility methods
myclabs/deep-copy                  1.6.0  Create deep copies (clones) of your objects
php-imap/php-imap                  2.0.3  PHP class to access mailbox by POP3/IMAP/NNTP using IMAP extension
phpdocumentor/reflection-common    1.0    Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  3.1.1  With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is ...
phpdocumentor/type-resolver        0.2.1  
phpspec/prophecy                   v1.7.0 Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          4.0.7  Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          1.4.2  FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1  Simple template engine.
phpunit/php-timer                  1.0.9  Utility class for timing
phpunit/php-token-stream           1.4.11 Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    5.7.17 The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       3.4.3  Mock Object library for PHPUnit
psr/http-message                   1.0.1  Common interface for HTTP messages
psr/log                            1.0.2  Common interface for logging libraries
sebastian/code-unit-reverse-lookup 1.0.1  Looks up which function or method a line of code belongs to
sebastian/comparator               1.2.4  Provides the functionality to compare PHP values for equality
sebastian/diff                     1.4.1  Diff implementation
sebastian/environment              2.0.0  Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 2.0.0  Provides the functionality to export PHP variables for visualization
sebastian/global-state             1.1.1  Snapshotting of global state
sebastian/object-enumerator        2.0.1  Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context        2.0.0  Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0  Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1  Library that helps with managing the version number of Git-hosted PHP projects
stecman/symfony-console-completion 0.7.0  Automatic BASH completion for Symfony Console Component based applications.
symfony/browser-kit                v3.2.6 Symfony BrowserKit Component
symfony/console                    v3.2.6 Symfony Console Component
symfony/css-selector               v3.2.6 Symfony CssSelector Component
symfony/debug                      v3.2.6 Symfony Debug Component
symfony/dom-crawler                v3.2.6 Symfony DomCrawler Component
symfony/event-dispatcher           v3.2.6 Symfony EventDispatcher Component
symfony/finder                     v3.2.6 Symfony Finder Component
symfony/polyfill-mbstring          v1.3.0 Symfony polyfill for the Mbstring extension
symfony/process                    v3.2.6 Symfony Process Component
symfony/yaml                       v3.2.6 Symfony Yaml Component
webmozart/assert                   1.2.0  Assertions to validate method input/output with nice error messages.

**Comment by reinholdfuereder** [comment] 2019-03-15 08:41
I am pretty sure this is the same problem as in #4413 

@Naktibalda Would you mind linking these issues and closing one of them with "Duplicate" (or so)?

**Comment by Naktibalda** [comment] 2019-03-15 09:09
Duplicate of #4413

**Closed by Naktibalda** 2019-03-15 09:09 UTC
