### ISSUE TITLE
EventDispatcherInterface::dispatch() -> method with the event name as the first argument is deprecated since Symfony 4.3

### ISSUE THREAD

**Issue by voku** [Codeception/Codeception#5896] opened 2020-03-30 10:18 UTC
#### What are you trying to achieve?

Running ```codecept.phar run``` after upgrading from v3 ⇉ v4

#### What do you get instead?

```bash
ErrorNo:16384 Error:Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead. File:phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/vendor/symfony/event-dispatcher/EventDispatcher.php Line:58
```

```bash
Backtrace + Parameter:

<>"ErrorHandlerLib->handleError" on line: <>
	Called with params: 16384, "Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead...", "phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/vendor/symfony/event-dispatcher/EventDispatcher.php", 58, Array(2) {'event' => "module.init" | 'eventName' => Object(Codeception\Event\SuiteEvent) |  }

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/vendor/symfony/event-dispatcher/EventDispatcher.php>"trigger_error" on line: <58>
	Called with params: "Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead...", 16384

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/vendor/codeception/codeception/src/Codeception/Event/DispatcherWrapper.php>"Symfony\Component\EventDispatcher\EventDispatcher->dispatch" on line: <25>
	Called with params: "module.init", Object(Codeception\Event\SuiteEvent)

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/vendor/codeception/codeception/src/Codeception/SuiteManager.php>"Codeception\SuiteManager->dispatch" on line: <81>
	Called with params: Object(Symfony\Component\EventDispatcher\EventDispatcher), "module.init", Object(Codeception\Event\SuiteEvent)

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/vendor/codeception/codeception/src/Codeception/Codecept.php>"Codeception\SuiteManager->initialize" on line: <192>

	Called By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/vendor/codeception/codeception/src/Codeception/Codecept.php>"Codeception\Codecept->runSuite" on line: <185>
	Called with params: Array(26) {'modules' => Array(3) {'config' => Array(1) {'WebDriver' => Array(10) {'url' => "http://localhost" | 'capabilities' => Array(1) {'chromeOptions' => Array(2) {'args' => Array(1) {0 => "--window-size=1920,1080" |  } | 'binary' => "/usr/bin/chromium-browser" |  } |  } | 'browser' => "chrome" | 'port' => 9515 | 'window_size' => False |  ...  } |  } | 'enabled' => Array(4) {0 => "WebDriver" | 1 => "Asserts" | 2 => "\Helper\Acceptance" | 3 => Array(1) {'\Codeception\Module\VisualCeption' => Array(4) {'maximumDeviation' => 0.05 | 'saveCurrentImageIfFailure' => True | 'fullScreenShot' => True | 'report' => True |  } |  } |  } | 'depends' => Array(0) |  } | 'class_name' => "AcceptanceTester" | 'lint' => True | 'shuffle' => False | 'colors' => True |  ...  }, "acceptance (local)", "App/modules/Rechnungen/UebersichtListe/RechnungenUebersichtListeView_VDMG_AcceptanceCest.php"

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/vendor/codeception/codeception/src/Codeception/Command/Run.php>"Codeception\Codecept->run" on line: <391>
	Called with params: "acceptance", "App/modules/Rechnungen/UebersichtListe/RechnungenUebersichtListeView_VDMG_AcceptanceCest.php", Array(26) {'modules' => Array(3) {'config' => Array(1) {'WebDriver' => Array(10) {'url' => "http://localhost" | 'capabilities' => Array(1) {'chromeOptions' => Array(2) {'args' => Array(1) {0 => "--window-size=1920,1080" |  } | 'binary' => "/usr/bin/chromium-browser" |  } |  } | 'browser' => "chrome" | 'port' => 9515 | 'window_size' => False |  ...  } |  } | 'enabled' => Array(4) {0 => "WebDriver" | 1 => "Asserts" | 2 => "\Helper\Acceptance" | 3 => Array(1) {'\Codeception\Module\VisualCeption' => Array(4) {'maximumDeviation' => 0.05 | 'saveCurrentImageIfFailure' => True | 'fullScreenShot' => True | 'report' => True |  } |  } |  } | 'depends' => Array(0) |  } | 'class_name' => "AcceptanceTester" | 'lint' => True | 'shuffle' => False | 'colors' => True |  ...  }

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/vendor/symfony/console/Command/Command.php>"Codeception\Command\Run->execute" on line: <255>
	Called with params: Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/vendor/symfony/console/Application.php>"Symfony\Component\Console\Command\Command->run" on line: <1001>
	Called with params: Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/vendor/symfony/console/Application.php>"Symfony\Component\Console\Application->doRunCommand" on line: <271>
	Called with params: Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/vendor/symfony/console/Application.php>"Symfony\Component\Console\Application->doRun" on line: <147>
	Called with params: Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/vendor/codeception/codeception/src/Codeception/Application.php>"Symfony\Component\Console\Application->run" on line: <117>
	Called with params: Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/vendor/codeception/codeception/app.php>"Codeception\Application->run" on line: <46>

	Called By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/vendor/codeception/codeception/app.php>"{closure}" on line: <47>

	Called By: </home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar>"require_once" on line: <5>
```

### Details

* Codeception version: 4.1.4
* PHP Version: 7.4
* Operating System: Ubuntu 18.04
* Installation type: Phar

**Comment by Naktibalda** [comment] 2020-03-30 11:12
It could be a duplicate of #5860

Does your project use any Symfony components installed using composer?

**Comment by voku** [comment] 2020-03-30 11:32
> It could be a duplicate of #5860
> 
> Does your project use any Symfony components installed using composer?

We only use "css-selector", "process" and "var-dumper" from symfony, no other symfony dependencies are in use.

**Comment by Naktibalda** [comment] 2020-03-30 11:48
More information about your project is necessary in order to undestand what makes it fail.

If you use codecept.phar to run WebDriver tests, it would be safer to run it from directory which has no vendor subdirectory.
If you use some Codeception module to test application code directly, it would be much better to install Codeception using Composer.

**Comment by voku** [comment] 2020-03-31 13:22
It's because of your global php error handler, every warning etc. triggers an error. So here we have only an "E_USER_DEPRECATED" (16384) but we see an error.

So I think a "@"-char before the "dispatch"-calls would fix that, but maybe I should ignore "E_USER_DEPRECATED"-errors at all? 

https://github.com/Codeception/Codeception/blob/4.x/src/Codeception/Event/DispatcherWrapper.php

**Comment by Naktibalda** [comment] 2020-04-01 10:11
Please provide instructions how to reproduce this error in empty directory.

**Comment by Naktibalda** [comment] 2020-04-19 13:54
I will close this issue unless instructions how to reproduce this issue are provided.

**Comment by voku** [comment] 2020-04-19 23:03
Here (https://github.com/voku/Codeception-TestAutomationFramework) I added a small test repository where you can see the error, but maybe it's not my best idea to catch all E_* errors / warnings / ... at all?

```
In ErrorHandlerLib.php line 146:
                                                                                                                                                         
  Backtrace + Parameter:                                                                                                                                 
                                                                                                                                                         
  <>"ErrorHandlerLib->handleError" on line: <>                                                                                                           
        Called with params: 16384, "Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the f  
  irst argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead...", "phar:/  
  //home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar/vendor/symfony/event-dispatcher/EventDispatcher.php", 58,   
  Array(2) {'event' => "module.init" | 'eventName' => Object(Codeception\Event\SuiteEvent) |  }                                                          
                                                                                                                                                         
        By: <phar:///home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar/vendor/symfony/event-dispatcher/EventDispatche  
  r.php>"trigger_error" on line: <58>                                                                                                                    
        Called with params: "Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first ar  
  gument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead...", 16384           
                                                                                                                                                         
        By: <phar:///home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar/vendor/codeception/codeception/src/Codeception  
  /Event/DispatcherWrapper.php>"Symfony\Component\EventDispatcher\EventDispatcher->dispatch" on line: <25>                                               
        Called with params: "module.init", Object(Codeception\Event\SuiteEvent)                                                                               
                                                                                                                                                         
        By: <phar:///home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar/vendor/codeception/codeception/src/Codeception  
  /SuiteManager.php>"Codeception\SuiteManager->dispatch" on line: <81>                                                                                   
        Called with params: Object(Symfony\Component\EventDispatcher\EventDispatcher), "module.init", Object(Codeception\Event\SuiteEvent)                    
                                                                                                                                                         
        By: <phar:///home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar/vendor/codeception/codeception/src/Codeception  
  /Codecept.php>"Codeception\SuiteManager->initialize" on line: <192>                                                                                    
                                                                                                                                                         
        Called By: <phar:///home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar/vendor/codeception/codeception/src/Code  
  ception/Codecept.php>"Codeception\Codecept->runSuite" on line: <185>                                                                                   
        Called with params: Array(26) {'modules' => Array(3) {'config' => Array(1) {'WebDriver' => Array(10) {'url' => "http://localhost:8887" | 'capabiliti  
  es' => Array(1) {'chromeOptions' => Array(2) {'args' => Array(2) {0 => "--no-sandbox" | 1 => "--window-size=1920,1080" |  } | 'binary' => "/usr/bin/c  
  hromium-browser" |  } |  } | 'browser' => "chrome" | 'port' => 9515 | 'window_size' => False |  ...  } |  } | 'enabled' => Array(4) {0 => "WebDriver"  
   | 1 => "Asserts" | 2 => "\Helper\Acceptance" | 3 => Array(1) {'\Codeception\Module\VisualCeption' => Array(4) {'maximumDeviation' => 0.05 | 'saveCur  
  rentImageIfFailure' => True | 'fullScreenShot' => True | 'report' => True |  } |  } |  } | 'depends' => Array(0) |  } | 'class_name' => "AcceptanceTe  
  ster" | 'lint' => True | 'shuffle' => False | 'colors' => True |  ...  }, "acceptance (local)", Null                                                   
                                                                                                                                                         
        By: <phar:///home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar/vendor/codeception/codeception/src/Codeception  
  /Command/Run.php>"Codeception\Codecept->run" on line: <503>                                                                                            
        Called with params: "acceptance"                                                                                                                      
                                                                                                                                                         
        By: <phar:///home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar/vendor/codeception/codeception/src/Codeception  
  /Command/Run.php>"Codeception\Command\Run->runSuites" on line: <397>                                                                                   
        Called with params: Array(4) {'acceptance' => "acceptance" | 'api' => "api" | 'functional' => "functional" | 'unit' => "unit" |  }, Array(0)          
                                                                                                                                                         
        By: <phar:///home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar/vendor/symfony/console/Command/Command.php>"Co  
  deception\Command\Run->execute" on line: <255>                                                                                                         
        Called with params: Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)                         
                                                                                                                                                         
        By: <phar:///home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar/vendor/symfony/console/Application.php>"Symfon  
  y\Component\Console\Command\Command->run" on line: <1001>                                                                                              
        Called with params: Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)                         
                                                                                                                                                         
        By: <phar:///home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar/vendor/symfony/console/Application.php>"Symfon  
  y\Component\Console\Application->doRunCommand" on line: <271>                                                                                          
        Called with params: Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Cons  
  oleOutput)                                                                                                                                             
                                                                                                                                                         
        By: <phar:///home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar/vendor/symfony/console/Application.php>"Symfon  
  y\Component\Console\Application->doRun" on line: <147>                                                                                                 
        Called with params: Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)                         
                                                                                                                                                         
        By: <phar:///home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar/vendor/codeception/codeception/src/Codeception  
  /Application.php>"Symfony\Component\Console\Application->run" on line: <117>                                                                           
        Called with params: Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)                         
                                                                                                                                                         
        By: <phar:///home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar/vendor/codeception/codeception/app.php>"Codece  
  ption\Application->run" on line: <46>                                                                                                                  
                                                                                                                                                         
        Called By: <phar:///home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar/vendor/codeception/codeception/app.php>  
  "{closure}" on line: <47>                                                                                                                              
                                                                                                                                                         
        Called By: </home/lmoelleken/testing/git/Codeception-TestAutomationFramework/thirdparty/codecept.phar>"require_once" on line: <5>                     
  Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated s  
  ince Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead. 
``'

**Comment by Naktibalda** [comment] 2020-04-20 06:05
Well, if your error handler turns deprecation messages to exceptions, then it is a problem of your error handler.

It is a bad idea to do that anyway, because it turns deprecation messages in minor version bumps to breaking changes, so Codeception stopped doing that few years ago.

Your options:
a) Update your error handler to stop throwing exceptions for deprecation messages.
b) Use https://codeception.com/php56/codecept.phar which is bundled with Symfony 3 and doesn't  have that deprecation problem.
c) Install Codeception using composer and get it with Symfony v5 components, so it won't emit those deprecation messages either.

**Closed by Naktibalda** 2020-04-20 06:05 UTC
