### ISSUE TITLE
[Module Db]. Problem with postgresql schema name qualification.

### ISSUE THREAD

**Issue by corvinusy** [Codeception/Codeception#1001] opened 2014-05-07 00:12 UTC
I cannot find the way to qualify schema names for postgresql databases.
If I write

        $I->seeInDatabase('schemma.users', array('user_id' => 1));

then it ends with 
***
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "schemma.users" doesn't exist
LINE 1: select count(*) from "schemma.users" where user_id = $1 
***

It happens because I have table users in schema "schemma" in the database. And I have no table "schemma.users" within the 'public' schema.

Quoted table names is a special (not recommended by postgresql developers) case.

        select count( * ) from "schemma.users" where user_id = $1;  -- problem
        -- related to table "schemma.users", not to "schemma"."users"

        select count( * ) from "schemma"."users" where user_id = $1; -- OK 
        -- related to table schemma.users.

It can be suitable to parse postgresql table names for schema qualification.

**Comment by zbateson** [comment] 2015-04-03 22:45
Duplicate of #970

**Comment by Naktibalda** [comment] 2015-08-19 19:49
Fixed by #1487

**Closed by Naktibalda** 2015-08-19 19:49 UTC
