### ISSUE TITLE
The request was not redirected

### ISSUE THREAD

**Issue by nnnikolay** [Codeception/Codeception#3269] opened 2016-06-24 07:40 UTC
All my POST requests in functional tests on version 2.2.1 starts failing with following message

> [LogicException] The request was not redirected.   

I've read documentation and changelog but did not found any recipe how can I turn off that super smart Logical checks.

P.S. On version 2.1.8  all my tests pass

**Comment by Naktibalda** [comment] 2016-06-24 09:03
Duplicate of #3171

Fixed in the branch, 2.2.2 will be good.

**Closed by Naktibalda** 2016-06-24 09:03 UTC
