### ISSUE TITLE
"Command Did Not Finish Properly" with no additional information

### ISSUE THREAD

**Issue by raynox** [Codeception/Codeception#4896] opened 2018-03-29 15:05 UTC
#### What are you trying to achieve?

I try to test Phalcon API using Codeception.

#### What do you get instead?

Codeception PHP Testing Framework v2.4.0
Powered by PHPUnit 5.7.23 by Sebastian Bergmann and contributors.

Api Tests (1) ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: \Helper\Api, Phalcon, REST
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
RegisterUserCept: Create a user via API
Signature: RegisterUserCept
Test: tests/api/RegisterUserCept.php
Scenario --
  [Database] Transaction started
 I send post "/user/register",{"name":"John","surname":"Davert","phone":"34345345345","password":"asdacvre1D","repassword":"asdacvre1D","email":"davert@codeception.com"}
  [Request] POST /user/register {"name":"John","surname":"Davert","phone":"34345345345","password":"asdacvre1D","repassword":"asdacvre1D","email":"davert@codeception.com"}
  [Request Headers] []
{"errors":[],"validationException":false,"userExist":false,"userInActive":false,"userBlock":false,"userSaved":true,"activationLink":"http:\/\/client.przelewy24.local\/activate\/bfe2f3e2-cd53-4fa0-a0a7-4dc063f3416d","id":2731446}
Fatal error: Uncaught RuntimeException: Command Did Not Finish Properly in /var/www/html/api.przelewy24.local/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php:101
Stack trace:
#0 [internal function]: Codeception\Subscriber\ErrorHandler->shutdownHandler()
#1 {main}
  thrown in /var/www/html/api.przelewy24.local/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php on line 101

* Codeception version: 2.4.0
* PHP Version: 7.0.28
* Operating System: Ubuntu
* Installation type: Composer
* List of installed packages (`composer show`)

behat/gherkin                         v4.5.1  Gherkin DSL parser for PHP 5.3
christian-riesen/base32               1.3.1   Base32 encoder/decoder according to RFC 4648
codeception/codeception               2.4.0   BDD-style testing framework
codeception/phpunit-wrapper           6.0.8   PHPUnit classes used by Codeception
codeception/stub                      1.0.2   Flexible Stub wrapper for PHPUnit's Mock Builder
dnoegel/php-xdg-base-dir              0.1     implementation of xdg base directory specification for php
doctrine/annotations                  v1.4.0  Docblock Annotations Parser
doctrine/cache                        v1.6.2  Caching library offering an object-oriented API for many cache backends
doctrine/collections                  v1.4.0  Collections Abstraction library
doctrine/common                       v2.6.2  Common Library for Doctrine projects
doctrine/dbal                         v2.5.4  Database Abstraction Layer
doctrine/inflector                    v1.2.0  Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.0.5   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                        v1.0.1  Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/orm                          v2.5.6  Object-Relational-Mapper for PHP
dompdf/dompdf                         v0.6.2  DOMPDF is a CSS 2.1 compliant HTML to PDF converter
facebook/webdriver                    1.3.0   A PHP client for WebDriver
filp/whoops                           2.1.6   php error handling for cool kids
guzzlehttp/guzzle                     6.3.0   Guzzle is a PHP HTTP client library
guzzlehttp/promises                   v1.3.1  Guzzle promises library
guzzlehttp/psr7                       1.4.2   PSR-7 message implementation that also provides common utility methods
jakub-onderka/php-console-color       0.1    
jakub-onderka/php-console-highlighter v0.3.2 
myclabs/deep-copy                     1.7.0   Create deep copies (clones) of your objects
nikic/php-parser                      v3.1.1  A PHP parser written in PHP
paragonie/random_compat               v2.0.11 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phalcon-ext/mailer                    v2.1.0  Mailer component as wrapper over SwiftMailer for Phalcon.
phalcon/devtools                      v3.1.2  This tools provide you useful scripts to generate code helping to develop faster and easy applications that use with Phalcon framework.
phalcon/incubator                     v3.0.4  Adapters, prototypes or functionality that can be potentially incorporated to the C-framework.
phenx/php-font-lib                    0.2.2   A library to read, parse, export and make subsets of different types of font files.
php-amqplib/php-amqplib               v2.7.0  Formerly videlalvaro/php-amqplib.  This library is a pure PHP implementation of the AMQP protocol. It's been tested against RabbitMQ.
phpdocumentor/reflection-common       1.0.1   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     4.1.1   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver           0.4.0  
phpmailer/phpmailer                   v5.2.25 PHPMailer is a full-featured email creation and transfer class for PHP
phpspec/prophecy                      v1.7.2  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             4.0.8   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator             1.4.2   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1   Simple template engine.
phpunit/php-timer                     1.0.9   Utility class for timing
phpunit/php-token-stream              2.0.1   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       5.7.23  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          3.4.4   Mock Object library for PHPUnit
pragmarx/google2fa                    v1.0.1  A One Time Password Authentication package, compatible with Google Authenticator.
predis/predis                         v1.1.1  Flexible and feature-complete Redis client for PHP and HHVM
przelewy24/platform                   1.1.51 
psr/cache                             1.0.0   Common interface for caching libraries
psr/http-message                      1.0.1   Common interface for HTTP messages
psr/log                               1.0.0   Common interface for logging libraries
psy/psysh                             v0.8.13 An interactive shell for modern PHP.
sebastian/code-unit-reverse-lookup    1.0.1   Looks up which function or method a line of code belongs to
sebastian/comparator                  1.2.4   Provides the functionality to compare PHP values for equality
sebastian/diff                        1.4.3   Diff implementation
sebastian/environment                 2.0.0   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    2.0.0   Provides the functionality to export PHP variables for visualization
sebastian/global-state                1.1.1   Snapshotting of global state
sebastian/object-enumerator           2.0.1   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context           2.0.0   Provides functionality to recursively process PHP variables
sebastian/resource-operations         1.0.0   Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.1   Library that helps with managing the version number of Git-hosted PHP projects
shared-libraries/cacheable            1.0.3   Base caching interface based on psr-6 (cache)
shared-libraries/cacheable-memcached  1.0.5   Memcached implementation for cacheable
shared-libraries/database-redis       0.8.1   Redis support
shared-libraries/database-sql         0.2.16  Adapter for PDO database connection
shared-libraries/logger               0.4.7   Logger
shared-libraries/message-broker       0.6.0   Message broker for queueing systems.
shared-libraries/p24-entities         1.0.81  Entities from Przelewy24 system
shared-libraries/persistence          0.15    Wspólne repozytoria oraz gatewaye
shared-libraries/platform-logger      0.0.10  Logger package.
shared-libraries/value-object         1.0.64  ValueObject from P24
swiftmailer/swiftmailer               v5.4.8  Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                   v3.4.6  Symfony BrowserKit Component
symfony/console                       v3.3.10 Symfony Console Component
symfony/css-selector                  v3.4.6  Symfony CssSelector Component
symfony/debug                         v3.3.10 Symfony Debug Component
symfony/dom-crawler                   v3.4.6  Symfony DomCrawler Component
symfony/event-dispatcher              v3.4.6  Symfony EventDispatcher Component
symfony/finder                        v3.3.10 Symfony Finder Component
symfony/polyfill-mbstring             v1.6.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                v1.6.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-util                 v1.6.0  Symfony utilities for portability of PHP codes
symfony/process                       v3.4.6  Symfony Process Component
symfony/var-dumper                    v3.3.10 Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v3.0.2  Symfony Yaml Component
twig/extensions                       v1.5.1  Common additional features for Twig that do not directly belong in core
twig/twig                             v1.35.0 Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                      1.2.0   Assertions to validate method input/output with nice error messages.
zircote/swagger-php                   2.0.8   Swagger-PHP - Generate interactive documentation for your RESTful API using phpdoc annotations

* Suite configuration:

api.suite.yml:
```yml
actor: ApiTester
modules:
    enabled:
        - \Helper\Api
        - Phalcon:
            bootstrap: 'app/config/bootstrap.php'
            cleanup: true
            savepoints: true
        - REST:
            depends: Phalcon
```

**Comment by Naktibalda** [comment] 2018-03-29 18:24
Duplicate of #4880

"Command Did Not Finish Properly" is an additional information itself - it means that application code called exit or die function.

Before introduction of "Command Did Not Finish Properly" test execution simply ended successfully ( or unsuccessfully, depending on exit code) with no output.

Current implementation does not intercept die and exit calls, it only checks if test suite was executed to completion, so it is impossible to tell where the die was called.

However if die/exit had a message parameter, that message is displayed below stack trace.

**Comment by raynox** [comment] 2018-03-29 18:26
@Naktibalda ty man man for the reply, I'm going to find this die/exit tommorow!

**Closed** 2018-03-29 18:41 UTC
