### ISSUE TITLE
Method signature incompatibilities with PHPUnit 9

### ISSUE THREAD

**Issue by boesing** [Codeception/Codeception#6097] opened 2021-01-25 15:52 UTC
#### What are you trying to achieve?

I want to execute my codeception tests.

#### What do you get instead?

```bash
→ vendor/bin/codecept run
Codeception PHP Testing Framework v4.1.15
Powered by PHPUnit 9.5.1 by Sebastian Bergmann and contributors.
PHP Fatal error:  Declaration of Codeception\Test\Test::run(?PHPUnit\Framework\TestResult $result = NULL) must be compatible with PHPUnit\Framework\Test::run(?PHPUnit\Framework\TestResult $result = NULL): PHPUnit\Framework\TestResult in vendor/codeception/codeception/src/Codeception/Test/Test.php on line 19
```

```bash
→ vendor/bin/codecept run
Codeception PHP Testing Framework v4.1.15
Powered by PHPUnit 9.5.1 by Sebastian Bergmann and contributors.
PHP Fatal error:  Declaration of Codeception\Test\Test::toString() must be compatible with PHPUnit\Framework\SelfDescribing::toString(): string in vendor/codeception/codeception/src/Codeception/Test/Test.php on line 20

```

```bash
→ vendor/bin/codecept run
Codeception PHP Testing Framework v4.1.15
Powered by PHPUnit 9.5.1 by Sebastian Bergmann and contributors.
PHP Fatal error:  Declaration of Codeception\Test\Cest::toString() must be compatible with Codeception\Test\Test::toString(): string in vendor/codeception/codeception/src/Codeception/Test/Cest.php on line 16
```

### Details

* Codeception version: v4.1.15
* PHP Version: 7.3.25
* Operating System: macOS Catalina
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

**Comment by Naktibalda** [comment] 2021-01-26 07:32
Duplicate of #5031

This issue happens because you use some other library which implements compatibility with PHPUnit 7+ in a different way (the way used by Codeception wasn't great). You could get your tests working by removing that library.

This issue won't exist in Codeception 5.0 which drops support for old versions of PHPUnit, so it doesn't need that compatibility code. It will be released in second half of February, but you can try it now by setting composer constraint to `"codeception/codeception": "dev-5.0 as 4.9.99"`

**Closed by Naktibalda** 2021-01-26 07:32 UTC

**Comment by bitwombat** [comment] 2021-02-23 22:52
laminas/laminas-test is another cause of this conflict. Should be redundant functionality anyway.

I'm not sure why because it doesn't implement `PHPUnit\Framework\TestResult`
