### ISSUE TITLE
Should generate:suite also create the appropriate test folder?

### ISSUE THREAD

**Issue by krukru** [Codeception/Codeception#4251] opened 2017-05-24 13:40 UTC
#### What are you trying to achieve?
When adding a new suite I would expect that the test folder for the new suite (`tests/some-new-suite`) would also be created, but it does not get created until you generate your first test in that suite.

How to reproduce?
1. In a clean folder, run `codecept bootstrap`. Note that the `tests/unit`, `tests/functional`, `tests/acceptance` folders are created, but empty
2. Create a new suite `codecept generate:suite integration`

Expected: The folder `tests/integration` has been created, just like unit/functional/acceptance have empty folders
Actual: The folder is missing until you create your first test in that suite.

Maybe I am wrong, but it would be consistent with `codecept bootstrap` to also create the tests folder at suite-creation time.

I can put together a PR if needed

### Details

* Codeception version: 2.3.1
* PHP Version: PHP 7.0.17 (cli) (built: Apr  3 2017 13:42:03) ( NTS )
* Operating System: macOS Sierrs 10.12.4
* Installation type: Composer

**Comment by DavertMik** [comment] 2017-05-25 02:49
Looks like a regression of 2.3
Before 2.3 we had bootstrap file always enabled so it has been placed into the tests directory so it was always created. Now we disabled bootstrap by default so dir is not created... Anyway, this should be fixed

**Closed** 2017-05-26 23:51 UTC
Labels: BUG, Generators
