### ISSUE TITLE
Calling getInternalResponse method before the request is deprecated

### ISSUE THREAD

**Issue by terabytesoftw** [Codeception/Codeception#5341] opened 2019-01-13 11:33 UTC
#### What are you trying to achieve?
Run test acceptance.

#### What do you get instead?
6x DEPRECATION: Calling the "Symfony\Component\BrowserKit\Client::getInternalResponse()" method before the "request()" one is deprecated since Symfony 4.1 and will throw an exception in 5.0.

> Provide console output if related. Use `-vvv` mode for more details.

1) AboutCest: Ensure that about page works.
 Test  tests/acceptance/AboutCest.php:aboutPageTest
                                                                                                                                           
  [GuzzleHttp\Exception\ConnectException] cURL error 52: Empty reply from server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) 

### Details

* Codeception version: 2.5.x-dev eaeafde
* PHP Version: 7.3 
* Operating System: Centos 7
* Installation type: Composer
```

**Comment by Naktibalda** [comment] 2019-01-13 12:49
So the problem is that your server does not respond.

**Comment by Naktibalda** [comment] 2019-07-26 07:54
I am reopenning this issue, because I am getting the same deprecation message with Symfony module whenever the app code throws an unhandled exception:

> 2x DEPRECATION: Calling the "Codeception\Lib\Connector\Symfony::getInternalResponse()" method before the "request()" one is deprecated since Symfony 4.1 and will throw an exception in 5.0. /.../vendor/symfony/browser-kit/Client.php:219

```
2) TestCest: Returns error when parameters are invalid
 Test  tests/functional/TestCest.php:returnsErrorWhenParametersAreInvalid

  [Symfony\Component\HttpKernel\Exception\NotFoundHttpException] No route found for "POST /test1"


Scenario Steps:

 1. $I->sendPOST("/test1",[]) at tests/functional/TestCest.php:31

#1  /.../vendor/symfony/http-kernel/EventListener/RouterListener.php:141
#2  /.../vendor/symfony/event-dispatcher/EventDispatcher.php:298
#3  /.../vendor/symfony/event-dispatcher/EventDispatcher.php:260
#4  /.../vendor/symfony/event-dispatcher/EventDispatcher.php:235
#5  /.../vendor/symfony/event-dispatcher/EventDispatcher.php:75
#6  /.../vendor/symfony/http-kernel/HttpKernel.php:127
#7  /.../vendor/symfony/http-kernel/HttpKernel.php:68
#8  /.../vendor/symfony/http-kernel/Kernel.php:198
#9  /.../vendor/symfony/http-kernel/Client.php:65
#10 /.../vendor/symfony/browser-kit/Client.php:407
```

**Comment by Naktibalda** [comment] 2019-07-26 08:12
`getInternalRequest` is called by [InnerBrowser::_failed](https://github.com/Codeception/Codeception/blob/3.0.3/src/Codeception/Lib/InnerBrowser.php#L60)

I see 2 ways to fix it.
1. Make all modules catch exceptions in `doRequest` method and set some `thrownExceptionInRequest` property which could be checked instead of calling `getInternalResponse`.
2. Create an alternative method for checking internal response.

I think that the second way is easier to implement
```php
trait InternalResponseChecker
{
  public function hasInternalResponse()
  {
    return $this->internalResponse !== null;
  }
}
```

then add `use InternalResponseChecker` to all connectors.

**Comment by ruudboon** [comment] 2019-07-31 08:47
@Naktibalda Would it be possible to add this to 3.0.x already? Would be nice to get rid of those deprecation messages before 4 drops.

**Comment by paoloacruz** [comment] 2019-08-13 07:47
Hello,

I'm also encountering this issue here's the full error DEPRECATION: Calling the "Codeception\Lib\Connector\Guzzle::getInternalResponse()" method before the "request()" one is deprecated since Symfony 4.1 and will throw an exception in 5.0. /var/www/                                        html/tourist-portal/vendor/symfony/browser-kit/Client.php:219

Can someone suggest how to resolve it?

**Comment by Naktibalda** [comment] 2019-08-13 09:59
The easiest option is to ignore deprecation message (Does `@` do that?) in Symfony 4 and catch exception in Symfony 5.

**Closed** 2019-11-24 16:32 UTC
