### ISSUE TITLE
When --steps is set, --coverage does not take effect

### ISSUE THREAD

**Issue by mipon** [Codeception/Codeception#1765] opened 2015-03-10 04:24 UTC
This does not generate coverage files.

```
php codecept.phar run unit --steps --coverage
```

However, this does.
```
php codecept.phar run unit --coverage
```

This also applies to `--coverage-xml` and `--coverage-html`.

**Comment by nsossonko** [comment] 2015-09-17 21:24
This should go in release notes, it was a very confusing issue to debug...

**Comment by Naktibalda** [comment] 2016-05-30 22:01
Duplicate of #2620  Fixed today.

**Closed by Naktibalda** 2016-05-30 22:01 UTC
Labels: BUG, Coverage
