### ISSUE TITLE
No code coverage driver available

### ISSUE THREAD

**Issue by RyanHavoc** [Codeception/Codeception#2773] opened 2016-02-05 16:09 UTC
I'm running Codeception 2.1.5 with C3 2.0.5 under Laravel 5.2. Everything was working a treat last week but no when I run `composer update` I get:

    The "codeception/c3" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).

And when I `codecept run --coverage-html` I get:

```
Codeception PHP Testing Framework v2.1.5
Powered by PHPUnit 4.8.22 by Sebastian Bergmann and contributors.


  [PHP_CodeCoverage_Exception]
  No code coverage driver available
```

Is there a workaround to get code coverage working again?

**Comment by raistlin** [comment] 2016-02-06 14:47
Duplicate of #2745

**Closed by raistlin** 2016-02-06 14:47 UTC

**Comment by Naktibalda** [comment] 2016-02-06 21:28
`No code coverage driver available` means that xdebug is not enabled.

**Comment by RyanHavoc** [comment] 2016-02-07 12:22
@Naktibalda That's what I thought but xdebug is enabled and appears in phpinfo as so. As I say everything was working find last week and the config of my VM hasn't changed. I naturally assumed that the issue must be related to this new warning has appeared in Composer?
