### ISSUE TITLE
Call to a member function setRefreshMaxInterval() on null

### ISSUE THREAD

**Issue by thomas-spigel** [Codeception/Codeception#2080] opened 2015-06-23 15:53 UTC
Hello, after recent upgrades, on running the acceptance tests, i get the error. Tested on multiple computers/environments, with the same result. Removing the configuration and running bootstrap didn't help to fix the problem too.

I'm using the master branch of codeception.
```
PHP 5.6.4-4ubuntu6 (cli) (built: Apr 17 2015 15:47:51)
```

```
PHP Fatal error:  Call to a member function setRefreshMaxInterval() on null in www/vendor/codeception/codeception/src/Codeception/Module/PhpBrowser.php on line 251
PHP Stack trace:
PHP   1. {main}() vendor/codeception/codeception/codecept:0
PHP   2. Symfony\Component\Console\Application->run() vendor/codeception/codeception/codecept:28
PHP   3. Symfony\Component\Console\Application->doRun() vendor/symfony/console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() vendor/symfony/console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() vendor/symfony/console/Application.php:878
PHP   6. Codeception\Command\Run->execute() vendor/symfony/console/Command/Command.php:259
PHP   7. Codeception\Command\Run->runSuites() vendor/codeception/codeception/src/Codeception/Command/Run.php:192
PHP   8. Codeception\Codecept->run() vendor/codeception/codeception/src/Codeception/Command/Run.php:264
PHP   9. Codeception\Codecept->runSuite() vendor/codeception/codeception/src/Codeception/Codecept.php:167
PHP  10. Codeception\SuiteManager->run() vendor/codeception/codeception/src/Codeception/Codecept.php:195
PHP  11. Codeception\PHPUnit\Runner->doEnhancedRun() vendor/codeception/codeception/src/Codeception/SuiteManager.php:149
PHP  12. PHPUnit_Framework_TestSuite->run() vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:88
PHP  13. PHPUnit_Framework_TestCase->run() vendor/phpunit/phpunit/src/Framework/TestSuite.php:738
PHP  14. PHPUnit_Framework_TestResult->run() vendor/phpunit/phpunit/src/Framework/TestCase.php:702
PHP  15. PHPUnit_Framework_TestCase->runBare() vendor/phpunit/phpunit/src/Framework/TestResult.php:601
PHP  16. PHPUnit_Framework_TestCase->runTest() vendor/phpunit/phpunit/src/Framework/TestCase.php:746
PHP  17. ReflectionMethod->invokeArgs() vendor/phpunit/phpunit/src/Framework/TestCase.php:881
PHP  18. Codeception\TestCase\Cept->testCodecept() vendor/phpunit/phpunit/src/Framework/TestCase.php:881
PHP  19. Codeception\TestCase\Cept->fire() vendor/codeception/codeception/src/Codeception/TestCase/Cept.php:58
PHP  20. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() vendor/codeception/codeception/src/Codeception/TestCase/Shared/Actor.php:71
PHP  21. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() vendor/symfony/event-dispatcher/EventDispatcher.php:53
PHP  22. call_user_func:{vendor/symfony/event-dispatcher/EventDispatcher.php:168}() vendor/symfony/event-dispatcher/EventDispatcher.php:168
PHP  23. Codeception\Subscriber\Module->before() vendor/symfony/event-dispatcher/EventDispatcher.php:168
PHP  24. Codeception\Module\PhpBrowser->_before() vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:58
PHP  25. Codeception\Module\PhpBrowser->_initializeSession() vendor/codeception/codeception/src/Codeception/Module/PhpBrowser.php:112
```

**Comment by Naktibalda** [comment] 2015-06-23 16:02
Duplicate of #2075

**Comment by Naktibalda** [comment] 2015-06-23 16:04
I merged it into master a minute ago.

**Closed** 2015-06-23 20:05 UTC
