### ISSUE TITLE
Running functional test using BDD is too slow

### ISSUE THREAD

**Issue by Cyansilver** [Codeception/Codeception#4551] opened 2017-10-05 09:31 UTC
#### What are you trying to achieve?

- Run the functional test using gherkin should be fast

#### What do you get instead?
- It's too slow. Only one Scenario in one feature file but it takes ~6s to finish

```bash
vendor/bin/codecept run functional --no-rebuild -v

Codeception PHP Testing Framework v2.3.6
Powered by PHPUnit 4.8.24 by Sebastian Bergmann and contributors.

Functional Tests (1) ----------------------------------------------------------------------------------
Modules: REST, Laravel5, \Helper\Functional, DataFactory
-----------------------------------------------------
✔ create: Happy Path (0.80s)
------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 6.23 seconds, Memory: 43.50Mb

```
### Details

* Codeception version: v2.3.6
* PHP Version: 5.6
* Operating System: centos 7
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: FunctionalTester
modules:
    enabled:
        - REST:
            depends: Laravel5
        - \Helper\Functional
        - Laravel5:
            environment_file: .env.testing
            cleanup: false
        - DataFactory:
            factories: tests/_support/factories
            depends: Laravel5
```

**Comment by DavertMik** [comment] 2017-10-07 08:30
> PHP Version: 5.6

You know, you can upgrade to 7.0 to get 2x speed improvement :)

Sorry, this information is not enough to reproduce or work out on this issue.
Questions should be answered:

* Is that happens only for Gherkin or same with other formats like Cest
* How many steps you have in scenario

because as for me Laravel tests run really fast. Esp with `cleanup: true` option enabled

**Comment by Cyansilver** [comment] 2017-10-10 04:56
Hi DavertMik,

- I changed the test to Cest, and the result is faster a little bit ~4s.
- There are 4 steps in the scenario:
   - First create a record in db with factory
   - Call api with POST method
   - Call api with POST method
   - Verify records in db

I put a measure time in the function, It's around ~1s same with the result in: `✔ create: Happy Path (0.80s)`
So I wonder why the last line is: Time: 6.23 seconds, Memory: 43.50Mb

**Comment by DavertMik** [comment] 2017-10-14 10:15
Technically there is a room for optimizations and caching for BDD Loader. 
Could you take a look https://github.com/Codeception/Codeception/blob/2.3/src/Codeception/Test/Loader/Gherkin.php

Maybe you get some ideas how to improve it so it would load and parse BDD scenarios faster. I assume the bottleneck could be loading extra files and running reflection there

**Comment by Naktibalda** [comment] 2021-01-09 16:04
This question is not specific, it is just a general complaint about performance, so I am closing it.

**Closed by Naktibalda** 2021-01-09 16:04 UTC
Labels: performance
