### ISSUE TITLE
RunFailed doesn't log failed examples

### ISSUE THREAD

**Issue by teeencho** [Codeception/Codeception#3390] opened 2016-07-29 15:29 UTC
I want to rerun failed examples using the `failed` group

When a test has examples that passed, and examples that didn't, it is not logged as failed. Perhaps the whole test could be logged as failed, even better if only the failed examples.

**Comment by eXorus** [comment] 2021-05-31 12:28
I can't reproduce anymore. With Codeception 4.1.20, if one example failed, I have the whole test in the failed file.
I'm closing this issue, feel free to reopen if it is necessary.

**Closed by eXorus** 2021-05-31 12:28 UTC
Labels: Bug
