### ISSUE TITLE
Empty radio buttons not send (Yii2)

### ISSUE THREAD

**Issue by dynasource** [Codeception/Codeception#1573] opened 2014-12-03 21:18 UTC
I was testing a radio button, specifically for it being selected or not (if not getting a validation error).

The problem is that the data of a unselected radiobutton was not to be found in the POST. This is behavior by default in ie. by Chrome. Yii2 fixes this by inserting a hidden input like this:
```html
<input type="hidden" name="Item[type]" value="">
<input type="radio" name="Item[type]" value="0"> Gezocht</label>
<input type="radio" name="Item[type]" value="1"> Aangeboden</label></div>
```

Unfortunately, Codeception does not do a post of the Item[type] which breaks my software logic. In the browser it works fine.

**Comment by tomtomsen** [comment] 2015-07-10 11:38
similar to #2043 (longer descussion in #586, based on Yii1)

**Comment by Naktibalda** [comment] 2016-09-25 19:56
Duplicate of #2275

**Closed by Naktibalda** 2016-09-25 19:56 UTC
Labels: Yii
