### ISSUE TITLE
Cannot filter tests by env

### ISSUE THREAD

**Issue by mightyknite** [Codeception/Codeception#1431] opened 2014-10-01 14:41 UTC
I set env in acceptance.suite.yml and it works perfectly when I call --env=something. But I cannot disable some tests in some selected environment. I set env in test file $scenario->env('something1');  it does not do any effect when I call --env=something or --env=something1 test runs every time.
But $scenario->group('something'); works perfectly when I call --group=something. So I can filter tests by group but not by env.

**Comment by eXorus** [comment] 2020-10-28 12:08
Hello,

I'm closing this issue because I can't reproduce on Codeception 4.1.9
```php

    /**
     * @env prod
     */
    public function onlyExecutedInProd(AcceptanceTester $I)
    {
		//check
    }
    /**
     * @env stage
     */
    public function onlyExecutedInStage(AcceptanceTester $I)
    {
		//check
    }

```

**Closed by eXorus** 2020-10-28 12:08 UTC
Labels: BUG, ENHANCEMENT
