### ISSUE TITLE
PHPUnit 9.3 assertEquals error

### ISSUE THREAD

**Issue by Pi-George** [Codeception/Codeception#5987] opened 2020-09-29 13:06 UTC
Argument 3 passed to PHPUnit\Framework\Assert::assertEquals() must be of the type string, null given, called in /srv/www/vendor/codeception/lib-asserts/src/Codeception/Util/Shared/InheritedAsserts.php on line 243

**Comment by Pi-George** [comment] 2020-09-29 13:27
So it's easy enough to fix by simply providing a message instead of null, however the default value is null so something is wrong for sure here https://imgur.com/RXngQk1

**Comment by Naktibalda** [comment] 2020-09-29 15:28
So the problem is that the default value is null, it should be an empty string.

**Comment by Naktibalda** [comment] 2020-09-29 15:32
It looks like the problem is in this generator:
https://github.com/Codeception/Codeception/blob/4.1.7/src/Codeception/Lib/Generator/Actions.php#L158
it uses null as default value for all optional arguments.

The same issue was fixed in Actor generator 5 years ago:
https://github.com/Codeception/Codeception/commit/60160d88679b296f92b229b9829480aa8c1fab0f

**Closed** 2020-10-23 17:40 UTC
