### ISSUE TITLE
ZF2 functional redirects

### ISSUE THREAD

**Issue by stevewest** [Codeception/Codeception#2964] opened 2016-04-06 14:46 UTC
Currently redirects are not correctly processed in the ZF2 module when running functional tests, a `LogicException` is thrown.

It seems the headers are not being reset for the second request after the redirect, causing a second redirect to occur.

@Naktibalda has been informed about this via IRC and a link to sample code to reproduce the error can be found here: https://github.com/stevewest/codecept_zf2_redirect with full `-vvv` console output in the `readme.md`

**Comment by Naktibalda** [comment] 2016-04-06 21:50
It happens because `Zend\Mvc\Application` uses the same Response object for all responses.
It wasn't designed to serve more than one request.

I see 2 ways to fix it:
a) create a new Application for each request,
b) inject new Request and Response objects before each request.

**Comment by stevewest** [comment] 2016-04-07 06:22
Ideally I think option a would be the best, the only downside I can think of right now is the extra overhead of having to initialise the new application for every request.

B might be a cheaper way of doing the same but I am not sure what that might leave behind from the previous request's state, given I am not all that familiar with ZF2's internals.

**Comment by Naktibalda** [comment] 2016-04-07 20:56
I am pretty sure that creating a new Application for each request would break tests using Doctrine2 module. A proper solution would be to persist a Doctrine service and inject it to a new ServiceManager before the next request (like Symfony2 module is doing).

**Comment by stevewest** [comment] 2016-04-08 07:43
Sounds like creating a new Application and re-injecting the Doctrine service is the way to go then, especially if the concept has already been proven with the Symfony module.

**Comment by stevewest** [comment] 2016-04-14 12:50
Is there any chance in getting this in to 2.2? It's quite a show-stopper when testing.

**Comment by Naktibalda** [comment] 2016-04-14 16:12
If I am doing that, the no, because I have to learn Doctrine to write a few tests first.

**Comment by stevewest** [comment] 2016-04-14 17:55
If you can give me some pointers in where to look in the code I could take a look at this if I can find the time this weekend.

**Comment by bilbercode** [comment] 2016-04-14 23:48
Your test is an Edge to Edge test and as such should always be creating a new instance of the application per test, In practice the application would create a new instance per request (It may be an overhead but thats how ZF2 works), deviating from this behaviour would render your test useless as you are changing how the application behaves during a test as opposed to a real request. 

However if you are simply testing if the controller action is redirecting and you don't want the overhead of a new application instance, do a unit test. Use the example given at http://framework.zend.com/manual/2.0/en/user-guide/unit-testing.html and amend it to suit your purpose (test if it was a redirect and to where) use the ```Zend\Http\Response::isRedirect()``` which internally tests the response code is correct and finally assert something like
```
...
$this->assertEquals('/', $response->getHeaders()->get('Location')->getUri());
...
```
 (no need to call getFieldValue() as internally it calls getUri(), not to be confused with uri() which returns a URI object and not a string ). If you want to go the extra mile you can do what I do and check if the returned url matches the expected Route just in case your Routing config is prone to change over time.

**Comment by stevewest** [comment] 2016-04-15 07:39
@bilbercode Thanks for that but it does not solve the fact that the redirects are not handled correctly.

**Comment by Naktibalda** [comment] 2016-04-17 22:18
I managed to do it, but I am not very happy with my solution.

It is a hybrid of both approaches:
a) new Application is created for each request,
b) but old ServiceManager provides all services to the new Application except Request and Response.

Would anyone like to try to solve it in a better way?

**Comment by stevewest** [comment] 2016-04-18 08:07
I'm honestly not sure how else this could be solved, after taking a quick look at the module code. What is it that you don't like about your solution?

**Comment by Naktibalda** [comment] 2016-04-18 08:18
It could be reusing too many services.

**Comment by stevewest** [comment] 2016-04-18 09:19
If that's the only issue then I'd say that getting the change merged in and testing it out would be the thing to do. It should be fairly simple to remove the reuse of extra services at a later time if needed.

**Comment by Naktibalda** [comment] 2016-04-19 21:40
I reproduced my issue locally
`php codeception/codecept run -c codeception-zf2-tests/` fails with many exceptions of which the most important is 
>   [PDOException]                                                                              
>  SQLSTATE[HY000] [1045] Access denied for user 'username'@'localhost' (using password: YES) 

`cd codeception-zf2-tests && php ../codeception/codecept run` pass,
so it has something to do with current working directory.

**Comment by Naktibalda** [comment] 2016-04-20 21:51
I merged the change to 2.1
@stevewest @dranzd Could you test 2.1-dev against your tests before the next version comes out?

**Comment by stevewest** [comment] 2016-04-21 08:07
@Naktibalda Just checked with my test repo and the sample test is now passing.

**Comment by Naktibalda** [comment] 2016-04-21 10:00
Could you run tests of your real projects?

**Comment by stevewest** [comment] 2016-04-21 11:29
No luck there it seems, output below.

Controller:
```php
    public function logoutAction()
    {
        $this->auth->clearIdentity();
        $this->redirect()->toRoute('home');
    }
```

Test cest is:
```php
    public function testLogOut(FunctionalTester $I)
    {
        $I->wantTo('check that I can log out');
    
        $I->amOnPage('/');
        $I->canSeeInTitle('my project');
        $I->see('Please sign in');
    
        $I->fillField('email', 'my@email.com');
        $I->fillField('password', 'super secret');
    
        $I->click('submit');
    
        $I->seeCurrentUrlEquals('/issue');
    
        $I->amOnPage('/logout');
        $I->canSee('Please sign in');
    }
```

```
Scenario:
* I am on page "/"

  [Page] /
  [Response] 200
  [Request Cookies] []
  [Response Headers] []
* I can see in title "my project"
* I see "Please sign in"
* I fill field "email","my@email.com"
* I fill field "password","super secret"
* I click "submit"
  [Uri] http://localhost/
  [Method] POST
  [Parameters] {"email":"my@email.com","password":"super secret","submit":"Log In"}
  [Page] http://localhost/
  [Response] 302
  [Request Cookies] []
  [Response Headers] {"Location":"issue"}
  [Redirecting to] issue
  [Page] issue
  [Response] 200
  [Request Cookies] []
  [Response Headers] []
* I see current url equals "/issue"
* I am on page "/logout"
  [Page] /logout
  [Response] 200
  [Request Cookies] []
  [Response Headers] []
* I can see "Please sign in"
 FAIL 
```

Seems like the second redirect is not being processed. This all works fine when manually testing via the browser.

**Comment by Naktibalda** [comment] 2016-04-21 21:01
It happens because Redirect plugin keeps the reference to the first response.
I need to figure out how to remove it from ServiceManager.

**Comment by Naktibalda** [comment] 2016-04-23 15:10
It should be good for everything now.

**Comment by stevewest** [comment] 2016-04-23 16:08
I'll be able to confirm on Monday when I have access to the test code again.

**Comment by stevewest** [comment] 2016-04-25 09:58
My tests are now passing, the latest fix seems to have done the job.

**Closed** 2016-04-25 10:35 UTC
Labels: ZF2
