### ISSUE TITLE
IDE error when creating new unit test from 2.2.11 onwards

### ISSUE THREAD

**Issue by carltondickson** [Codeception/Codeception#4261] opened 2017-05-26 09:38 UTC
#### What are you trying to achieve?

Create a new unit test and open the file in PHPStorm, I wouldn't expect to see any errors 

#### What do you get instead?

IDE shows an error - Class must be declared abstract or implement methods 'count', 'run'...

Oddly the test can still run but something seems to have changed between 2.2.10 where everything is OK, 2.2.11 introduces this behavior. Also does the same in the latest stable release (2.3.1?)

### Details

* Codeception version: 2.2.11 problem first occurs, 2.2.10 is OK
* PHP Version: PHP 5.6.30-10+deb.sury.org~trusty+2
* Operating System: PHPStorm running on Windows. VMWare running Ubuntu
* Installation type: Composer

![image](https://cloud.githubusercontent.com/assets/1442885/26489442/4a7f5cc8-41ff-11e7-914a-1852f57a3e86.png)

**Comment by DavertMik** [comment] 2017-05-26 19:56
Created a basic test on Ubuntu and I can't reproduce this.
Looks like PhpStorm can't find and add to index `PHPUnit_Framework_TestCase` file which actually implements `count` and `run`. Please check is it visible to PHPStorm

**Comment by carltondickson** [comment] 2017-05-30 11:21
I believe that this file is visible to PHPStorm even though my vendor folder has been "excluded" in my settings. I tried removing this exclusion but this didn't help.

**Comment by DavertMik** [comment] 2017-05-30 11:23
Does PHPStorm shows you any notice when you look into source of `Codeception\Test\Unit`?

**Comment by carltondickson** [comment] 2017-05-30 12:42
The file **vendor\codeception\codeception\src\Codeception\Test\Unit.php** is absolutely fine (when I exclude the vendors folder) No warnings or errors.

When I remove vendor from the excluded folders I get errors in the Unit class.

_Class must be declared abstract or implement methods 'count', 'run'_

It's probably a little off topic but I'm not 100% sure of the correct way to exclude folders but I tend to add my vendors folder to excluded folders as they aren't editable files but can still be used.

**Comment by carltondickson** [comment] 2017-05-30 13:22
I'll try and recreate in a fresh project

**Comment by carltondickson** [comment] 2017-05-30 13:35
Weirdly I don't get this error when creating a new project, bootstraping and creating a new unit test with "codeception/codeception:2.2.11".

**Comment by nglelinh** [comment] 2017-06-02 09:54
I got the same problem.
Seems that the problem comes from shim.php
`class_alias('PHPUnit\Framework\TestCase', 'PHPUnit_Framework_TestCase');`

**Comment by warkadiusz** [comment] 2017-06-08 11:11
Same here, commenting:
`class_alias('PHPUnit\Framework\TestCase', 'PHPUnit_Framework_TestCase');`
in shim.php helped. But I think it's problem with PHPStorm which doesn't "understand" that this `class_alias` is called only under specific conditions.

**Comment by usulix** [comment] 2017-06-13 01:51
I had the same issue.
I had both phpunit and codeception in my composer.json
removing the phpunit require and composer update... "must be declared abstract" error went away.

**Comment by dereuromark** [comment] 2017-09-26 12:24
Any solution here how to skip? We face the same issue.

**Comment by IvoPereira** [comment] 2017-10-09 10:30
Facing the same problem here.

**Comment by AdrianSkierniewski** [comment] 2017-10-11 17:41
Is there any plans to drop support for old PHPUnit versions? We could simply extend new PHPUnit 6 namespaced classes to avoid this whole issue.

**Comment by dereuromark** [comment] 2017-10-11 17:43
@AdrianSkierniewski We are still using "5.7.22", but until recently there were no issues...

**Comment by AdrianSkierniewski** [comment] 2017-10-11 17:55
In my case, I don't see this exact error but I have a problem with code completion because of shim.php namespace aliases :) 

Change bellow will fix those problems.
```PHP
class Unit extends \PHPUnit_Framework_TestCase
```
to
```PHP
class Unit extends \PHPUnit\Framework\TestCase
```

**Comment by zeeshanbashir** [comment] 2017-12-03 13:23
You can try to extend PHPUnit_Framework_TestCase unless you don't find the solution

**Comment by MaXal** [comment] 2018-02-02 13:01
It's PhpStorm issue and we will fix it on our side. Please vote for https://youtrack.jetbrains.com/issue/WI-40295 to get notified when the fix is available.

**Comment by artspb** [comment] 2018-02-05 15:58
The problem occurs indeed due to the fact that PhpStorm doesn't support conditionally created class aliases. On our side, it's unclear for now how the problem can be addressed in both efficient and performant manner. Meanwhile, you can try to use [a workaround](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/tests/bootstrap.php#L32) found by CodeSniffer guys (see [1671](https://github.com/squizlabs/PHP_CodeSniffer/issues/1671)).

**Comment by AndrewSologor** [comment] 2018-02-08 16:15
Possible workaround (or not?):
 - Right click on file **codeception/codeception/shim.php**
 - Mark as Plain Text

**Comment by delboy1978uk** [comment] 2018-05-30 07:57
Thanks @AndrewSologor, that worked, although for me I had to mark the shim.php that was in the vendor folder of PHPUnit wrapper

**Comment by artspb** [comment] 2018-05-30 08:04
JFYI The problem was fixed in PhpStorm 2018.1, see [WI-40295](https://youtrack.jetbrains.com/issue/WI-40295).

**Comment by delboy1978uk** [comment] 2018-05-30 08:21
@artspb Yes it's fine on my mac back home, but we are in the ridiculous situation in work where they bought us licenses for storm only a month or two ago, but their insanely restrictive network and equipment policy means that we can only install from the 'pre-approved' software list. We're stuck on 2017.2.4! :-P

**Closed** 2019-07-26 09:16 UTC
Labels: Reproduce

**Comment by ODAEL** [comment] 2021-02-09 17:44
I have this issue again in version 2020.3.2
