### ISSUE TITLE
Extend request timeout for WebDriver

### ISSUE THREAD

**Issue by spleshka** [Codeception/Codeception#1984] opened 2015-05-27 16:06 UTC
We have the following acceptance.suite.yml:

    class_name: AcceptanceTester
    modules:
        enabled:
            - WebDriver
            - AcceptanceHelper
        config:
            WebDriver:
                url: 'http://www.example.com'
                host: 'localhost'
                port: 4444
                wait: 0.1
                browser: firefox

The problem is that sometimes our test web page takes more than 30 second to load completely (we have a lot of external js files in header). By default webdriver waits only 30 seconds for response, and then we're getting the following error:

      [WebDriverCurlException]
      Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"unexpectedAlertBehaviour":"accept","browserName":"firefox"}}
      Operation timed out after 30002 milliseconds with 0 bytes received

RemoteWebDriver.php file from facebook allows to override timeouts, but your WebDriveer.php file doesn't implement this feature. Please take a look at the following line: https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Module/WebDriver.php#L130 

If you will provide a webdriver setting to override connection and response timeout it would help us a lot. Thanks!

**Comment by RayRom** [comment] 2015-06-01 15:57
```wait: 0.1``` It that?
Here the expectation interval in seconds (the whole value) is set, you want 2 minutes of expectation that put 120 seconds.
```wait: 120```

**Comment by spleshka** [comment] 2015-06-01 16:02
I wish it was so easy ;) It is another setting not related to request timeout.

**Comment by TroyRudolph** [comment] 2015-06-19 16:15
Hello, I would like to add a comment here.
We  have similar issues. Our initial setup does some things that can take much more than 30 seconds. However, we started having trouble with it after upgrading to Codeception 2.0.14.  Things had worked before were failing with 'Curl error thrown for http POST to /session/90a166d3-3afb-46ae-a3a0-c97106157f88/element/0/click with params: {":id":"0"}'.

Digging into the FB Webdriver code, I found the cause.  About five months ago, The default timeout values were changed from 300,000 millseconds to 30,000 milliseconds..  The developer comments indicated that he was correcting a typo.  Nevertheless, it is an order-of-magnitude change.

If you look at the history of HttpCommandExecutor.php, the diff between commit 58223ee and commit c78f868 show the change.  See liens 137 and 138.

The trouble is, as spleshka points out, is there is no way to override it.

So, for now, I have reverted to 2.0.7 for the entire dev team and the test automation environment.  There is no way to move forward.

Thanks to everyone on the CC team for helping me with the previous issue I opened,

**Comment by zbateson** [comment] 2015-06-19 16:44
Well good news, this should be fixed by #2065 and merged shortly :smiley:

**Comment by spleshka** [comment] 2015-06-19 17:02
Thanks @zbateson, looking forward to see this commited.

**Comment by TroyRudolph** [comment] 2015-06-19 18:22
Do we know when a new codecept.phar file will be published?  What release will it be?  Thank you!

**Comment by zbateson** [comment] 2015-06-19 21:26
It's been merged, many thanks to @n8whnp - I'll leave the release question for @DavertMik

**Comment by TroyRudolph** [comment] 2015-08-05 14:46
Hello!  We have deployed Codeception in our test automation environment with good results.  Thank you for addressing this issue.

**Closed** 2015-08-18 21:25 UTC
Labels: ENHANCEMENT, WebDriver
