### ISSUE TITLE
phpunit issues with symfony5 demo

### ISSUE THREAD

**Issue by tacman** [Codeception/Codeception#5801] opened 2019-12-23 14:29 UTC
Starting with symfony demo:

    symfony new --demo my_project
    composer req codeception/codeception --dev

Not sure how to handle warning message

    Adding phpunit/phpunit as a dependency is discouraged in favor of Symfony's PHPUnit Bridge. 
                                                                                            
  * Instead:
    1. Remove it now: composer remove --dev phpunit/phpunit
    2. Use Symfony's bridge: composer require --dev phpunit

Should we follow those instructions?  They don't seem to do anything.  Running codecept generates:

```
  1x: The "Codeception\PHPUnit\Listener" class implements "PHPUnit\Framework\TestListener" that is deprecated Use the `TestHook` interfaces instead.
    1x in DeprecationErrorHandler::shutdown from Symfony\Bridge\PhpUnit

  1x: The "PHPUnit\TextUI\ResultPrinter" class is considered internal This class is not covered by the backward compatibility promise for PHPUnit. It may change without further notice. You should not use it from "Codeception\PHPUnit\ResultPrinter\UI".
    1x in DeprecationErrorHandler::shutdown from Symfony\Bridge\PhpUnit

  1x: The "PHPUnit\Runner\BaseTestRunner" class is considered internal This class is not covered by the backward compatibility promise for PHPUnit. It may change without further notice. You should not use it from "Codeception\PHPUnit\NonFinal\TestRunner".
    1x in DeprecationErrorHandler::shutdown from Symfony\Bridge\PhpUnit

  1x: The "PHPUnit\Framework\TestSuite" class is considered internal This class is not covered by the backward compatibility promise for PHPUnit. It may change without further notice. You should not use it from "Codeception\Suite".
    1x in DeprecationErrorHandler::shutdown from Symfony\Bridge\PhpUnit
```

**Comment by Naktibalda** [comment] 2019-12-23 15:45
Ignore it, PHPUnit installed by symfony/phpunit-bridge is not usable for Codeception and other tools that extend PHPUnit's functionality.

Duplicate of #4974
There is an open Symfony issue at https://github.com/symfony/symfony/issues/27289

I wouldn't worry about those PHPUnit internal class warnings until PHPUnit 9 or 10 is released.
It is a license for Sebastian Bergmann to break anything in the next major release.

**Closed** 2019-12-23 17:16 UTC

**Comment by hakimdjabri** [comment] 2020-03-13 20:48
thank you

**Comment by rogoit** [comment] 2020-12-06 23:05
my GitLab pipelines fails with this issue. Is there a way to hide it?

**Comment by Naktibalda** [comment] 2020-12-09 07:00
@rogoit you can control it using SYMFONY_DEPRECATIONS_HELPER environment variable,
Set it to `weak` to see deprecation messages, but pass the build, or set it to `disabled` to hinde them completely.

```
SYMFONY_DEPRECATIONS_HELPER=weak
```
