### ISSUE TITLE
Misleading naming scheme for `haveInDatabase`. Suggestion!

### ISSUE THREAD

**Issue by rene-hermenau** [Codeception/Codeception#6114] opened 2021-02-09 16:02 UTC
`haveInDatabase()` is described as 

**Inserts an SQL record into a database. This record will be erased after the test.**

The name `insertInDatabase()` would be much more clearer.
Any chance to refactor that method name and deprecate the old one?

All other names reflect better what the method does like `updateInDatabase()` 

So, what's the reason for that misleading name?

**Comment by Naktibalda** [comment] 2021-02-09 17:06
Duplicate of #4268

**Closed** 2021-02-19 17:00 UTC
