### ISSUE TITLE
Not showing expected / actual correcty on unit tests after upgrade to 2.2.2

### ISSUE THREAD

**Issue by mauriciopiber** [Codeception/Codeception#3334] opened 2016-07-13 10:00 UTC
Hi.

I made a early upgrade to codeception 2.2.2, it's not showing the information of that happened on unit tests.

Use Case:

Output on 2.2.1:

```
[exec] Time: 1.41 seconds, Memory: 31.25MB
[exec] 
[exec] There was 1 failure:
[exec] 
[exec] ---------
[exec] 1) AllColumnsDbRepositoryTest: Select all
[exec]  Test  test/unit/MyModuleTest/RepositoryTest/AllColumnsDbRepositoryTest.php:testSelectAll
[exec] Failed asserting that 32 matches expected 30.
[exec] #1  /var/www/gear-package/my-module/test/unit/MyModuleTest/RepositoryTest/AllColumnsDbRepositoryTest.php:47
[exec] #2  MyModuleTest\RepositoryTest\AllColumnsDbRepositoryTest->testSelectAll
```
After bump version on composer and run composer update, version 2.2.2

```
[exec] Time: 1.2 seconds, Memory: 31.75MB
[exec] 
[exec] There was 1 failure:
[exec] 
[exec] ---------
[exec] 1) AllColumnsDbRepositoryTest: Select all
[exec]  Test  test/unit/MyModuleTest/RepositoryTest/AllColumnsDbRepositoryTest.php:testSelectAll
[exec] - Expected | + Actual
[exec] 
[exec] #1  /var/www/gear-package/my-module/test/unit/MyModuleTest/RepositoryTest/AllColumnsDbRepositoryTest.php:47
[exec] #2  MyModuleTest\RepositoryTest\AllColumnsDbRepositoryTest->testSelectAll
```
Seems to been improved with color, but not information at all, it's a bug or something misconfigured on the early version?

**Comment by Naktibalda** [comment] 2016-07-13 11:47
Duplicate of #3306. I fixed this issue already.

**Closed by Naktibalda** 2016-07-13 11:47 UTC
