### ISSUE TITLE
REST module, params never set

### ISSUE THREAD

**Issue by gmhenderson** [Codeception/Codeception#1682] opened 2015-01-28 23:32 UTC
Am I missing something, or is the public property `$rest->params` never actually set? It always returns an empty array, even when I send URL params with a request. I'll work on a PR.

**Comment by ThePeach** [comment] 2015-01-29 10:47
Could this be a duplicate of #1667 ?

**Comment by gmhenderson** [comment] 2015-01-29 14:50
It's not the same issue. The parameters are being sent to the application, however I am not able to retrieve them after the request is sent because they're never set on the instance of the module.

This works: `$I->sendGET($url, ['id' => 1]);`

But some of my tests require that I read the contents of the params sent with the most recent request. So I should be able to do (in my `FunctionalHelper.php`):

```
$rest = $this->getModule('REST');
echo $rest->params; // ['id' => 1]
```

Right? Currently $rest->params is always an empty array, even when the correct params have been sent to the application.

**Closed** 2015-02-01 01:23 UTC
