### ISSUE TITLE
docker 'latest' tag is not up to date

### ISSUE THREAD

**Issue by webward09** [Codeception/Codeception#5080] opened 2018-07-17 14:15 UTC
#### What are you trying to achieve?
Use the latest docker container, 2.4.4

#### What do you get instead?
codeception/codeception:latest gives me codeception 2.3.9

**Comment by MindTooth** [comment] 2019-11-02 18:11
Belive this still holds true.  Latest is 3.1.2 released 14 days ago, and last image is built two months age.

**Comment by Naktibalda** [comment] 2019-11-02 18:22
Duplicate of #5728

**Closed by Naktibalda** 2019-11-02 18:22 UTC
Labels: BUG
