### ISSUE TITLE
Webdriver clears cookies on every page

### ISSUE THREAD

**Issue by D1ssonance** [Codeception/Codeception#5272] opened 2018-11-19 08:00 UTC
#### What are you trying to achieve?

I'm wrote acceptance test for Magento 1.9 site. It works, but there is some problem.

#### What do you get instead?

Issue is in webdriver working process. Every single page webdriver visit (for example homepage=>product page=>checkout) new session starts. It caused because webdriver clears cookies on every new page. So to finish test I manualy set primary session cookie: 

```php
MyClass::$sessionCookie = $I->grabCookie('frontend'); //writing cookie into my support class
//And then setting on every page manualy
$I->setCookie('frontend', MyClass::$sessionCookie);
```
 It's not right way, I think. Whats wrong with webdriver? How could I fix it? Manualy, in browser, sessions works fine.

### Details
* Selenium-server and webdriver installed from npm;
* Codeception version: 2.5.1
* PHP Version: 5.6
* Operating System: W7
* Installation type: Composer
* Suite configuration:

```yml
actor: AcceptanceTester
modules:
    enabled:
      - WebDriver:
            url: http://myurl.net
            browser: chrome
      - \Helper\Acceptance
```

**Comment by Naktibalda** [comment] 2020-03-02 07:27
Have you figured it out?

I'm closing this ticket, because this isn't a general issue and it must have been caused by some very specific circumstances.

**Closed by Naktibalda** 2020-03-02 07:27 UTC
Labels: WebDriver
