### ISSUE TITLE
Webdriver Timeout Exception

### ISSUE THREAD

**Issue by M1ke** [Codeception/Codeception#5638] opened 2019-08-07 10:43 UTC
#### What are you trying to achieve?

Running a test suite

#### What do you get instead?

```
[Facebook\WebDriver\Exception\TimeOutException]                                                                               
  timeout                                                                                                                       
    (Session info: chrome=64.0.3282.119)                                                                                        
    (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.4.0-157-generic x86_64)
```

> Provide test source code if related

This does not seem to be related to specific tests, just to running a lot of tests (~30mins) in one go

### Details

* Codeception version: 2.5.6
* PHP Version: 7.1
* Operating System: Linux
* Installation type: Composer
* List of installed packages (`composer show`) not relevant
* Suite configuration:

```yml
modules:
    enabled:
        - \Helper\Acceptance
        - WebDriver
        - Db
        - Asserts
        - \Helper\Email
        - \Helper\Populate
        - \Helper\DbTest
        - \Helper\TenancyContractHelper
        - \Helper\Debug
        - \Helper\Unit
    config:
        WebDriver:
            url: 'http://test.local/'
            browser: 'chrome'
            host: 'xxxx_selenium'
            window_size: 1280x960
            capabilities:
                javascriptEnabled: true
                phantomjs.cli.args: ['--ignore-ssl-errors=true']
```

I imagine the timeout might be legitimate but it shouldn't hose the whole test suite - it should probably fail that test and then continue with tests. The issue means that one test failing this way can stop the suite running and prevent any test output from being discovered.

**Comment by Naktibalda** [comment] 2019-08-08 15:50
Please run codeception with `-vvv` parameter and provide a full stack trace.

**Comment by reinholdfuereder** [comment] 2019-09-05 14:06
In my experience it does exactly what you are expecting ("_I imagine the timeout might be legitimate but it shouldn't hose the whole test suite - it should probably fail that test and then continue with tests_")

=> I would opt for closing this issue with something like "Cannot reproduce" (due to the lack of further details)

**Comment by M1ke** [comment] 2019-09-05 14:36
I'll try and get some details. Only problem is the issue happens sporadically and the suite it happens in takes an hour to run (issue doesn't happen ever, as far as I have observed, running a single test).

**Comment by Naktibalda** [comment] 2019-09-05 17:16
This is not an issue of Codeception, after all it isn't Codeception that is throwing this exception.

Then, you are using very old versions of Codeception, Chrome, chromedriver and probably everything else. Unless you are using the latest versions, you are unsupported.

**Comment by Naktibalda** [comment] 2020-02-29 19:40
Closing because no additional information was provided.

**Closed by Naktibalda** 2020-02-29 19:40 UTC
Labels: WebDriver

**Comment by M1ke** [comment] 2020-03-05 12:53
Sorry for the lack of information on this. It was a hard one to catch as it was sporadic and the test run took 1.5 hours.

I concede to the comment above regarding version; I'll update our toolchain to a recent version and open a new issue with debugging info if the issue occurs again.
