### ISSUE TITLE
loadSessionSnapshot() working for Chrome, not working for phantomjs

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#3272] opened 2016-06-24 19:58 UTC
Today I added to my test a new way of testing - phantomjs

Here is my problem:
I have in my test this:

``` php
 public function _before(AcceptanceTester $I)
    {
        $I->automaticLoginAsSuperAdminErp();
    }
```

method is:

``` php
public function automaticLoginAsSuperAdminErp()
    {
        $I = $this;
        if ($I->loadSessionSnapshot('PrihlasenSuperAdminInErp')) return;
        $I->loginAsSuperAdminErp();
        $I->saveSessionSnapshot('PrihlasenSuperAdminInErp');
    }
```

when I run my test as:
codecept run --env DevChrome acceptance smoke --html
it works very well..

but when I run my test as:
codecept run --env DevPhantom acceptance smoke --html
the same test has problem in place, where the session snapshot is loaded.
In html output I see this warning:

```
I load session snapshot "PrihlasenSuperAdminInErp"
{"errorMessage":"Unable to set Cookie","request":{"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"185","Content-Type":"application/json; charset=utf-8","Host":"localhost:10186","User-Agent":"Apache-HttpClient/4.5.1 (Java/1.8.0_91)"},"httpVersion":"1.1","method":"POST","post":"{\"cookie\":{\"path\":\"/\",\"domain\":\"erpdev.changedomain.xx\",\"name\":\"nette-browser\",\"httpOnly\":false,\"hCode\":2027889961,\"secure\":false,\"value\":\"o3lmqr6ilj\",\"class\":\"org.openqa.selenium.Cookie\"}}","url":"/cookie","urlParsed":{"anchor":"","query":"","file":"cookie","directory":"/","path":"/cookie","relative":"/cookie","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/cookie","queryKey":{},"chunks":["cookie"]},"urlOriginal":"/session/b78e55f0-3a42-11e6-b0ae-d18b7c33e7cd/cookie"}}
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'Tatason', ip: '10.0.0.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_91'
Driver info: driver.version: unknown 
```

**Comment by gdscei** [comment] 2016-06-24 22:26
There's an existing open issue for this: #2900

**Comment by bun4uk** [comment] 2017-02-24 15:35
I have a similar issue with Firefox. 
My code 
`public function loggedInIntoFrontend($name, $password)
    {
        $I = $this->driver;
        // if snapshot exists - skipping login
        if ($I->loadSessionSnapshot('login')) {
            return;
        }
        // logging in
        $I->amOnPage(LoginPage::getUrl());
        $I->submitForm(
            LoginPage::$form,
            [
                '_username' => $name,
                '_password' => $password,
            ],
            LoginPage::$btnLogin
        );
        $I->see('Autotest');
        // saving snapshot
        $I->saveSessionSnapshot('login');
    }`

**Comment by bun4uk** [comment] 2017-02-24 15:36
`$I = $this->driver;
        // if snapshot exists - skipping login
        if ($I->loadSessionSnapshot('login')) {
            return;
        }
        // logging in
        $I->amOnPage(LoginPage::getUrl());
        $I->submitForm(
            LoginPage::$form,
            [
                '_username' => $name,
                '_password' => $password,
            ],
            LoginPage::$btnLogin
        );
        $I->see('Autotest');
        // saving snapshot
        $I->saveSessionSnapshot('login');`

**Comment by Naktibalda** [comment] 2017-03-12 20:34
Duplicate of #2900

**Closed by Naktibalda** 2017-03-12 20:34 UTC
Labels: PhantomJS
