### ISSUE TITLE
Test name is different in `startTest` and `endTest` methods if not '$I' variable is used

### ISSUE THREAD

**Issue by SvetlanaZem** [Codeception/Codeception#4123] opened 2017-04-11 15:56 UTC
#### What are you trying to achieve?
1) I created a test with `\AcceptanceTester` parameter named `$tester` instead of `$I`:
```
<?php
class GoogleCest
{
    public function tryVisitGoogle(\AcceptanceTester $tester){
        $tester->wantTo('try going to google');
        $tester->amOnUrl('https://www.google.com');
        $tester->see('Search');
    }
}
```

2) I've implemented custom ResultPrinter and override `startTest` and `endTest` methods.
```
class PhpStorm_Codeception_ReportPrinter extends PHPUnit_TextUI_ResultPrinter
{
    public function startTest(PHPUnit_Framework_Test $test)
    {
        $testName              = \Codeception\Test\Descriptor::getTestAsString($test);
        $this->write("\nSTARTED: $testName\n");
    }

    public function endTest(PHPUnit_Framework_Test $test, $time)
    {
        $testName              = \Codeception\Test\Descriptor::getTestAsString($test);
        $this->write("\nENDED: $testName\n");

    }
}
```
3) I've executed the test with custom result printer.

I expect to see the same test name in `startTest` and `endTest`.
```
STARTED: GoogleCest: Try going to google

ENDED: GoogleCest: Try going to google
```
#### What do you get instead?
```
STARTED: GoogleCest: Try visit google

ENDED: GoogleCest: Try going to google
```
### Details

* Codeception version: 2.2.10
* PHP Version: 7.1.1
* Operating System: Ubuntu
* Installation type: Phar

**Comment by Naktibalda** [comment] 2022-07-31 13:54
`$I` is hardcoded in https://github.com/Codeception/Codeception/blob/cbaa347a683bd5d2f44aefeef57aec31989525ea/src/Codeception/Lib/Parser.php#L33-L38

**Comment by Naktibalda** [comment] 2022-12-29 18:07
Won't fix.

The root cause of this issue is that `wantTo` method is called in the test.

`wantTo` was intended to be used in Cept format and has unexpected effects in other formats.
Cept format is deprecated and it is quite likely that `wantTo` method will be removed in the future version of Codeception, together with Cept format.

**Closed** 2023-01-13 18:28 UTC
