### ISSUE TITLE
Loading and configuring extensions for multiple applications within a single runner

### ISSUE THREAD

**Issue by mrfelton** [Codeception/Codeception#1330] opened 2014-08-20 00:09 UTC
I've made a runner for all my test applications as it is described in the docs using the include statement. I can run tests for all applications. Each application has an extension enabled and configured in it's own codeception.yml file. When I run the tests for these applications individually the extension works as expected. However when I run from the combined test runner the extension is not used.

If I enable and configure the extension from the combined test runner's codeception.yml file then it works. However, each of my applications needs a different configuration for the Extension so configuring it once in the main runner config isn't going to work. Any ideas why the extension wouldn't load from the inner codeception.yml files? Is this supported?

**Comment by AhmedSamy** [comment] 2015-02-19 22:50
I have the same problem, it think we can apply one of two solution:
1. Modify https://github.com/Codeception/Codeception/blob/de94d3cdb9408e22119156ae1ae8608bfcdf318f/src/Codeception/Codecept.php#L75
and make this function dig deep into include paths and merge all extensions and to be loaded at once (draw back you cannot have specific extensions for every application and it wont make sense to load them separately as they will get merged anyway )

2. Add some kind of general _bootstrap.php file that runs on all applications level in order to register custom extension namespaces for instance

**Comment by eXorus** [comment] 2020-10-28 11:48
Hello,

I can't reproduce anymore on Codeception 4.1.9.
The runner  works with the correct configuration of the extensions.

**Closed by eXorus** 2020-10-28 11:48 UTC
Labels: BUG
