### ISSUE TITLE
JUnit no testcases in xml

### ISSUE THREAD

**Issue by gimler** [Codeception/Codeception#5282] opened 2018-11-26 20:54 UTC
#### What are you trying to achieve?

JUnit output of my acceptance suite only gherkin feature files. The file does not contain any testcase entry. It works with unit and functional test.

It seems to be phpunit incompatibility with 7.4.x. With phpunit 7.3.5 it works.
see for changes https://github.com/sebastianbergmann/phpunit/compare/7.3.5...7.4.0 (most files are tests)

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="acceptance" tests="0" assertions="2" errors="0" failures="0" skipped="0" time="0.000000">
    <testcase ...>
    .....
  </testsuite>
</testsuites>
```

#### What do you get instead?

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="acceptance" tests="0" assertions="2" errors="0" failures="0" skipped="0" time="0.000000"/>
</testsuites>
```
### Details

* Codeception version: 2.5.1
* PHPUnit: 7.4.4
* PHP Version: 7.2.12
* Operating System: Linux
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
  enabled:
  - WebDriver:
      host: chrome
      url: 'https://localhost'
      browser: chrome
  - \Helper\Acceptance
```

**Comment by Naktibalda** [comment] 2018-11-29 13:00
@reinholdfuereder We provide 2 phar files - one for PHP 5.6 and another for PHP 7.0+
They have different versions of PhpUnit and Symfony libraries, and possibly some others.

PHP 7.0 build is bundled with PhpUnit 6, because later versions of PhpUnit do not support PHP 7.0.
If you want newer PhpUnit, install Codeception with composer.

Also you looked at the wrong version of composer.json
we use 2 branches: [6.0](https://github.com/Codeception/phpunit-wrapper/blob/6.0/composer.json) and [7.1](https://github.com/Codeception/phpunit-wrapper/blob/7.1/composer.json) to support PhpUnit 5-6 and PhpUnit 7, because they have signifficant differences.

**Comment by Naktibalda** [comment] 2018-11-29 13:02
@gimler as mentioned in https://github.com/Codeception/phpunit-wrapper/issues/46, installing PhpUnit 7.5 downgrades phpunit-wrapper, so some old bugs reappear.

**Comment by Naktibalda** [comment] 2018-11-29 13:50
It looks like a new bug, phpunit-wrapper build failed with this error:
```
Failed asserting that '<?xml version="1.0" encoding="UTF-8"?>\n
<testsuites>\n
  <testsuite name="Jazz.functional" tests="0" assertions="1" errors="0" failures="0" skipped="0" time="0.000000"/>\n
  <testsuite name="Jazz.unit" tests="2" assertions="2" errors="0" failures="0" skipped="0" time="0.004218">\n
    <testcase name="testSimple" class="Jazz\SimpleTest" file="/home/travis/build/Codeception/phpunit-wrapper/vendor/codeception/codeception/tests/data/included/jazz/tests/unit/SimpleTest.php" assertions="1" time="0.003433"/>\n
    <testcase name="testSimpler" class="Jazz\SimpleTest" file="/home/travis/build/Codeception/phpunit-wrapper/vendor/codeception/codeception/tests/data/included/jazz/tests/unit/SimpleTest.php" assertions="1" time="0.000785"/>\n
  </testsuite>\n
  <testsuite name="Jazz\Pianist.functional" tests="0" assertions="1" errors="0" failures="0" skipped="0" time="0.000000"/>\n
  <testsuite name="Shire.functional" tests="0" assertions="1" errors="0" failures="0" skipped="0" time="0.000000"/>\n
</testsuites>\n
' contains "<testsuite name="Jazz.functional" tests="1" assertions="1"".
```

I think that `tests="0"` could be a root cause, for some reason phpunit thinks that there were 0 tests in the testsuite.

**Comment by Naktibalda** [comment] 2018-11-30 10:53
I investigated this issue further and I can confirm that it was caused by this change:
https://github.com/sebastianbergmann/phpunit/commit/be6564ea49b96b9776c53f627a49683ec2687ce5#diff-ba45229ebe0a31a58756c348d0875c62L292

```php
if (!$test instanceof TestCase) {
    return;
}
```
This condition bypasses important parts of `startTest` and `endTest`,
It allowed to replace `if (\method_exists($test, 'hasOutput') && $test->hasOutput()) {` condition with `if ($test->hasOutput()) {`.

We could fix it in 3 ways:
1. Make a pull request to PhpUnit to revert that change (easy to do, probably difficult to get it merged),
2. Make Cept format extend `PHPUnit\Framework\TestCase`. It is a difficult way, only @DavertMik could pull it off, and I am pretty sure that he had good reasons not to extend TestCase in the past.
3. Come up with idea to patch PhpUnit in a way which is more likely to be accepted than a simple reversal.

**Comment by Naktibalda** [comment] 2018-11-30 17:11
All that trouble just to fix `src/Util/Log/JUnit.php:294 PhanUndeclaredMethod Call to undeclared method \PHPUnit\Framework\Test::getName`

**Comment by Naktibalda** [comment] 2018-12-01 08:07
Option 4. Extend JUnit class and restore old behaviour of startTest and endTest methods.

**Comment by Naktibalda** [comment] 2018-12-02 15:19
It was easier to fix than I expected.

@gimler Please `composer update` and check if you get correct reports now.

**Closed by Naktibalda** 2018-12-02 15:19 UTC
