### ISSUE TITLE
XML report not working - PHPUnit change causing break?

### ISSUE THREAD

**Issue by gazrogers** [Codeception/Codeception#6687] opened 2023-08-21 15:52 UTC
#### What are you trying to achieve?

Run tests with an XML report.

#### What do you get instead?

An exception:

```
    PHP Fatal error:  Uncaught Error: Call to private method PHPUnit\Framework\TestCase::hasExpectationOnOutput() from scope Codeception\Reporter\JUnitReporter in /var/www/html/vendor/codeception/codeception/src/Codeception/Reporter/JUnitReporter.php:250
    Stack trace:
    #0 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(220): Codeception\Reporter\JUnitReporter->endTest(Object(Codeception\Event\TestEvent), 'test.end', Object(Symfony\Component\EventDispatcher\EventDispatcher))
    #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'test.end', Object(Codeception\Event\TestEvent))
    #2 /var/www/html/vendor/codeception/codeception/src/Codeception/Test/Test.php(243): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Codeception\Event\TestEvent), 'test.end')
    #3 /var/www/html/vendor/codeception/codeception/src/Codeception/Suite.php(130): Codeception\Test\Test->realRun(Object(Codeception\ResultAggregator))
    #4 /var/www/html/vendor/codeception/codeception/src/Codeception/SuiteManager.php(148): Codeception\Suite->run(Object(Codeception\ResultAggregator))
    #5 /var/www/html/vendor/codeception/codeception/src/Codeception/Codecept.php(260): Codeception\SuiteManager->run(Object(Codeception\ResultAggregator))
    #6 /var/www/html/vendor/codeception/codeception/src/Codeception/Codecept.php(216): Codeception\Codecept->runSuite(Array, 'Functional', NULL)
    #7 /var/www/html/vendor/codeception/codeception/src/Codeception/Command/Run.php(646): Codeception\Codecept->run('Functional')
    #8 /var/www/html/vendor/codeception/codeception/src/Codeception/Command/Run.php(467): Codeception\Command\Run->runSuites(Array, Array)
    #9 /var/www/html/vendor/symfony/console/Command/Command.php(326): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #10 /var/www/html/vendor/symfony/console/Application.php(1063): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #11 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #12 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #13 /var/www/html/vendor/codeception/codeception/src/Codeception/Application.php(112): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #14 /var/www/html/vendor/codeception/codeception/app.php(45): Codeception\Application->run()
    #15 /var/www/html/vendor/codeception/codeception/app.php(46): {closure}()
    #16 /var/www/html/vendor/codeception/codeception/codecept(7): require('/var/www/html/v...')
    #17 /var/www/html/vendor/bin/codecept(119): include('/var/www/html/v...')
    #18 {main}
      thrown in /var/www/html/vendor/codeception/codeception/src/Codeception/Reporter/JUnitReporter.php on line 250

    Fatal error: Uncaught Error: Call to private method PHPUnit\Framework\TestCase::hasExpectationOnOutput() from scope Codeception\Reporter\JUnitReporter in /var/www/html/vendor/codeception/codeception/src/Codeception/Reporter/JUnitReporter.php:250
    Stack trace:
    #0 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(220): Codeception\Reporter\JUnitReporter->endTest(Object(Codeception\Event\TestEvent), 'test.end', Object(Symfony\Component\EventDispatcher\EventDispatcher))
    #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'test.end', Object(Codeception\Event\TestEvent))
    #2 /var/www/html/vendor/codeception/codeception/src/Codeception/Test/Test.php(243): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Codeception\Event\TestEvent), 'test.end')
    #3 /var/www/html/vendor/codeception/codeception/src/Codeception/Suite.php(130): Codeception\Test\Test->realRun(Object(Codeception\ResultAggregator))
    #4 /var/www/html/vendor/codeception/codeception/src/Codeception/SuiteManager.php(148): Codeception\Suite->run(Object(Codeception\ResultAggregator))
    #5 /var/www/html/vendor/codeception/codeception/src/Codeception/Codecept.php(260): Codeception\SuiteManager->run(Object(Codeception\ResultAggregator))
    #6 /var/www/html/vendor/codeception/codeception/src/Codeception/Codecept.php(216): Codeception\Codecept->runSuite(Array, 'Functional', NULL)
    #7 /var/www/html/vendor/codeception/codeception/src/Codeception/Command/Run.php(646): Codeception\Codecept->run('Functional')
    #8 /var/www/html/vendor/codeception/codeception/src/Codeception/Command/Run.php(467): Codeception\Command\Run->runSuites(Array, Array)
    #9 /var/www/html/vendor/symfony/console/Command/Command.php(326): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #10 /var/www/html/vendor/symfony/console/Application.php(1063): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #11 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #12 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #13 /var/www/html/vendor/codeception/codeception/src/Codeception/Application.php(112): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #14 /var/www/html/vendor/codeception/codeception/app.php(45): Codeception\Application->run()
    #15 /var/www/html/vendor/codeception/codeception/app.php(46): {closure}()
    #16 /var/www/html/vendor/codeception/codeception/codecept(7): require('/var/www/html/v...')
    #17 /var/www/html/vendor/bin/codecept(119): include('/var/www/html/v...')
    #18 {main}
      thrown in /var/www/html/vendor/codeception/codeception/src/Codeception/Reporter/JUnitReporter.php on line 250



    FATAL ERROR. TESTS NOT FINISHED.
    Uncaught Error: Call to private method PHPUnit\Framework\TestCase::hasExpectationOnOutput() from scope Codeception\Reporter\JUnitReporter in /var/www/html/vendor/codeception/codeception/src/Codeception/Reporter/JUnitReporter.php:250
    Stack trace:
    #0 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(220): Codeception\Reporter\JUnitReporter->endTest(Object(Codeception\Event\TestEvent), 'test.end', Object(Symfony\Component\EventDispatcher\EventDispatcher))
    #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'test.end', Object(Codeception\Event\TestEvent))
    #2 /var/www/html/vendor/codeception/codeception/src/Codeception/Test/Test.php(243): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Codeception\Event\TestEvent), 'test.end')
    #3 /var/www/html/vendor/codeception/codeception/src/Codeception/Suite.php(130): Codeception\Test\Test->realRun(Object(Codeception\ResultAggregator))
    #4 /var/www/html/vendor/codeception/codeception/src/Codeception/SuiteManager.php(148): Codeception\Suite->run(Object(Codeception\ResultAggregator))
    #5 /var/www/html/vendor/codeception/codeception/src/Codeception/Codecept.php(260): Codeception\SuiteManager->run(Object(Codeception\ResultAggregator))
    #6 /var/www/html/vendor/codeception/codeception/src/Codeception/Codecept.php(216): Codeception\Codecept->runSuite(Array, 'Functional', NULL)
    #7 /var/www/html/vendor/codeception/codeception/src/Codeception/Command/Run.php(646): Codeception\Codecept->run('Functional')
    #8 /var/www/html/vendor/codeception/codeception/src/Codeception/Command/Run.php(467): Codeception\Command\Run->runSuites(Array, Array)
    #9 /var/www/html/vendor/symfony/console/Command/Command.php(326): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #10 /var/www/html/vendor/symfony/console/Application.php(1063): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #11 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #12 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #13 /var/www/html/vendor/codeception/codeception/src/Codeception/Application.php(112): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #14 /var/www/html/vendor/codeception/codeception/app.php(45): Codeception\Application->run()
    #15 /var/www/html/vendor/codeception/codeception/app.php(46): {closure}()
    #16 /var/www/html/vendor/codeception/codeception/codecept(7): require('/var/www/html/v...')
    #17 /var/www/html/vendor/bin/codecept(119): include('/var/www/html/v...')
    #18 {main}
      thrown
    in /var/www/html/vendor/codeception/codeception/src/Codeception/Reporter/JUnitReporter.php:250
```

### Details

* Codeception version: 5.0.10
* PHP Version: 8.2.8
* Operating System: Debian Bullseye
* Installation type: Composer
* List of installed packages (`composer show`)

```
amphp/amp                          v3.0.0         A non-blocking concurrency framework for PHP applications.
amphp/byte-stream                  v2.0.1         A stream abstraction to make working with non-blocking I/O simple.
amphp/cache                        v2.0.0         A fiber-aware cache API based on Amp and Revolt.
amphp/dns                          v2.0.1         Async DNS resolution for Amp.
amphp/hpack                        v3.1.5         HTTP/2 HPack implementation.
amphp/http                         v2.0.0         Basic HTTP primitives which can be shared by servers and clients.
amphp/http-client                  v5.0.0-beta.13 Non-blocking concurrent HTTP/2 and HTTP/1.1 client based on Amp a...
amphp/parser                       v1.1.0         A generator parser to make streaming parsers simple.
amphp/pipeline                     v1.0.0         Asynchronous iterators and operators.
amphp/process                      v2.0.1         A fiber-aware process manager based on Amp and Revolt.
amphp/serialization                v1.0.0         Serialization tools for IPC and data storage in PHP.
amphp/socket                       v2.1.0         Non-blocking socket connection / server implementations based on ...
amphp/sync                         v2.0.0         Non-blocking synchronization primitives for PHP based on Amp and ...
amphp/windows-registry             v1.0.0         Windows Registry Reader.
behat/gherkin                      v4.9.0         Gherkin DSL parser for PHP
codeception/c3                     2.8.1          CodeCoverage collector for Codeception
codeception/codeception            5.0.10         BDD-style testing framework
codeception/lib-asserts            2.1.0          Assertion methods used by Codeception core and Asserts module
codeception/lib-innerbrowser       4.0.0          Parent library for all Codeception framework modules and PhpBrowser
codeception/lib-web                1.0.2          Library containing files used by module-webdriver and lib-innerbr...
codeception/lib-xml                1.0.1          Files used by module-rest and module-soap
codeception/module-asserts         3.0.0          Codeception module containing various assertions
codeception/module-db              3.1.0          DB module for Codeception
codeception/module-phalcon5        v2.0.1         Codeception module for Phalcon 5 framework
codeception/module-phpbrowser      3.0.0          Codeception module for testing web application over HTTP
codeception/module-rest            3.3.2          REST module for Codeception
codeception/stub                   4.1.1          Flexible Stub wrapper for PHPUnit's Mock Builder
daverandom/libdns                  v2.0.3         DNS protocol implementation written in pure PHP
graham-campbell/result-type        v1.1.1         An Implementation Of The Result Type
guzzlehttp/guzzle                  7.7.0          Guzzle is a PHP HTTP client library
guzzlehttp/promises                2.0.1          Guzzle promises library
guzzlehttp/psr7                    2.6.0          PSR-7 message implementation that also provides common utility me...
justinrainbow/json-schema          5.2.12         A library to validate a json schema.
kelunik/certificate                v1.1.3         Access certificate details and transform between different formats.
league/uri                         6.8.0          URI manipulation library
league/uri-components              2.4.2          URI components manipulation library
league/uri-interfaces              2.3.0          Common interface for URI representation
masterminds/html5                  2.8.1          An HTML5 parser and serializer.
myclabs/deep-copy                  1.11.1         Create deep copies (clones) of your objects
nikic/php-parser                   v4.17.1        A PHP parser written in PHP
phar-io/manifest                   2.0.3          Component for reading phar.io manifest information from a PHP Arc...
phar-io/version                    3.2.1          Library for handling version information and constraints
phpoption/phpoption                1.9.1          Option Type for PHP
phpunit/php-code-coverage          10.1.3         Library that provides collection, processing, and rendering funct...
phpunit/php-file-iterator          4.0.2          FilterIterator implementation that filters files based on a list ...
phpunit/php-invoker                4.0.0          Invoke callables with a timeout
phpunit/php-text-template          3.0.0          Simple template engine.
phpunit/php-timer                  6.0.0          Utility class for timing
phpunit/phpunit                    10.3.2         The PHP Unit Testing framework.
psr/container                      2.0.2          Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher               1.0.0          Standard interfaces for event handling.
psr/http-client                    1.0.2          Common interface for HTTP clients
psr/http-factory                   1.0.2          Common interfaces for PSR-7 HTTP message factories
psr/http-message                   1.1            Common interface for HTTP messages
psy/psysh                          v0.11.20       An interactive shell for modern PHP.
ralouphie/getallheaders            3.0.3          A polyfill for getallheaders.
revolt/event-loop                  v1.0.3         Rock-solid event loop for concurrent PHP applications.
sebastian/cli-parser               2.0.0          Library for parsing CLI options
sebastian/code-unit                2.0.0          Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup 3.0.0          Looks up which function or method a line of code belongs to
sebastian/comparator               5.0.1          Provides the functionality to compare PHP values for equality
sebastian/complexity               3.0.0          Library for calculating the complexity of PHP code units
sebastian/diff                     5.0.3          Diff implementation
sebastian/environment              6.0.1          Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 5.0.0          Provides the functionality to export PHP variables for visualization
sebastian/global-state             6.0.1          Snapshotting of global state
sebastian/lines-of-code            2.0.0          Library for counting the lines of code in PHP source code
sebastian/object-enumerator        5.0.0          Traverses array structures and object graphs to enumerate all ref...
sebastian/object-reflector         3.0.0          Allows reflection of object attributes, including inherited and n...
sebastian/recursion-context        5.0.0          Provides functionality to recursively process PHP variables
sebastian/type                     4.0.0          Collection of value objects that represent the types of the PHP t...
sebastian/version                  4.0.1          Library that helps with managing the version number of Git-hosted...
softcreatr/jsonpath                0.8.3          JSONPath implementation for parsing, searching and flattening arrays
symfony/browser-kit                v6.3.2         Simulates the behavior of a web browser, allowing you to make req...
symfony/console                    v6.3.2         Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v6.3.2         Converts CSS selectors to XPath expressions
symfony/deprecation-contracts      v3.3.0         A generic function and convention to trigger deprecation notices
symfony/dom-crawler                v6.3.1         Eases DOM navigation for HTML and XML documents
symfony/event-dispatcher           v6.3.2         Provides tools that allow your application components to communic...
symfony/event-dispatcher-contracts v3.3.0         Generic abstractions related to dispatching event
symfony/finder                     v6.3.3         Finds files and directories via an intuitive fluent interface
symfony/polyfill-ctype             v1.27.0        Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.27.0        Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer   v1.27.0        Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.27.0        Symfony polyfill for the Mbstring extension
symfony/polyfill-php80             v1.27.0        Symfony polyfill backporting some PHP 8.0+ features to lower PHP ...
symfony/service-contracts          v3.3.0         Generic abstractions related to writing services
symfony/string                     v6.3.2         Provides an object-oriented API to strings and deals with bytes, ...
symfony/var-dumper                 v6.3.3         Provides mechanisms for walking through any arbitrary PHP variable
symfony/yaml                       v6.3.3         Loads and dumps YAML files
theseer/tokenizer                  1.2.1          A small library for converting tokenized PHP source code into XML...
vlucas/phpdotenv                   v5.5.0         Loads environment variables from `.env` to `getenv()`, `$_ENV` an...
```

* Suite configuration:
```
actor: FunctionalTester
bootstrap: _bootstrap.php
modules:
    enabled:
        # add a framework module here
        - Phalcon5:
            bootstrap: 'app/config/bootstrap.php'
            cleanup: true
            savepoints: true
        - Tests\Support\Helper\Functional
```

```yml
# paste suite config here
```

I had a look at the recent changes in PHPUnit and there's a commit from the 3rd of August that changes the name of a method from `hasExpectationOnOutput` to `expectsOutput`. You can see the commit at [https://github.com/sebastianbergmann/phpunit/commit/d3d14bf1b1afb9e551588b6ea15f59b0805dd242](https://github.com/sebastianbergmann/phpunit/commit/d3d14bf1b1afb9e551588b6ea15f59b0805dd242).  
It looks like it's tagged 10.3.2 so for now I'm going to change my composer config to require a version before that to try and solve the problem. I just thought I should let you know about the problem.

**Comment by gazrogers** [comment] 2023-08-21 16:01
Additional info: phpunit/phpunit version 10.2.7 works, 10.3.0 does not.

**Comment by Naktibalda** [comment] 2023-08-21 18:52
Duplicate of #6680 
Will be fixed in the next release.

**Closed by Naktibalda** 2023-08-21 18:52 UTC
