### ISSUE TITLE
Unable to use variables in $scenario->skip()

### ISSUE THREAD

**Issue by alexwhitman** [Codeception/Codeception#2006] opened 2015-06-03 09:18 UTC
In 2.x it's not possible to use a variable within the skip message.

``` php
$scenario->skip('skipping because ' . $foo);
```

will dump a notice saying `$foo` is undefined.

``` php
$scenario->skip('skipping because ' . $this->_foo());
```

will fail completely with `Call to undefined method Codeception\Lib\Parser::_foo()`

Including a variable in the skip message does work with 1.8.

**Comment by Naktibalda** [comment] 2015-06-03 16:30
It looks like a trivial issue with your code.

Are you sure that $foo is defined?

**Comment by alexwhitman** [comment] 2015-06-04 05:38
The variables/functions are definitely defined.  It looks like a scope issue.  Notice how the error message indicates that `_foo()` is trying to be called on `Codeception\Lib\Parser` rather than `$this` in the test.  The error comes from https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Lib/Parser.php#L49

**Comment by Naktibalda** [comment] 2015-06-04 08:21
Could you attach your test to the ticket?

**Comment by alexwhitman** [comment] 2015-06-04 08:59
This isn't the actual test but a test case which presents the same issues.
```php
<?php

use \WebGuy;

class ExampleCest
{
	public function _foo()
	{
		return 'defined';
	}

	public function skipTestWithVariable(WebGuy $I, $scenario)
	{
		$foo = 'defined';
		$scenario->skip('Skipping ' . $foo);
	}

	public function skipTestWithFunctionCall(WebGuy $I, $scenario)
	{
		$scenario->skip('Skipping ' . $this->_foo());
	}
}
```
`skipTestWithVariable()` fails with
```
  [PHPUnit_Framework_Exception]  
  Undefined variable: foo
```
`skipTestWithFunctionCall()` fails with
```
PHP Fatal error:  Call to undefined method Codeception\Lib\Parser::_foo() in /home/alex/projects/codecept-test/vendor/codeception/codeception/src/Codeception/Lib/Parser.php(49) : eval()'d code on line 1
PHP Stack trace:
PHP   1. {main}() /home/alex/projects/codecept-test/vendor/codeception/codeception/codecept:0
PHP   2. Symfony\Component\Console\Application->run() /home/alex/projects/codecept-test/vendor/codeception/codeception/codecept:27
PHP   3. Symfony\Component\Console\Application->doRun() /home/alex/projects/codecept-test/vendor/symfony/console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /home/alex/projects/codecept-test/vendor/symfony/console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /home/alex/projects/codecept-test/vendor/symfony/console/Application.php:878
PHP   6. Codeception\Command\Run->execute() /home/alex/projects/codecept-test/vendor/symfony/console/Command/Command.php:259
PHP   7. Codeception\Command\Run->runSuites() /home/alex/projects/codecept-test/vendor/codeception/codeception/src/Codeception/Command/Run.php:192
PHP   8. Codeception\Codecept->run() /home/alex/projects/codecept-test/vendor/codeception/codeception/src/Codeception/Command/Run.php:263
PHP   9. Codeception\Codecept->runSuite() /home/alex/projects/codecept-test/vendor/codeception/codeception/src/Codeception/Codecept.php:158
PHP  10. Codeception\SuiteManager->loadTests() /home/alex/projects/codecept-test/vendor/codeception/codeception/src/Codeception/Codecept.php:174
PHP  11. Codeception\SuiteManager->addToSuite() /home/alex/projects/codecept-test/vendor/codeception/codeception/src/Codeception/SuiteManager.php:99
PHP  12. Codeception\TestCase\Cest->preload() /home/alex/projects/codecept-test/vendor/codeception/codeception/src/Codeception/SuiteManager.php:126
PHP  13. Codeception\Lib\Parser->parseScenarioOptions() /home/alex/projects/codecept-test/vendor/codeception/codeception/src/Codeception/TestCase/Cest.php:39
PHP  14. eval() /home/alex/projects/codecept-test/vendor/codeception/codeception/src/Codeception/Lib/Parser.php:49
```

**Comment by eXorus** [comment] 2021-01-19 11:17
I can't reproduce anymore.
I'm closing this issue, feel free to reopen if it is not resolved.

**Closed by eXorus** 2021-01-19 11:17 UTC
