### ISSUE TITLE
[Error] [] operator not supported for strings

### ISSUE THREAD

**Issue by Agilix** [Codeception/Codeception#4498] opened 2017-09-11 07:35 UTC
#### What are you trying to achieve?
Fill in a form to login a user.

#### What do you get instead?
 I get the error that is in the title `[Error] [] operator not supported for strings` when I add the fillField function.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
35) AclCest: Check if the acl works correctly
 Test  tests/functional/AclCest.php:checkEndpoints

  [Error] [] operator not supported for strings


Scenario Steps:

 8. $I->click("security.login.submit") at tests/functional/AclCest.php:63
 7. $I->fillField("_password","password") at tests/functional/AclCest.php:62
 6. $I->fillField("_username","user@example.com") at tests/functional/AclCest.php:61
 5. $I->amOnRoute("fos_user_security_login") at tests/functional/AclCest.php:60
 4. $I->persistEntity("user@example.com",{"email":"user@example.com","username":"user@example.com"...}) at tests/functional/AclCest.php:40
 3. $I->persistEntity("inno-reviewer@example.com",{"email":"inno-reviewer@example.com","username":...}) at tests/functional/AclCest.php:31

/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:120
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:96
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php:80
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/UsernamePasswordFormAuthenticationListener.php:93
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AbstractAuthenticationListener.php:146
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall.php:69
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:106
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:174
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:43
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:146
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:129
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:168
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Client.php:62
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Lib/Connector/Symfony.php:54
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/BrowserKit/Client.php:315
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php:193
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php:846
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php:422
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php:360
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Step.php:260
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Scenario.php:72
/home/kenneth/vhosts/kenneth/tests/_support/_generated/FunctionalTesterActions.php:375
/home/kenneth/vhosts/kenneth/tests/functional/AclCest.php:63
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Lib/Di.php:127
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Test/Cest.php:136
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Test/Cest.php:145
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Test/Cest.php:82
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Test/Test.php:87
/home/kenneth/vhosts/kenneth/vendor/phpunit/phpunit/src/Framework/TestSuite.php:722
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:106
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/SuiteManager.php:157
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Codecept.php:188
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Codecept.php:157
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Command/Run.php:341
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:841
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:206
/home/kenneth/vhosts/kenneth/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:125
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/src/Codeception/Application.php:103
/home/kenneth/vhosts/kenneth/vendor/codeception/codeception/codecept:36
```
> Provide test source code if related

```php
/**
     * @dataprovider pageProvider
     */
    public function checkEndpoints(FunctionalTester $I, \Codeception\Example $example)
    {
        $I->wantTo("check if the ACL works correctly");
        $I->amOnRoute('fos_user_security_login');
        $I->fillField('_username', 'user@example.com');
        $I->fillField('_password', 'password');
        $I->click('security.login.submit');
        $I->amOnPage('/aef/users');
        $I->canSeeResponseCodeIs(401);
    }
```
### Details

* Codeception version: 2.3.5
* PHP Version: PHP 7.0.18-0ubuntu0.16.10.1 (cli) ( NTS )
* Operating System: Ubuntu
* Installation type:  Composer
* List of installed packages (`composer show`)
api-platform/core                    v2.0.10            The ultimate solution to create web APIs.
api-platform/schema-generator        v1.2.0             Various tools to generate a data model bas...
behat/behat                          v3.3.1             Scenario-oriented BDD framework for PHP 5.3
behat/gherkin                        v4.4.5             Gherkin DSL parser for PHP 5.3
behat/mink                           v1.7.1             Browser controller/emulator abstraction fo...
behat/mink-browserkit-driver         v1.3.2             Symfony2 BrowserKit driver for Mink framework
behat/mink-extension                 v2.2               Mink extension for Behat
behat/mink-goutte-driver             v1.2.1             Goutte driver for Mink framework
behat/mink-selenium2-driver          v1.3.1             Selenium2 (WebDriver) driver for Mink fram...
behat/symfony2-extension             2.1.1              Symfony2 framework extension for Behat
behat/transliterator                 v1.2.0             String transliterator
behatch/contexts                     2.7.1              Behatch contexts
codeception/codeception              2.3.5              BDD-style testing framework
composer/ca-bundle                   1.0.7              Lets you find a path to the system CA bund...
container-interop/container-interop  1.2.0              Promoting the interoperability of containe...
doctrine/annotations                 v1.4.0             Docblock Annotations Parser
doctrine/cache                       v1.6.2             Caching library offering an object-oriente...
doctrine/collections                 v1.4.0             Collections Abstraction library
doctrine/common                      v2.7.3             Common Library for Doctrine projects
doctrine/data-fixtures               v1.2.2             Data Fixtures for all Doctrine Object Mana...
doctrine/dbal                        v2.5.13            Database Abstraction Layer
doctrine/doctrine-bundle             1.6.8              Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.3.0              Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle    2.3.0              Symfony DoctrineFixturesBundle
doctrine/inflector                   v1.2.0             Common String Manipulations with regard to...
doctrine/instantiator                1.0.5              A small, lightweight utility to instantiat...
doctrine/lexer                       v1.0.1             Base library for a lexer that can be used ...
doctrine/orm                         v2.5.10            Object-Relational-Mapper for PHP
dunglas/action-bundle                v0.3.1             Symfony controllers, redesigned
easyrdf/easyrdf                      0.9.1              EasyRdf is a PHP library designed to make ...
eightpoints/guzzle-bundle            v5.3.0             Integrates Guzzle into Symfony2, comes wit...
eightpoints/guzzle-wsse-middleware   v4.2.0             WSSE Middleware for Guzzle, a PHP HTTP cli...
fabpot/goutte                        v3.2.1             A simple PHP Web Scraper
facebook/webdriver                   1.4.1              A PHP client for Selenium WebDriver
friendsofphp/php-cs-fixer            v1.13.2            A tool to automatically fix PHP code style
friendsofsymfony/jsrouting-bundle    1.6.0              A pretty nice way to expose your Symfony2 ...
friendsofsymfony/user-bundle         v2.0.1             Symfony FOSUserBundle
gedmo/doctrine-extensions            v2.4.30            Doctrine2 behavioral extensions
guzzlehttp/guzzle                    6.3.0              Guzzle is a PHP HTTP client library
guzzlehttp/promises                  v1.3.1             Guzzle promises library
guzzlehttp/psr7                      1.4.2              PSR-7 message implementation that also pro...
incenteev/composer-parameter-handler v2.1.2             Composer script handling your ignored para...
instaclick/php-webdriver             1.4.5              PHP WebDriver for Selenium 2
jdorn/sql-formatter                  v1.2.17            a PHP SQL highlighting library
justinrainbow/json-schema            1.6.1              A library to validate a json schema.
league/html-to-markdown              4.4.1              An HTML-to-markdown conversion helper for PHP
leezy/pheanstalk-bundle              3.1.0              The LeezyPheanstalkBundle is a Symfony2 Bu...
monolog/monolog                      1.23.0             Sends your logs to files, sockets, inboxes...
myclabs/deep-copy                    1.6.1              Create deep copies (clones) of your objects
nelmio/cors-bundle                   1.5.3              Adds CORS (Cross-Origin Resource Sharing) ...
paragonie/random_compat              v2.0.10            PHP 5.x polyfill for random_bytes() and ra...
pda/pheanstalk                       v3.1.0             PHP client for beanstalkd queue
phing/phing                          2.16.0             PHing Is Not GNU make; it's a PHP project ...
phpdocumentor/reflection-common      1.0                Common reflection classes used by phpdocum...
phpdocumentor/reflection-docblock    3.1.1              With this component, a library can provide...
phpdocumentor/type-resolver          0.2.1
phpspec/prophecy                     v1.7.2             Highly opinionated mocking framework for P...
phpunit/php-code-coverage            4.0.8              Library that provides collection, processi...
phpunit/php-file-iterator            1.4.2              FilterIterator implementation that filters...
phpunit/php-text-template            1.2.1              Simple template engine.
phpunit/php-timer                    1.0.9              Utility class for timing
phpunit/php-token-stream             2.0.1              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                      5.7.21             The PHP Unit Testing framework.
phpunit/phpunit-mock-objects         3.4.4              Mock Object library for PHPUnit
poken/sdk                            dev-master 3450174 Poken PHP SDK
psr/cache                            1.0.1              Common interface for caching libraries
psr/container                        1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-message                     1.0.1              Common interface for HTTP messages
psr/log                              1.0.2              Common interface for logging libraries
sebastian/code-unit-reverse-lookup   1.0.1              Looks up which function or method a line o...
sebastian/comparator                 1.2.4              Provides the functionality to compare PHP ...
sebastian/diff                       1.4.3              Diff implementation
sebastian/environment                2.0.0              Provides functionality to handle HHVM/PHP ...
sebastian/exporter                   2.0.0              Provides the functionality to export PHP v...
sebastian/global-state               1.1.1              Snapshotting of global state
sebastian/object-enumerator          2.0.1              Traverses array structures and object grap...
sebastian/recursion-context          2.0.0              Provides functionality to recursively proc...
sebastian/resource-operations        1.0.0              Provides a list of PHP built-in functions ...
sebastian/version                    2.0.1              Library that helps with managing the versi...
seld/jsonlint                        1.6.1              JSON Linter
sensio/distribution-bundle           v5.0.21            Base bundle for Symfony Distributions
sensio/framework-extra-bundle        v3.0.27            This bundle provides a way to configure yo...
sensio/generator-bundle              v3.1.6             This bundle generates code for you
sensiolabs/security-checker          v4.1.5             A security checker for your composer.lock
sg/datatablesbundle                  v1.0               Symfony Datatable Bundle For Doctrine2 Ent...
squizlabs/php_codesniffer            2.9.1              PHP_CodeSniffer tokenizes PHP, JavaScript ...
stecman/symfony-console-completion   0.7.0              Automatic BASH completion for Symfony Cons...
stof/doctrine-extensions-bundle      v1.2.2             Integration of the gedmo/doctrine-extensio...
swiftmailer/swiftmailer              v5.4.8             Swiftmailer, free feature-rich PHP mailer
symfony/monolog-bundle               v3.1.0             Symfony MonologBundle
symfony/phpunit-bridge               v3.3.8             Symfony PHPUnit Bridge
symfony/polyfill-intl-icu            v1.5.0             Symfony polyfill for intl's ICU-related da...
symfony/polyfill-mbstring            v1.5.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php56               v1.5.0             Symfony polyfill backporting some PHP 5.6+...
symfony/polyfill-php70               v1.5.0             Symfony polyfill backporting some PHP 7.0+...
symfony/polyfill-util                v1.5.0             Symfony utilities for portability of PHP c...
symfony/swiftmailer-bundle           v2.6.3             Symfony SwiftmailerBundle
symfony/symfony                      v3.2.13            The Symfony PHP framework
twig/twig                            v1.34.4            Twig, the flexible, fast, and secure templ...
webmozart/assert                     1.2.0              Assertions to validate method input/output...
webmozart/json                       1.2.2              A robust JSON decoder/encoder with support...
webmozart/path-util                  2.3.0              A robust cross-platform utility for normal...
willdurand/jsonp-callback-validator  v1.1.0             JSONP callback validator.
willdurand/negotiation               v2.3.1             Content Negotiation tools for PHP provided...

* Suite configuration:

```yml
actor: FunctionalTester
modules:
    enabled:
        - Symfony:
            app_path: 'app'
            var_path: 'var'
            environment: 'test'
        - Doctrine2:
            depends: Symfony
            cleanup: true
        - \test\Helper
```

**Comment by Naktibalda** [comment] 2017-09-11 09:20
It looks like the error is happening in Symfony Security component.

**Comment by Agilix** [comment] 2017-09-11 09:45
@Naktibalda So I should pick it up with the Symfony people?

**Comment by Naktibalda** [comment] 2017-09-11 10:13
Are you able to reproduce this issue manually?

**Comment by DavertMik** [comment] 2017-09-11 20:54
@Agilix yeah, it looks like an edgecase but we don't have Symfony module maintainer to check it. 
If you can reproduce and fix the issue it would be nice.

**Comment by Naktibalda** [comment] 2017-09-12 08:23
Stacktrace above does not show the actual place where the error happens.
I think that this stacktrace issue could be fixed by #4491
@Agilix Could you you test 2.3 branch by setting composer.json to `"codeception/codeception": "2.3.x-dev"`?

**Comment by Naktibalda** [comment] 2017-10-09 09:41
@Agilix have you solved it?
Please upgrade to Codeception 2.3.6 and provide a new stack trace.

**Comment by Agilix** [comment] 2017-10-16 08:15
I have now updated to the latest version and started over. Have not tested this yet as I'm looking for a solution of how to have data inside my tests. Like logging in as a user. Where does it get the user?

**Comment by Naktibalda** [comment] 2017-10-16 08:58
It is totally app specific. There is no login function in Symfony module.

**Closed** 2017-12-26 22:26 UTC
Labels: Symfony
