### ISSUE TITLE
Codeception 2.2.11 stops executing Cepts if a tests results in an error.

### ISSUE THREAD

**Issue by kajstrom** [Codeception/Codeception#4228] opened 2017-05-18 13:18 UTC
Attached are screenshots of the behavior on 2.2.10 and on 2.2.11.

Codeception 2.2.11 will stop executing tests if a tests results in an error. Codeception 2.2.10 and earlier keep executing tests even if one or more tests result in an error.

### Details

* Codeception version: 2.2.11
* PHP Version: 7.1.5
* Operating System: Windows 10
* Installation type: Phar

![codeception_2 2 10](https://cloud.githubusercontent.com/assets/1039316/26203679/d99d98dc-3be4-11e7-80a5-9573e7b84570.PNG)
![codeception2 2 11](https://cloud.githubusercontent.com/assets/1039316/26203680/d9a25cd2-3be4-11e7-98a4-48c11118373d.PNG)

**Comment by Naktibalda** [comment] 2017-05-18 13:25
Thanks,
This is a duplicate of #4223 

It will be fixed in 2.2.12.

**Closed by Naktibalda** 2017-05-18 13:25 UTC

**Comment by kajstrom** [comment] 2017-05-18 13:29
Good to hear, thank you.
