### ISSUE TITLE
seeInPopup and acceptPopup throw Unexpected Alert exceptions on some environments

### ISSUE THREAD

**Issue by Thistler** [Codeception/Codeception#3337] opened 2016-07-14 06:13 UTC
I'm writing a script that deletes something from the user's page and gets a "Are you sure?" type of alert on the page. However, for some reason codeception isn't interacting with the alerts properly. The page is still in development and on an internal test environment. I mention this because when I test against live for one of our other apps, the popup handling works fine. 

Is there a condition where codeception won't detect popups correctly? Is there something I can tell ops to do to make the environment workable? Or is this some kind of unknown issue?

**Comment by dizzy7** [comment] 2016-07-20 12:37
Try turning off the Recorder if it is on

**Comment by stirrell-idexx** [comment] 2016-07-25 16:51
I am also seeing this issue without Recorder turned on. I have:

`$I->acceptPopup();`

But get the following error:

```
[Facebook\WebDriver\Exception\UnexpectedAlertOpenException]
  unexpected alert open: {Alert text : Are you sure you want to delete this?}
    (Session info: chrome=52.0.2743.82)
    (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.6 x86_64) (WARNING:
  The server did not provide any stacktrace information)
  Command duration or timeout: 1 milliseconds: null
```

**Comment by Thistler** [comment] 2016-07-26 18:56
Yeah, that's the error I get too. I could have sworn I posted it but I guess I was more tired and frustrated than I realized when making this thread...

**Comment by stirrell-idexx** [comment] 2016-07-27 12:49
@Thistler - thanks for the workaround. I will look into that.

I have noticed that running locally on the newest Chrome gives me this problem. Running on a slightly older version in Sauce Labs does not have the same problem. I am unsure if it is related to running in Sauce Labs or the difference in Chrome but will try to test.

**Comment by stirrell-idexx** [comment] 2016-08-01 14:19
I tried the workaround above. Unfortunately, it doesn't seem to help in my case. I still get:

`[Facebook\WebDriver\Exception\UnexpectedAlertOpenException]
  unexpected alert open: {Alert text : Are you sure you want to delete this?}`

And the test suite halts execution right there. That is the bigger issue I am facing is that this error is causing all remaining tests to not run.

**Comment by stirrell-idexx** [comment] 2016-08-01 17:06
I did run this test in Sauce Labs against the newest version of Chrome (52) and it works in Sauce Labs. Locally I get the error. I looked to see if there was a new version of the standalone Selenium server and didn't see one. I'm not sure what is causing the issue locally for me.

**Comment by stirrell-idexx** [comment] 2016-08-01 18:39
I believe that the issue in Chrome with this error is fixed with the newest version of Chromedriver. According to their notes:

http://chromedriver.storage.googleapis.com/2.22/notes.txt

So I think my issues were caused by Chrome being updated to version 52 and having 2.21 of Chromedriver. I am sorry that I inadvertently thought it was an issue with Codeception. I do not think this is the case now.

**Closed** 2016-09-28 06:31 UTC
Labels: WebDriver
