### ISSUE TITLE
PHPUnit 10.3 Generator namespace changed.

### ISSUE THREAD

**Issue by martineiber** [Codeception/Codeception#6681] opened 2023-08-04 08:36 UTC
#### What are you trying to achieve?
Use Codeception with PHPUnit 10.3

#### What do you get instead?
`Error : Class "PHPUnit\Framework\MockObject\Generator" not found` 

When using `$this->makeEmpty()`

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Error : Class "PHPUnit\Framework\MockObject\Generator" not found` 
```
> Provide test source code if related

```php
$this->makeEmpty(\stdClass::class, ['foo' => 'bar']);
```
### Details

* Codeception version: 5.0.10
* PHP Version: 8.2
* Operating System: Linux
* Installation type: Composer

**Comment by W0rma** [comment] 2023-08-07 04:22
Duplicate of https://github.com/Codeception/Stub/issues/41

**Closed** 2023-08-16 19:17 UTC
