### ISSUE TITLE
Compatibility with PHPUnit 7, 8, 9...

### ISSUE THREAD

**Issue by michalbundyra** [Codeception/Codeception#5916] opened 2020-05-13 06:10 UTC
#### What are you trying to achieve?

```
Codeception PHP Testing Framework v3.1.2
Powered by PHPUnit 8.5.2 by Sebastian Bergmann and contributors.
Running with seed: 

PHP Fatal error:  Declaration of Codeception\Test\Test::toString() must be compatible with PHPUnit\Framework\SelfDescribing::toString(): string in /project/vendor/codeception/codeception/src/Codeception/Test/Test.php on line 18

Fatal error: Declaration of Codeception\Test\Test::toString() must be compatible with PHPUnit\Framework\SelfDescribing::toString(): string in /projectvendor/codeception/codeception/src/Codeception/Test/Test.php on line 18
```

Since PHPUnit 7.0 we have RTH `:string` declaration here:

https://github.com/sebastianbergmann/phpunit/blob/7.0.0/src/Framework/SelfDescribing.php#L23

In Codeception we do not have RTH on that function and it causes the above issue, see:

https://github.com/Codeception/Codeception/blob/3.1.2/src/Codeception/Test/Test.php#L58
https://github.com/Codeception/Codeception/blob/4.1.4/src/Codeception/Test/Test.php#L58

Please note that `abstract Codeception\Test\Test` implements [`Codeception\Test\Interfaces\Descriptive`](https://github.com/Codeception/Codeception/blob/4.1.4/src/Codeception/Test/Interfaces/Descriptive.php) which extends `\PHPUnit\Framework\SelfDescribing`, so effectively:

`Codeception\Test\Test` implements `PHPUnit\Framework\SelfDescribing` and here we have the mismatch of the declaration.

As noted: issue in Codeception 3 and 4, starting since PHPUnit 7.0.

Related issue:
- https://github.com/php-mock/php-mock-phpunit/issues/46

**Comment by Naktibalda** [comment] 2020-05-13 07:07
Duplicate of #5031

**Closed by Naktibalda** 2020-05-13 07:07 UTC

**Comment by michalbundyra** [comment] 2020-05-13 07:10
@Naktibalda wow, thanks! Two years old issues, even on Codeception 2.x still without resolution...
