### ISSUE TITLE
Yii2 model is lost when doing functional test and the action returns redirect response

### ISSUE THREAD

**Issue by biserantonov** [Codeception/Codeception#3961] opened 2017-01-26 13:28 UTC
Bug is caused by pull request #3834 in v.2.2.8. I'm testing an action which redirects to itself in certain condition. However before the redirect is done the transaction is roll backed and the model that I use for testing is lost.

**Comment by ddinchev** [comment] 2017-01-27 20:20
This caused a lot of frustration. Tests that check that something has happened after a redirect, are being broken.
1. Actor fills form with correct data.
2. Actor submits form.
3. Backend saves the record and immediately redirects to the record view page. Record is deleted because of #3834
4. We check if record is present based on the id recovered from URL, or the submitted test data, and test fails.

**Comment by StalkAlex** [comment] 2017-01-31 14:45
Guys, really? Again? Wasting couple of days to find out why half of functional tests become strangely broken. This isn't fisrt time already though. Bugs during development, ok I understand it, but it's almost impossible to wait another month waiting new release and living with ugly kludges. So fix commit is here, it's working. Please merge it and make another release.

**Comment by samdark** [comment] 2017-01-31 14:51
Which fix do you mean?

**Comment by StalkAlex** [comment] 2017-01-31 14:52
This one https://github.com/iRipVanWinkle/Codeception/commit/994118f7aaece9d4c4fbf8fcad22874610abcf77

**Comment by samdark** [comment] 2017-01-31 14:58
That is basically a rollback of another fix for a valid issue.

**Comment by StalkAlex** [comment] 2017-01-31 15:02
https://github.com/Codeception/Codeception/pull/3834 ? I think this was related too. https://github.com/Codeception/Codeception/issues/3769 . At least previous variant worked properly in "all-green" scenario.

**Comment by samdark** [comment] 2017-01-31 15:06
In your case yes but since that issue was reported, it was preventing someone else tests from working.

**Comment by StalkAlex** [comment] 2017-01-31 15:22
@samdark  ok, sorry. Just as I said not the first time.

**Comment by iRipVanWinkle** [comment] 2017-01-31 17:26
@samdark I can't reproduce this bug #3834. Because my transaction closes of config property `cleanup`, I think the property enough.

And if this bug exists we can move method of closing transaction here: [#L153](https://github.com/iRipVanWinkle/Codeception/blob/2.2/src/Codeception/Lib/Connector/Yii2.php#L151)

```php
            } elseif (!$e instanceof ExitException) {
                // for exceptions not related to Http, we pass them to Codeception
                $this->rollBackTransaction(); // added
                $this->resetApplication();
                throw $e;
            }
```

**Closed** 2017-02-03 22:39 UTC
Labels: Yii
