### ISSUE TITLE
PHP Warning: Cannot declare class PHPUnit_Framework_Assert, because the name is already in use in shim.php on line 17

### ISSUE THREAD

**Issue by krukru** [Codeception/Codeception#4500] opened 2017-09-11 16:09 UTC
#### What are you trying to achieve?
I tried running `codecept --version`

#### What do you get instead?

```bash
I get the following output
PHP Warning:  Cannot declare class PHPUnit_Framework_Assert, because the name is already in use in shim.php on line 17
PHP Stack trace:
PHP   1. {main}() vendor/codeception/codeception/codecept:0
PHP   2. require_once() vendor/codeception/codeception/codecept:7
PHP   3. include_once() vendor/codeception/codeception/autoload.php:45
PHP   4. class_alias() vendor/codeception/codeception/shim.php:17
Codeception 2.3.5
```

I get this warning on any codecept command I run. The commands successfully complete (since this is only a warning), but still it is annoying.
### Details

* Codeception version:  2.3.5
* PHP Version: PHP 7.1.9-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep  2 2017 05:56:43) ( NTS )
* Operating System: Ubuntu 16.04
* Installation type: composer
* List of installed packages:
```
behat/gherkin                      v4.4.5             Gherkin DSL parser for PHP 5.3
codeception/c3                     2.0.12             CodeCoverage collector for Codeception
codeception/codeception            2.3.5              BDD-style testing framework
codeception/mockery-module         0.2.2              Mockery Module for Codeception
codeception/specify                0.4.6              BDD code blocks for PHPUnit and Codeception
codeception/verify                 0.4.0              BDD assertion library for PHPUnit
composer/ca-bundle                 1.0.8              Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
degordian/php-coding-standards     dev-master b0537ad Degordian PHP coding stanards
doctrine/instantiator              1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
facebook/webdriver                 1.4.1              A PHP client for Selenium WebDriver
flow/jsonpath                      0.3.4              JSONPath implementation for parsing, searching and flattening arrays
fzaninotto/faker                   v1.6.0             Faker is a PHP library that generates fake data for you.
guzzlehttp/guzzle                  6.3.0              Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1             Guzzle promises library
guzzlehttp/psr7                    1.4.2              PSR-7 message implementation that also provides common utility methods
hamcrest/hamcrest-php              v1.2.2             This is the PHP port of Hamcrest Matchers
league/factory-muffin              v3.0.1             The goal of this package is to enable the rapid creation of objects for the purpose of testing.
league/factory-muffin-faker        v2.0.0             The goal of this package is to wrap faker to make it super easy to use with factory muffin.
mockery/mockery                    0.9.9              Mockery is a simple yet flexible PHP mock object framework for use in unit testing with PHPUnit, PHPSpec or any other testing framework. Its core...
myclabs/deep-copy                  1.6.1              Create deep copies (clones) of your objects
neronmoon/teamcity-codeception     dev-master b4cc925 Integrating codeception builds with codeception
nikic/php-parser                   v3.1.1             A PHP parser written in PHP
pdepend/pdepend                    2.5.0              Official version of pdepend to be handled with Composer
phar-io/manifest                   1.0.1              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    1.0.1              Library for handling version information and constraints
php-mock/php-mock                  1.0.1              PHP-Mock can mock built-in PHP functions (e.g. time()). PHP-Mock relies on PHP's namespace fallback policy. No further extension is needed.
php-mock/php-mock-integration      1.0.0              Integration package for PHP-Mock
php-mock/php-mock-mockery          1.1.0              Mock built-in PHP functions (e.g. time()) with Mockery. This package relies on PHP's namespace fallback policy. No further extension is needed.
phpdocumentor/reflection-common    1.0                Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.1.1              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver        0.4.0
phploc/phploc                      4.0.0              A tool for quickly measuring the size of a PHP project.
phpmd/phpmd                        2.6.0              PHPMD is a spin-off project of PHP Depend and aims to be a PHP equivalent of the well known Java tool PMD.
phpmetrics/phpmetrics              v2.2.0             Static analyzer tool for PHP : Coupling, Cyclomatic complexity, Maintainability Index, Halstead's metrics... and more !
phpspec/prophecy                   v1.7.2             Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          5.2.2              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          1.4.2              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1              Simple template engine.
phpunit/php-timer                  1.0.9              Utility class for timing
phpunit/php-token-stream           2.0.1              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    6.2.4              The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       4.0.4              Mock Object library for PHPUnit
psr/container                      1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-message                   1.0.1              Common interface for HTTP messages
psr/log                            1.0.2              Common interface for logging libraries
sebastian/code-unit-reverse-lookup 1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator               2.0.0              Provides the functionality to compare PHP values for equality
sebastian/diff                     1.4.3              Diff implementation
sebastian/environment              3.1.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0              Provides the functionality to export PHP variables for visualization
sebastian/finder-facade            1.2.1              FinderFacade is a convenience wrapper for Symfony's Finder component.
sebastian/global-state             2.0.0              Snapshotting of global state
sebastian/object-enumerator        3.0.3              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1              Allows reflection of object attributes, including inherited and non-public ones
sebastian/phpcpd                   3.0.0              Copy/Paste Detector (CPD) for PHP code.
sebastian/recursion-context        3.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0              Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
sensiolabs/security-checker        v4.1.5             A security checker for your composer.lock
squizlabs/php_codesniffer          3.0.2              PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
stecman/symfony-console-completion 0.7.0              Automatic BASH completion for Symfony Console Component based applications.
symfony/browser-kit                v3.3.8             Symfony BrowserKit Component
symfony/config                     v3.3.8             Symfony Config Component
symfony/console                    v3.3.8             Symfony Console Component
symfony/css-selector               v3.3.8             Symfony CssSelector Component
symfony/debug                      v3.3.8             Symfony Debug Component
symfony/dependency-injection       v3.3.8             Symfony DependencyInjection Component
symfony/dom-crawler                v3.3.8             Symfony DomCrawler Component
symfony/event-dispatcher           v3.3.8             Symfony EventDispatcher Component
symfony/filesystem                 v3.3.8             Symfony Filesystem Component
symfony/finder                     v3.3.8             Symfony Finder Component
symfony/polyfill-mbstring          v1.5.0             Symfony polyfill for the Mbstring extension
symfony/process                    v3.3.8             Symfony Process Component
symfony/yaml                       v3.3.8             Symfony Yaml Component
theseer/fdomdocument               1.6.6              The classes contained within this repository extend the standard DOM to use exceptions at all occasions of errors instead of PHP warnings or noti...
theseer/tokenizer                  1.1.0              A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.2.0              Assertions to validate method input/output with nice error messages.
yiisoft/yii2-coding-standards      v3.0               Yii PHP Framework Version 2 - Coding standard tools
```

**Comment by Naktibalda** [comment] 2017-09-11 17:17
Duplicate of #4479

**Closed by Naktibalda** 2017-09-11 17:17 UTC
