### ISSUE TITLE
0% API code coverage

### ISSUE THREAD

**Issue by visiover** [Codeception/Codeception#4691] opened 2017-12-14 16:23 UTC
#### What are you trying to achieve?
I'm trying to get code coverage for my tests.

The Code Coverage Report is showing 0% class tested after adding the REST module to my suites.

I have added the c3.php file to the root of my project and added the configuration to my index.php file
but i'm still getting 0% code coverage. 

* Codeception version: 2.1.4
* PHP Version: 7.1.12
* Operating System: Ubuntu 16.04 LTS
* Installation type: Composer
* List of installed packages : 
    "codeception/codeception": "2.*",
    "codeception/c3": "2.*",
    "mockery/mockery": "^0.9"

* index.php file
```php
<?php

require_once(__DIR__ . '../c3.php');
define('C3_CODECOVERAGE_ERROR_LOG_FILE', '../c3_error.log');
```

* Suite configuration:
```yml
class_name: ApiTester
modules:
    enabled:
        - Asserts
        - Helper\Unit
        - REST:
            url: http://test/
            depends: PhpBrowser
            part: Json
```

* Codeception.yml configuration :
```yml
coverage:
    enabled: true
    remote: true
    c3_url: 'http://test/index.php/'
    whitelist:
      include:
          - src/*
```
Enabling Debug doesn't show anything 

```php
$_SERVER['HTTP_X_CODECEPTION_CODECOVERAGE_DEBUG'] = 1;

/* if (!array_key_exists('HTTP_X_CODECEPTION_CODECOVERAGE', $_SERVER)) {
	return;
} */
```

* xdebug.ini configuration

```yml
zend_extension=xdebug.so
xdebug.var_display_max_depth=50
xdebug.remote_enable=1
xdebug.idekey=PHPSTORM
xdebug.collect_vars=1
```

**Comment by salma-abdelhady** [comment] 2018-01-16 07:36
+1

**Comment by HoraceVelmont** [comment] 2018-03-16 01:12
+1

**Comment by eerison** [comment] 2018-04-27 18:35
+1

**Comment by jonny7** [comment] 2018-06-07 12:32
+1

**Comment by Naktibalda** [comment] 2021-01-06 16:00
Duplicate of #4792

**Closed by Naktibalda** 2021-01-06 16:00 UTC
Labels: Coverage
