### ISSUE TITLE
.env file loaded in wrong order

### ISSUE THREAD

**Issue by Rahe** [Codeception/Codeception#4996] opened 2018-05-28 12:49 UTC
#### What are you trying to achieve?
I have a codeception.dist.yml versionned loading a .env file for the CI, and this is working fine : https://github.com/BeAPI/bea-sanitize-filename/blob/add-unit-tests/codeception.dist.yml

When I'm locally testing I create a codeception.yml file with this content at the end
```yml
params:
   - .env.local
```

I expect that the .env file is loaded then the .env.local wich is override the .env file configuration, but this is not the case.
I'm using wp-browser, I have made debug with var_dump into the dotenv loader from codeception and the files loaded order is 
- .env.local
- .env

```bash
vendor/bin/codecept run acceptance     
/app/vendor/codeception/codeception/src/Codeception/Lib/ParamsLoader.php:82:
string(10) ".env.local"
/app/vendor/codeception/codeception/src/Codeception/Lib/ParamsLoader.php:82:
string(4) ".env"
```
#### What do you get instead?
The .env.local is loaded then the .env file is loaded so the configuration isn't right and the tests doesn't pass.

### Details

* Codeception version:
* PHP Version:2.4.2
* Operating System:Linux
* Installation type: Composer
* List of installed packages (`composer show`)

antecedent/patchwork               2.1.8   Method redefinition (monkey-patc...
bacon/bacon-string-utils           1.1.0   BaconStringUtils contain utitili...
behat/gherkin                      v4.5.1  Gherkin DSL parser for PHP 5.3
codeception/codeception            2.4.2   BDD-style testing framework
codeception/phpunit-wrapper        6.0.9   PHPUnit classes used by Codeception
codeception/stub                   2.0.1   Flexible Stub wrapper for PHPUni...
composer/ca-bundle                 1.1.1   Lets you find a path to the syst...
composer/composer                  1.6.5   Composer helps you declare, mana...
composer/installers                v1.5.0  A multi-framework Composer libra...
composer/semver                    1.4.2   Semver library that offers utili...
composer/spdx-licenses             1.4.0   SPDX licenses list and validatio...
dg/mysql-dump                      v1.4.0  MySQL database dump.
doctrine/inflector                 v1.3.0  Common String Manipulations with...
doctrine/instantiator              1.1.0   A small, lightweight utility to ...
facebook/webdriver                 1.6.0   A PHP client for Selenium WebDriver
gumlet/php-image-resize            1.8.0   PHP class to re-size and scale i...
guzzlehttp/guzzle                  6.3.3   Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1  Guzzle promises library
guzzlehttp/psr7                    1.4.2   PSR-7 message implementation tha...
hautelook/phpass                   0.3.5   Portable PHP password hashing fr...
illuminate/contracts               v5.6.23 The Illuminate Contracts package.
illuminate/support                 v5.6.23 The Illuminate Support package.
justinrainbow/json-schema          5.2.7   A library to validate a json sch...
lucatume/codeception-setup-local   1.0.3   Flexible local setup for Codecep...
lucatume/wp-browser                1.24.4  WordPress extension of the PhpBr...
lucatume/wp-browser-commons        1.2.8.2 Common libraries of the WP-Brows...
mikemclin/laravel-wp-password      2.0.1   Laravel package that checks and ...
mustache/mustache                  v2.12.0 A Mustache implementation in PHP.
myclabs/deep-copy                  1.7.0   Create deep copies (clones) of y...
nb/oxymel                          v0.1.0  A sweet XML builder
nesbot/carbon                      1.29.0  A simple API extension for DateT...
phpdocumentor/reflection-common    1.0.1   Common reflection classes used b...
phpdocumentor/reflection-docblock  4.3.0   With this component, a library c...
phpdocumentor/type-resolver        0.4.0  
phpspec/prophecy                   1.7.6   Highly opinionated mocking frame...
phpunit/php-code-coverage          4.0.8   Library that provides collection...
phpunit/php-file-iterator          1.4.5   FilterIterator implementation th...
phpunit/php-text-template          1.2.1   Simple template engine.
phpunit/php-timer                  1.0.9   Utility class for timing
phpunit/php-token-stream           2.0.2   Wrapper around PHP's tokenizer e...
phpunit/phpunit                    5.7.27  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       3.4.4   Mock Object library for PHPUnit
psr/container                      1.0.0   Common Container Interface (PHP ...
psr/http-message                   1.0.1   Common interface for HTTP messages
psr/log                            1.0.2   Common interface for logging lib...
psr/simple-cache                   1.0.1   Common interfaces for simple cac...
ramsey/array_column                1.1.3   Provides functionality for array...
rmccue/requests                    v1.7.0  A HTTP library written in PHP, f...
sebastian/code-unit-reverse-lookup 1.0.1   Looks up which function or metho...
sebastian/comparator               1.2.4   Provides the functionality to co...
sebastian/diff                     1.4.3   Diff implementation
sebastian/environment              2.0.0   Provides functionality to handle...
sebastian/exporter                 2.0.0   Provides the functionality to ex...
sebastian/global-state             1.1.1   Snapshotting of global state
sebastian/object-enumerator        2.0.1   Traverses array structures and o...
sebastian/recursion-context        2.0.0   Provides functionality to recurs...
sebastian/resource-operations      1.0.0   Provides a list of PHP built-in ...
sebastian/version                  2.0.1   Library that helps with managing...
seld/cli-prompt                    1.0.3   Allows you to prompt for user in...
seld/jsonlint                      1.7.1   JSON Linter
seld/phar-utils                    1.0.1   PHAR file format utilities, for ...
symfony/browser-kit                v4.0.11 Symfony BrowserKit Component
symfony/config                     v3.4.11 Symfony Config Component
symfony/console                    v3.4.11 Symfony Console Component
symfony/css-selector               v4.0.11 Symfony CssSelector Component
symfony/debug                      v3.4.11 Symfony Debug Component
symfony/dependency-injection       v3.4.11 Symfony DependencyInjection Comp...
symfony/dom-crawler                v4.0.11 Symfony DomCrawler Component
symfony/event-dispatcher           v3.4.11 Symfony EventDispatcher Component
symfony/filesystem                 v2.8.41 Symfony Filesystem Component
symfony/finder                     v3.4.11 Symfony Finder Component
symfony/polyfill-ctype             v1.8.0  Symfony polyfill for ctype funct...
symfony/polyfill-mbstring          v1.8.0  Symfony polyfill for the Mbstrin...
symfony/process                    v3.4.11 Symfony Process Component
symfony/translation                v3.4.11 Symfony Translation Component
symfony/yaml                       v3.4.11 Symfony Yaml Component
vlucas/phpdotenv                   v2.4.0  Loads environment variables from...
webmozart/assert                   1.3.0   Assertions to validate method in...
wp-cli/autoload-splitter           v0.1.5  Composer plugin for splitting a ...
wp-cli/cache-command               v1.0.6  Manages object and transient cac...
wp-cli/checksum-command            v1.0.9  Verifies file integrity by compa...
wp-cli/config-command              v1.2.0  Generates and reads the wp-confi...
wp-cli/core-command                v1.0.9  Downloads, installs, updates, an...
wp-cli/cron-command                v1.0.5  Tests, runs, and deletes WP-Cron...
wp-cli/db-command                  v1.3.3  Performs basic database operatio...
wp-cli/embed-command               v1.0.0  Inspects oEmbed providers, clear...
wp-cli/entity-command              v1.2.0  Manage WordPress core entities.
wp-cli/eval-command                v1.0.5  Executes arbitrary PHP code or f...
wp-cli/export-command              v1.0.6  Exports WordPress content to a W...
wp-cli/extension-command           v1.1.10 Manages plugins and themes, incl...
wp-cli/import-command              v1.0.6  Imports content from a given WXR...
wp-cli/language-command            v1.0.6  Installs, activates, and manages...
wp-cli/media-command               v1.1.4  Imports files as attachments, re...
wp-cli/mustangostang-spyc          0.6.3   A simple YAML loader/dumper clas...
wp-cli/package-command             v1.0.14 Lists, installs, and removes WP-...
wp-cli/php-cli-tools               v0.11.9 Console utilities for PHP
wp-cli/rewrite-command             v1.0.5  Lists or flushes the site's rewr...
wp-cli/role-command                v1.1.0  Adds, removes, lists, and resets...
wp-cli/scaffold-command            v1.1.3  Generates code for post types, t...
wp-cli/search-replace-command      v1.3.0  Searches/replaces strings in the...
wp-cli/server-command              v1.0.9  Launches PHP's built-in web serv...
wp-cli/shell-command               v1.0.5  Opens an interactive PHP console...
wp-cli/super-admin-command         v1.0.6  Lists, adds, or removes super ad...
wp-cli/widget-command              v1.0.5  Adds, moves, and removes widgets...
wp-cli/wp-cli                      v1.5.1  The command line interface for W...
wp-cli/wp-config-transformer       v1.2.1  Programmatically edit a wp-confi...
xamin/handlebars.php               v0.10.4 Handlebars processor for php

* Suite configuration:
```yml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests that require WordPress functions and classes.
actor: WpunitTester
modules:
    enabled:
        - WPLoader
        - \Helper\Wpunit
    config:
        WPLoader:
            wpRootFolder: "%WP_ROOT_FOLDER%"
            dbName: "%DB_NAME%"
            dbHost: "%DB_HOST%"
            dbUser: "%DB_USER%"
            dbPassword: "%DB_PASSWORD%"
            tablePrefix: "%TABLE_PREFIX%"
            domain: "%WP_DOMAIN%"
            adminEmail: "%ADMIN_EMAIL%"
            title: "Test"
            plugins: ['bea-sanitize-filename/bea-sanitize-filename.php']
            activatePlugins: ['bea-sanitize-filename/bea-sanitize-filename.php']
```

**Comment by reinholdfuereder** [comment] 2019-03-15 07:45
This matches my experience/workaround (?) for CI/CD where I am overriding default values from the committed "codeception.yml" file with (dynamic) ones needed for CI/CD via env variables; (and I have just a single "codeception.yml" file):
```
params: # Environment vars override hard-coded default parameters from YAML file
    - test/codeception/parameters.yml
    - env
```

Not sure if that is of any help to you, or actually just confirms your statement ;-)

**Comment by gboubaker** [comment] 2019-06-20 17:35
This issue is still unresolved until version 3.0, the order is completely inversed comparing to the expected behaviour like described here [https://codeception.com/docs/reference/Configuration.html](https://codeception.com/docs/reference/Configuration.html) in "Config Templates (dist)" section.

What we got right now is that params are loaded in this order:
1. personal and uncommitted `codeception.yaml`
2. dist file `codeception.dist.yaml`
3. default config

I debugged configuration loading before running test suites and it seems like the error is coming from this line: [https://github.com/Codeception/Codeception/blob/3.0/src/Codeception/Configuration.php#L655](https://github.com/Codeception/Codeception/blob/3.0/src/Codeception/Configuration.php#L655)

We should inverse arguments to be like this `return array_merge_recursive($a1, $a2);`

**Comment by eXorus** [comment] 2021-01-20 12:49
Old issues, I'm closing it.

**Closed by eXorus** 2021-01-20 12:49 UTC

**Comment by scanacs-awuttig** [comment] 2021-11-10 07:39
The issue might be unresolved? Why it was closed?

**Comment by eXorus** [comment] 2021-11-10 13:55
Might unresolved or unresolved?

It has been closed because it's an old issue on the Codeception version 2.x or 3.x and we don't support it.
