### ISSUE TITLE
Empty environment in Scenario object in Cests

### ISSUE THREAD

**Issue by kirilltitov** [Codeception/Codeception#2225] opened 2015-07-29 08:58 UTC
So I made a slight refactoring, moving a couple of tests from ce**p**t to ce**s**t format. All my tests depend in runtime (welp, yes) on current environment (using --env production etc. in CLI), so it is quite obvious that I'd like to keep that behavior. In ce**p**ts everything worked like a charm — either `$this->env` or `$scenario->getEnv()` or `$scenario->current('env')`. But when it comes to ce**s**ts, env property in scenario (which is passed as second argument to all test methods in ce**s**ts) IS EMPTY every time.

**Comment by DavertMik** [comment] 2015-07-29 23:56
You can get `$scenario` variable by setting `\Codeception\Scenario $scenario` as second argument for your test:

```
<?php
function testSmth(SomeTester $I, \Codeception\Scenario $scenario) 
{
}
```

**Comment by kirilltitov** [comment] 2015-07-30 06:02
Yes! And `env` in this `$scenario` is empty!

**Comment by micaweb** [comment] 2015-07-30 20:43
What version are you using? I'm able to retrieve `$scenario->current('env')` in Cests.

**Comment by kirilltitov** [comment] 2015-07-31 12:33
Oh. For reason UNKNOWN it works now. I don't know why it did not before. I really don't. But what makes me sad — is when I don't provide an `--env` before running tests and $scenario->current('env') throws an exception, while in cepts `$this->env` just was empty (or something, don't quite remember).

**Comment by AlexLomm** [comment] 2015-12-22 14:08
Hello, is there a way to get `$scenario->current('env')` working when not providing `--env`?

**Comment by eXorus** [comment] 2021-01-19 11:21
I can't reproduce anymore.

$scenario->current('env') => Return NULL when it's not set.

I'm closing this issue, feel free to reopen if it is not resolved.

**Closed by eXorus** 2021-01-19 11:21 UTC
