### ISSUE TITLE
Multi-session testing producing a non-zero exit code of 255

### ISSUE THREAD

**Issue by grantlucas** [Codeception/Codeception#1278] opened 2014-08-07 14:54 UTC
I've recently come across an issue where multi-session tests are returning a non-zero exit code, even when nothing is done. The included tests run and pass properly, but an exit code of `255` is being returned. Below is all the information I've managed to find.
## Setup information

I'm using:
- PHP's built in server
- PhantomJS
## Reproducing the error

Example test that produces the `255` exit code

``` php
<?php
// Filename: SessionTestCept.php

$I = new AcceptanceTester($scenario);
$I->wantTo('test multi-sessionn exit codes');

$friend = $I->haveFriend('friend');
$friend->does(function(AcceptanceTester $I) {
  codecept_debug('HI');
});
```

Run the test with the following to display the exit code

```
php codecept run --debug acceptance SessionTestCept.php; echo $?
```

This should output `255` after the test is complete where `0` is the desired value.
## Potential source of error

Using `die;` statements I managed to find the line that's causing the issue but I'm not sure _why_ it's occurring yet hence this bug report.

[Line 36](https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Lib/Friend.php#L36) of the `Friend` class seems to be causing the error. Putting `die;` statements before that at any point produces a `0` exit code and that line is the first one that produces a `255` exit code.

**This produces a proper `0` exit code:**

``` php
foreach ($this->multiSessionModules as $module) {
    $name = $module->_getName();
    $currentUserData[$name] = $module->_backupSessionData();
    if (empty($this->data)) {
        $module->_initializeSession();
        die;
        $this->data[$name] = $module->_backupSessionData();
        continue;
    }
    $module->_loadSessionData($this->data[$name]);
};
```

**This produces the `255` exit code:**

``` php
foreach ($this->multiSessionModules as $module) {
    $name = $module->_getName();
    $currentUserData[$name] = $module->_backupSessionData();
    if (empty($this->data)) {
        $module->_initializeSession();
        $this->data[$name] = $module->_backupSessionData();
        die;
        continue;
    }
    $module->_loadSessionData($this->data[$name]);
};
```

---

Since `$module->_backupSessionData()` is only returning `$this->webDriver`, I'm not really sure what could be causing this error.

If you need any more information or have questions, please let me know.

Thank you for any help on this matter.

**Comment by davidjeddy** [comment] 2015-12-05 14:50
Running the unit tests of the Humhub application (https://github.com/humhub/humhub) results in a non-zero return even though the tests pass.

Command used:
```
codecept build -c ./protected/humhub/tests/ && codecept run unit -c ./protected/humhub/tests/ --steps --debug
```

**Comment by eXorus** [comment] 2020-10-28 08:44
Hello,

I can't reproduce with the last version of Codeception so I'm closing this issue.
<img width="831" alt="Capture d’écran 2020-10-28 à 09 43 25" src="https://user-images.githubusercontent.com/1255561/97412591-0afe5080-1902-11eb-866d-72051b25f4de.png">

**Closed by eXorus** 2020-10-28 08:44 UTC
Labels: BUG, Reproduce

**Comment by kluevandrew** [comment] 2020-11-19 14:25
I've got the same behavour when i add register_shutdown_function and multiple pcntl_signal to my code, they was called multiple times duing tests of console commands in yii2 and it's producess 255 exit code, it's not an issue of codeception, just remeber about it
