### ISSUE TITLE
[Laravel5.3] Functional test - seeInSession() not working after redirect

### ISSUE THREAD

**Issue by zepco** [Codeception/Codeception#3567] opened 2016-09-30 19:53 UTC
#### What are you trying to achieve?

I have register form secured by token in url.
If token is invalid or empty, middleware redirect user to home with error message.

``` php
    public function __construct(RegisterTokenRepositoryInterface $registerTokenRepository)
    {
        parent::__construct();
        $this->middleware('guest');

        $this->middleware(function($request, $next) use ($registerTokenRepository) {
            $token = $request->route()->getParameter('token');

            if ( ! $registerTokenRepository->exists($token))
            {
                 return redirect('/')->with('message', 'Nieprawidłowy token! Rejestracja nie jest możliwa!');
            }

            return $next($request);
        });
    }
```
#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

``` bash
RegisterCest: See redirected page with error message on invalid token
Signature: RegisterCest:secureRegisterFormWithToken
Test: tests/functional/RegisterCest.php:secureRegisterFormWithToken
Scenario --
 I have record "register_tokens",{"email":"test@test.pl","token":"Ramsey\\Uuid\\Uuid","created_at":"DateTime","updated_at":"DateTime"}
 I am on page "register/fake-token"
  [Request Headers] []
  [Page] register/fake-token
  [Response] 302
  [Request Cookies] []
  [Response Headers] {"cache-control":["no-cache"],"location":["http://xyz.pl"],"content-type":["text/html; charset=UTF-8"],"Set-Cookie":[{},{}]}
  [Redirecting to] http://xyz.pl
  [Page] http://xyz.pl
  [Response] 200
  [Request Cookies] {"XSRF-TOKEN":"eyJpdiI6InMyc2xaT1RXUDNBVStDMUlvU2h3cHc9PSIsInZhbHVlIjoicmNxYTJJNnRpUkUzWGxLN092Q3E5bDZxakRCYzBGN3lCZWhJUGd2dE9wMmxqVjlUeHFhRlZpN3JNRkNXRFlrTWptN3JmZWVJMWFYelMwUkhZWlRSRGc9PSIsIm1hYyI6IjBjYTJlYTNkMWQ2NTlhZGUwODA3NTQ4MTFlNDRjMTNhMGRmOWE5OGIxN2U3M2YxZTExZmZiOGZlYTQyMmUzN2IifQ==","laravel_session":"eyJpdiI6IlFOd1pPK3VybHZudGtHY2RxUTFENkE9PSIsInZhbHVlIjoiU1VsVENEckJOYTRUbVlDT1pSNzRCaTdxS1JRK2NlMTFJWGVRdXhOM0dGS29FN2lZYnpLc3RocmxaSk5WUGpPOHZ6NzRvbHJzNlhCbTVtVjRhcUhNR2c9PSIsIm1hYyI6IjM2Zjk3YWU3NGNmOTcxYjY3MDc5NTFhZTA2YmUwZjA1MTRkYTYyYWVlY2NhNzNjY2ZhZjg0YTNkZDFmZmE4NjMifQ=="}
  [Response Headers] {"cache-control":["no-cache"],"content-type":["text/html; charset=UTF-8"],"Set-Cookie":[{},{}]}
 I see current url equals "/"
 I see in session "message"
 FAIL 

```

> Provide test source code if related

``` php
<?php

use Ramsey\Uuid\Uuid;

class RegisterCest
{
    private $userAttributes;
    private $registerToken;

    public function _before(FunctionalTester $I)
    {
        $this->userAttributes = [
            'name' => 'Tester',
            'email' =>  'test@test.pl',
            'password' => Hash::make('test_password'),
        ];

        $this->registerToken = Uuid::uuid4();

        $I->haveRecord('register_tokens', [
            'email' =>  $this->userAttributes['email'],
            'token' => $this->registerToken,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
    }

    public function secureRegisterFormWithToken(FunctionalTester $I)
    {
        // Sprawedzenie działanie tokenu
        $I->wantTo('See redirected page with error message on invalid token');
        $I->amOnPage('register/fake-token');
        $I->seeCurrentUrlEquals('/');
// $I->seeInSession('message', 'Nieprawidłowy token! Rejestracja nie jest możliwa!');
        $I->seeInSession('message'); // <- here is something wrong :/
    }
}
```
### Details
- Codeception version: 2.2.4
- PHP Version: 7.0
- Operating System: Mint Linux
- Installation type: Phar
- List of installed packages (`composer show`)

```
barryvdh/laravel-debugbar             V2.2.3  PHP Debugbar integration for Laravel
caffeinated/bonsai                    v3.0    Asset management package for the Laravel 5 framework.
caffeinated/modules                   v4.0.2  Laravel 5 Modules
classpreloader/classpreloader         3.0.0   Helps class loading performance by generating a single PHP file containing all of the autoloaded files for a specific use case
dnoegel/php-xdg-base-dir              0.1     implementation of xdg base directory specification for php
doctrine/inflector                    v1.1.0  Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.0.5   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
fzaninotto/faker                      v1.6.0  Faker is a PHP library that generates fake data for you.
hamcrest/hamcrest-php                 v1.2.2  This is the PHP port of Hamcrest Matchers
jakub-onderka/php-console-color       0.1     
jakub-onderka/php-console-highlighter v0.3.2  
jeremeamia/SuperClosure               2.2.0   Serialize Closure objects, including their context and binding
laravel/framework                     v5.3.9  The Laravel Framework.
league/flysystem                      1.0.27  Filesystem abstraction: Many filesystems, one API.
maximebf/debugbar                     v1.12.0 Debug bar in the browser for php application
mockery/mockery                       0.9.5   Mockery is a simple yet flexible PHP mock object framework for use in unit testing with PHPUnit, PHPSpec or any other testing framework. Its core goal is to offer a test double framework ...
monolog/monolog                       1.21.0  Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/cron-expression             v1.1.0  CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
myclabs/deep-copy                     1.5.4   Create deep copies (clones) of your objects
nesbot/carbon                         1.21.0  A simple API extension for DateTime.
nikic/php-parser                      v2.1.1  A PHP parser written in PHP
paragonie/random_compat               v2.0.2  PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phpdocumentor/reflection-common       1.0     Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     3.1.0   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver           0.2     
phpspec/prophecy                      v1.6.1  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             4.0.1   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator             1.4.1   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1   Simple template engine.
phpunit/php-timer                     1.0.8   Utility class for timing
phpunit/php-token-stream              1.4.8   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       5.5.4   The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          3.2.7   Mock Object library for PHPUnit
prettus/l5-repository                 2.6.6   Laravel 5 - Repositories to  the database layer
prettus/laravel-validation            1.1.4   Laravel Validation Service
psr/log                               1.0.1   Common interface for logging libraries
psy/psysh                             v0.7.2  An interactive shell for modern PHP.
ramsey/uuid                           3.5.0   Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique identifiers (UUID).
sebastian/code-unit-reverse-lookup    1.0.0   Looks up which function or method a line of code belongs to
sebastian/comparator                  1.2.0   Provides the functionality to compare PHP values for equality
sebastian/diff                        1.4.1   Diff implementation
sebastian/environment                 1.3.8   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    1.2.2   Provides the functionality to export PHP variables for visualization
sebastian/global-state                1.1.1   Snapshotting of global state
sebastian/object-enumerator           1.0.0   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context           1.0.2   Provides functionality to recursively process PHP variables
sebastian/resource-operations         1.0.0   Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.0   Library that helps with managing the version number of Git-hosted PHP projects
sofa/eloquence                        v5.3.2  Flexible Searchable, Mappable, Metable, Validation and more extensions for Laravel Eloquent ORM.
sofa/hookable                         V5.3.1  Laravel Eloquent hooks system.
swiftmailer/swiftmailer               v5.4.3  Swiftmailer, free feature-rich PHP mailer
symfony/console                       v3.1.4  Symfony Console Component
symfony/css-selector                  v3.1.4  Symfony CssSelector Component
symfony/debug                         v3.1.4  Symfony Debug Component
symfony/dom-crawler                   v3.1.4  Symfony DomCrawler Component
symfony/event-dispatcher              v3.1.4  Symfony EventDispatcher Component
symfony/finder                        v3.1.4  Symfony Finder Component
symfony/http-foundation               v3.1.4  Symfony HttpFoundation Component
symfony/http-kernel                   v3.1.4  Symfony HttpKernel Component
symfony/polyfill-mbstring             v1.2.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                v1.2.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-util                 v1.2.0  Symfony utilities for portability of PHP codes
symfony/process                       v3.1.4  Symfony Process Component
symfony/routing                       v3.1.4  Symfony Routing Component
symfony/translation                   v3.1.4  Symfony Translation Component
symfony/var-dumper                    v3.1.4  Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v3.1.4  Symfony Yaml Component
vlucas/phpdotenv                      v2.4.0  Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                      1.1.0   Assertions to validate method input/output with nice error messages.
```
- Suite configuration:

``` yml
class_name: FunctionalTester
modules:
    enabled:
        - Laravel5
        - \Helper\Functional
```

**Comment by janhenkgerritsen** [comment] 2016-10-21 10:44
I reproduced your issue in the sample application. The cause of this issue is that the `\Illuminate\Session\Middleware\StartSession` middleware calls the `save` method on the session after a request, where flash data is aged in [this line](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Session/Store.php#L260). 

Because the `redirect()->with()` call in your middleware uses this flash functionality, the flashed message is cleared from the session after the request for the redirect finishes. This is why the Laravel 5 module does not see this flashed message in the session, because it inspects the session after the request is finished.

To solve this problem the Laravel 5 module needs to store this flash session data before it is aged. I'll need to think a bit about other consequences of this before I implement a fix for this issue.

**Comment by ForwardGuy** [comment] 2017-03-05 19:33
Any new information about this bug? 
Because of this bug I cannot test administration forms (which are behind authentication middleware). Everytime I send form, authentication get reset. Is there any workaround for this?

**Comment by janhenkgerritsen** [comment] 2017-03-06 10:18
I haven't looked into this issue any further yet. But from what I can remember this issue only affects flash session data, it should not affect authentication since that is not flashed session data. Or am I missing something?

**Comment by ForwardGuy** [comment] 2017-03-06 11:02
Oh, maybe it is related to some new bug. I have created new repo with clean installation of Laravel and Codeception which is describing my problem:
https://github.com/ForwardGuy/larave-codeception-functional-authentication-test

It uses default Laravel authentication scaffolding. And there is one functional test created (SomeAuthenticationCest) - which is trying to test sending form behind auth middleware. It seems like after sending form sessions got reset and it will got redirected to login page instead of displaying inputs value.

**Comment by janhenkgerritsen** [comment] 2017-03-06 16:05
In your `amLoggedAsAdministrator` method you have to persist the user to the database. If you for example change the code to create the user to the following the test succeeds:

```
$user = User::firstOrCreate(['name' => 'Tester', 'email' => 'tester@site.com', 'password' => bcrypt(123456)]);
```

**Comment by ForwardGuy** [comment] 2017-03-07 10:05
Thank you so much, that was rly stupid mistake from me. Of course after persisting the user everything works as expected. Once again, thanks for your help.

**Comment by janhenkgerritsen** [comment] 2017-03-07 11:19
Glad I could help :)

**Closed by janhenkgerritsen** 2017-03-07 11:19 UTC
Labels: BUG, Laravel5
