### ISSUE TITLE
Debugging Command for Skipping depends annotations

### ISSUE THREAD

**Issue by DreadCube** [Codeception/Codeception#4530] opened 2017-09-22 12:38 UTC
Hello guys.

Does Codeception have something like a feature, to skip / ignore "@depends" annotations for debugging purposes?

Example:
codecept run myCest:thatTest  --ignore-depends

Or if not could we implement something like that?

**Comment by Naktibalda** [comment] 2017-09-22 13:34
No there is no such thing.

I agree that it is very annoying when you want to run a single test and it fails because it is in the middle of depends chain.

**Comment by Naktibalda** [comment] 2017-09-22 13:36
Oh, another guy raised a ticket first, so this is a duplicate of #4528

**Closed by Naktibalda** 2017-09-22 13:36 UTC
Labels: ENHANCEMENT
