### ISSUE TITLE
Unable to switch to defaultContent since v2.2.9

### ISSUE THREAD

**Issue by saitho** [Codeception/Codeception#4012] opened 2017-02-10 10:56 UTC
#### What are you trying to achieve?
I'm running a test to create a page in the admin panel of a CMS. I'm doing that with Codeception v2.2.9. However, the test works fine with Codeception v2.2.8.

A simplified version of the test:

```php
// go to page...
$I->switchToFrame('content');
// do stuff to create page; fill inputs; click save; etc
$I->switchToFrame();
// check if page has been created
```

In fact only switching to the frame and switching out of it already fails with v2.2.9 and succeeds with v2.2.8.

#### What do you get instead?
Instead I get the following exception:

> [Facebook\WebDriver\Exception\NoSuchFrameException] {"errorMessage":"Unable to switch to frame","request":{"headers":{"Accept":"application/json","Content-Length":"9","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:4445"},"httpVersion":"1.1","method":"POST","post":"{\"id\":\"\"}","url":"/frame","urlParsed":{"anchor":"","query":"","file":"frame","directory":"/","path":"/frame","relative":"/frame","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/frame","queryKey":{},"chunks":["frame"]},"urlOriginal":"/session/0b252c60-ef70-11e6-94bb-b7fc66d0e83f/frame"}}  

### Details

* Codeception version: 2.2.9 (2.2.8 works!)
* PHP Version: 5.5.9
* Operating System: Ubuntu Trusty 64
* Installation type: Composer
* Can't provide a list of installed packages as most of them are non-public

**Comment by Naktibalda** [comment] 2017-02-10 11:36
Duplicate of #4001 

It is fixed already.

**Closed by Naktibalda** 2017-02-10 11:36 UTC

**Comment by saitho** [comment] 2017-02-10 11:59
Thanks – I looked for similar issues but I did not think about looking for closed ones. ^^
