### ISSUE TITLE
HTTP header problem

### ISSUE THREAD

**Issue by HakanDmr** [Codeception/Codeception#4810] opened 2018-02-12 18:58 UTC
I just simply send POST request to my REST service! However, Codeception changes http header keys. 
Why are you changing HTTP Header keys? 
What we have to do for using custom HTTP header key names?

**HTTP Header (Expected)**
Key: X-appAuth_Key 
Key: iosAppVersion

**But got these**
Key: X-Appauth-Key
Key: Iosappversion

> Therefore, service returns HTTP 401 Unauthorized!

```php
$I = new ApiTester($scenario);
$I->wantTo('Check web service health');
$I->haveHttpHeader('X-appAuth_Key', 'xxxxxxxx');
$I->haveHttpHeader('iosAppVersion', 1000);
$I->sendPOST('ping');
$I->seeResponseCodeIs(\Codeception\Util\HttpCode::OK);
$I->seeResponseIsJson();
```
### Details

* Codeception version: v2.3.8
* PHP Version: 7.2
* Operating System: Windows
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: ApiTester
modules:
    enabled:
        - REST:
            url: http://xxxx.com/v2/
            depends: PhpBrowser
            part: Json
```

**Comment by Naktibalda** [comment] 2018-02-13 11:35
This is so old, it almost is a feature.
Http custom headers problem: #1801

Recently implemented workaround - html encode characters that you don't want to be replaced #4541
Documented at https://codeception.com/docs/modules/PhpBrowser#haveHttpHeader
gives example with underscore `Client&#95;Id`
but letters can be html encoded too: https://cs.stanford.edu/people/miles/iso8859.html

It looks ugly, but works.

**Comment by Naktibalda** [comment] 2019-07-19 16:17
I'm closing this issue, because it is a duplicate of #1801

**Closed by Naktibalda** 2019-07-19 16:17 UTC
