### ISSUE TITLE
XML report generated in wrong folder

### ISSUE THREAD

**Issue by Anahkiasen** [Codeception/Codeception#2139] opened 2015-07-08 23:55 UTC
Since upgrading to 2.1 it seems Codeception is outputting the report file in the wrong folder when passing an absolute path, see example on CircleCI:

```
- XML report generated in /home/ubuntu/Ignition/tests/codeception/_output//tmp/circle-junit.XIDwsrx/codeception/ignition.xml vendor/bin/codecept run -vvv --no-interaction --debug --xml="$CIRCLE_TEST_REPORTS/codeception/ignition.xml" returned exit code 1
```

As you can see here `$CIRCLE_TEST_REPORTS` was `/tmp/circle-junit.XIDwsrx` yet Codeception still saved the file in `_output`.

**Comment by Naktibalda** [comment] 2015-08-18 22:32
Duplicate of #2187

Already fixed.

**Closed by Naktibalda** 2015-08-18 22:32 UTC
Labels: BUG, Reports
