### ISSUE TITLE
Errors when using multisession (Friend) in Acceptance tests

### ISSUE THREAD

**Issue by abenites** [Codeception/Codeception#1516] opened 2014-11-06 12:01 UTC
I'm using Webdriver module with PhantomJS. Sometimes, when running test with multissesion, it throws an error:

PHP Fatal error:  Call to a member function execute() on a non-object in /tests/vendor/facebook/webdriver/lib/remote/RemoteWebDriver.php on line 471
PHP Stack trace:
PHP   1. {main}() /tests/vendor/codeception/codeception/codecept:0
PHP   2. Symfony\Component\Console\Application->run() /tests/vendor/codeception/codeception/codecept:27
PHP   3. Symfony\Component\Console\Application->doRun() /tests/vendor/symfony/console/Symfony/Component/Console/Application.php:124
PHP   4. Symfony\Component\Console\Application->doRunCommand() /tests/vendor/symfony/console/Symfony/Component/Console/Application.php:193
PHP   5. Symfony\Component\Console\Command\Command->run() /tests/vendor/symfony/console/Symfony/Component/Console/Application.php:889
PHP   6. Codeception\Command\Run->execute() /tests/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
PHP   7. Codeception\Lib\Friend->__destruct() /tests/vendor/codeception/codeception/src/Codeception/Lib/Friend.php:0
PHP   8. Codeception\Module\WebDriver->_closeSession() /tests/vendor/codeception/codeception/src/Codeception/Lib/Friend.php:73
PHP   9. RemoteWebDriver->close() /tests/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:697
PHP  10. RemoteWebDriver->execute() /tests/vendor/facebook/webdriver/lib/remote/RemoteWebDriver.php:109

Any suggestions?

**Comment by girokon** [comment] 2015-06-10 10:20
I have same problem. This happens because "friend" session not closing after test was finished, Friend class trying to close self session after all tests. Because "friend" not destructed in test where I used it, he destructed when codeception script shutdown

This creates big problem for me, I have few tests, and their total execution time more then 10 minutes, and if I use `$mike = $I->haveFriend('Mike');` in one of test, I guaranteed getting this exception in final after success report

For reproducing use selenium grid with timeout lower than total test execution time

**Comment by eXorus** [comment] 2020-10-28 12:14
Thank you for contributing to this issue. As it has been 5 year since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please feel free to either reopen this issue or open a new one. 

We will be more than happy to look at it again!

**Closed by eXorus** 2020-10-28 12:14 UTC
Labels: BUG, Reproduce
