### ISSUE TITLE
Link or Button or CSS or XPath element with [...] was not found.

### ISSUE THREAD

**Issue by jannovy** [Codeception/Codeception#2910] opened 2016-03-17 09:03 UTC
I have these steps in my acceptance test:

$I->see("Přístupy", '.sidebar-nav a.item'); // passing
$I->click("Přístupy", '.sidebar-nav a.item'); // fail with "Link or Button or CSS or XPath element with 'P┼Ö├şstupy' was not found."

It happens only with Selenium2/firefox environment. In case of PhpBrowser pass the second step well.

I have 

- selenium-server-standalone-2.52.0.jar
- "codeception/codeception": "2.1.7"
- PHP Version 5.6.12

HTML snippet
```
<div id="sidebar-nav" class="sidebar-nav navbar-collapse">
<ul class="nav">
    <li class="active">
        <a class="item active" href="/admin.account/view/a/56e9755d514360fc17000051">
            <i class="fa fa-building"></i> Home
            <span class="fa arrow"></span>
        </a>
        <ul class="nav nav-second-level">
            <li>
                <a class="item" href="/admin.profile/contact/a/56e9755d514360fc17000051">
		Kontakty
		
	</a>

            </li>
            <li>
                <a class="item" href="/admin.role/default/a/56e9755d514360fc17000051">
		Přístupy
		
	</a>

            </li>

        </ul>

    </li>

    <li>
        <a class="item" href="/admin.settings/default">
            <i class="fa fa-cogs"></i> Nastavení
            <span class="fa arrow"></span>
        </a>

    </li>
</ul>
</div>
```
NOTE:

$I->see("Přístupy", '.sidebar-nav a.item'); // pass
$I->click("Přístupy"); // pass
$I->click("Přístupy","a"); // fail

**Comment by jirkae** [comment] 2016-03-21 11:58
Same problem +1

**Comment by index-panayotov** [comment] 2016-03-22 11:49
Have same problem : 
When I try to select a drop-down. For normal inputs or btns  i have no this issue

**Comment by Naktibalda** [comment] 2016-03-25 22:36
It is an issue of Selenium.

**Comment by index-panayotov** [comment] 2016-03-26 00:01
@Naktibalda  - I'm using  phpwebbrowser  :)

**Comment by Naktibalda** [comment] 2016-03-26 16:06
@index-panayotov then you have a different issue. Please raise an issue and provide your test code and HTML.

**Comment by josefsabl** [comment] 2016-03-29 15:07
Hey, I am writing on behalf of @jannovy as we work on the project together. I'd like to correct him as this appears not only in firefox environment and indeed in phpbrowser as well. And what is worse: seemingly randomly. Sometimes the tests pass locally but not on server. Other times they pass on the server for few hours and later they don't. It is crazy.

Today however, I found out one interesting thing. The test (phpbrowser) was failing at $I->see('hello world'); step although the string was there. It was captured in the error output html. And it failed everytime. But I also noticed the HTML was not valid and particularly one html attribute was malformed in a bad way:

`<a href=javascript:;">`

Notice the missing quote.

After fixing this the test is running just fine.

These tests are pretty simple, just $I->amOn("hello-world.php"); $I->see("hello world");

**Comment by josefsabl** [comment] 2016-03-31 11:10
Just to isolate the problem I created html like this (no header, no body etc, just this is in the document):

```
<a href=javascript:;">foo</a>
<p>bar</p>
```

The test is:

```
$I = new AcceptanceTester($scenario);
$I->amOnPage('/homepage/test');
$I->see('bar');
```

And it fails.

I understand that phpbrowser maybe can't parse the output well but it should explicitly show some notice, maybe "cannot parse page, invalid xml" instead of "I don't see 'bar' in output.". Env is phpbrowser.

Fixing the missing double quote makes the test to pass.

**Comment by Naktibalda** [comment] 2016-03-31 11:19
see() method does not parse HTML, it simply strips tags with strip_tags.

strip_tags removes everything after your invalid tag: http://codepad.org/5wK57qP7

**Comment by josefsabl** [comment] 2016-04-01 11:27
Well, I am bit confused now. Are you acknowledging the bug or are you explaining that see() method works as intended?

Don't take me wrong, but from the user point of view I am really not interested in the way the feature is implemented. What is important to me is that it behaves differently than I would expect.

**Comment by Naktibalda** [comment] 2016-04-01 13:59
It is an issue of your application if your HTML is invalid - use HTML validator.

Resolution of this ticket will be one of "won't fix" and  "not a bug".

**Comment by josefsabl** [comment] 2016-04-01 19:51
My expectation would be that Codeception would say something like "Test failed, output cannot be checked as it is an invalid XML" or something. Your position makes me feel like the whole thing is pretty volatile.

But nevermind, this is just some testing framework, nothing critical. It exposed our error anyways so it actually did it's job. It just wasted quite a lot of our time with false error report.

Thank you for your time and this cool product, cheers :-)

**Comment by Naktibalda** [comment] 2016-04-01 21:03
Related PHP bug reports: https://bugs.php.net/bug.php?id=63212 https://bugs.php.net/bug.php?id=62032

PhpBrowser's `see` is very primitive, it doesn't do any parsing. Few releases ago it searched for text anywhere in the page source and could match tags or content of <script> tag.

There are many other ways the text could be hidden - css, javascript, <font> tags and probably more.
If you want to test if the text is actually visible in the browser, use WebDriver with a real browser.

**Comment by josefsabl** [comment] 2016-04-04 08:47
I see, I read through the bugs. I don't think they will ever be resolved though as strip_tags seems to be broken beyond repair.

Quote from comments in one of those bugs threads:

> 99.99% of the time, strip_tags just should not be used at all because it's horribly broken.

**Closed** 2016-09-28 06:27 UTC
Labels: WebDriver
