### ISSUE TITLE
Can't install via composer for php 8.1

### ISSUE THREAD

**Issue by progdog-ru** [Codeception/Codeception#6340] opened 2022-01-29 11:57 UTC
#### What are you trying to achieve?
Install via command: `composer require "codeception/codeception" --dev`
#### What do you get instead?
I've got error in my console.
> Provide console output if related. Use `-vvv` mode for more details.

```bash
Using version ^4.1 for codeception/codeception
./composer.json has been updated
Running composer update codeception/codeception
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - codeception/codeception[4.1.0, ..., 4.1.8] require php >=5.6.0 <8.0 -> your php version (8.1.0) does not satisfy that requirement.
    - codeception/codeception[4.1.9, ..., 4.1.21] require guzzlehttp/psr7 ~1.4 -> found guzzlehttp/psr7[1.4.0, ..., 1.8.3] but the package is fixed to 2.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - codeception/codeception[4.1.22, ..., 4.1.28] require symfony/finder >=2.7 <6.0 -> found symfony/finder[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.37, v5.0.0, ..., v5.4.3] but the package is fixed to v6.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires codeception/codeception ^4.1 -> satisfiable by codeception/codeception[4.1.0, ..., 4.1.28].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require codeception/codeception:*" to figure out if any version is installable, or "composer require codeception/codeception:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version:  4.1
* PHP Version: 8.1
* Operating System: Win 10
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by Naktibalda** [comment] 2022-01-29 16:20
The problem is that you have symfony/finder locked to v6.0.2.

Codeception 4 is incompatible with Symfony 6.

Wait for Codeception 5 (5.0.0-alpha1 should be released in a few days) or downgrade to Symfony 5.

**Closed by Naktibalda** 2022-01-29 16:20 UTC

**Comment by progdog-ru** [comment] 2022-01-29 16:38
Thanks!

**Comment by progdog-ru** [comment] 2022-01-29 16:41
I installed it using [phar archive](https://codeception.com/install) and it works fine
Thank you!
