### ISSUE TITLE
Code generator mangles valid php-doc annotations with use-statements

### ISSUE THREAD

**Issue by mindplay-dk** [Codeception/Codeception#2622] opened 2015-12-10 14:59 UTC
I have in `tests/_support/Helper/Unit.php` something like:

```php
<?php

namespace Helper;

use Forms\Facets\ValidatorInterface;
use Forms\Field;

class Unit extends \Codeception\Module
{
    /**
     * Test a Validator against known valid and invalid values.
     *
     * @param Field              $field     Field instance where $name === 'value'
     * @param ValidatorInterface $validator function (FormValidator $v, Field $f): void; should invoke the validation function
     * @param string[]           $valid     list of valid values
     * @param string[]           $invalid   list of invalid values
     */
    public function testValidator(Field $field, ValidatorInterface $validator, array $valid, array $invalid)
    {
        // ...
    }
}
```

This results in a generated stub like:

```php
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Test a Validator against known valid and invalid values.
     *
     * @param Field              $field     Field instance where $name === 'value'
     * @param ValidatorInterface $validator function (FormValidator $v, Field $f): void; should invoke the validation function
     * @param string[]           $valid     list of valid values
     * @param string[]           $invalid   list of invalid values
     * @see \Helper\Unit::testValidator()
     */
    public function testValidator($field, $validator, $valid, $invalid) {
        return $this->getScenario()->runStep(new \Codeception\Step\Action('testValidator', func_get_args()));
    }
```

Unfortunately, it neither copies nor resolves type-references in doc-blocks, which results in mangled type-hints in the generated file - which means failed inspections and missing IDE support.

The obvious work-around is to break our code-standards and mangle code by using fully-qualified type-hints in every doc-block - which will provide IDE support, but will also lead to failed inspections.

Of course you can't simply copy the `use` statements, since this could cause collisions, so the type-hints really should be resolved and replaced with fully-qualifed type-hints in the generated source.

**Comment by DavertMik** [comment] 2015-12-17 01:45
unfortunately I don't see a way this can easily be fixes. Sure, docblocks should correspond to originals but resolving them in a way you need is a thing hard to implement. We will need some really smart parsing algorithm to do that.

I don't see a way this can be fixed, and the issue is not that major to be fixed.
If you have ideas how to make this done - please send PR.
For now I'll close this issue.

**Closed by DavertMik** 2015-12-17 01:45 UTC

**Comment by mindplay-dk** [comment] 2015-12-18 10:37
[This library](https://github.com/mindplay-dk/filereflection) will resolve qualified/unqualified type references into fully-qualified ones.

Note that PHP 7 grouped type-references are not supported yet.
