### ISSUE TITLE
REST module not sending any parameters via PUT

### ISSUE THREAD

**Issue by ThePeach** [Codeception/Codeception#1667] opened 2015-01-25 00:16 UTC
I've got a simple test that updates the password and then tries to use it to ensure it's working:

```php
$I->amGoingTo('authenticate to update my own password');
$I->amHttpAuthenticated($user['username'], $userPassword);
$newPassword = 'something else';
$I->sendPUT(
    'users/' . $userId,
    ['password' => $newPassword, 'authkey' => 'updated']
);
$I->seeResponseIsJson();
$I->seeResponseContains('true');
$I->seeResponseCodeIs(200);

$I->amGoingTo('authenticate to check my new password works');
$I->amHttpAuthenticated($user['username'], $newPassword);
$I->sendHEAD('users/'.$userId);
$I->seeResponseIsJson();
$I->seeResponseCodeIs(200);
```

the output is the following:
```
* I am going to authenticate to update my own password
* I am http authenticated "user","something"
* I send put "users/3",{"password":"something else","authkey":"updated"}
  [Request] PUT http://basic-dev.yii2.sandbox/v1/users/3 {"password":"something else","authkey":"update"}
  [Response] true
  [Headers] {"content-type":["application/json; charset=UTF-8"]}
  [Status] 200
* I see response is json 
* I see response contains "true"
* I see response code is 200
* I am going to authenticate to check my new password works
* I am http authenticated "user","something else"
* I send head "users/3"
  [Request] HEAD http://basic-dev.yii2.sandbox/v1/users/3 []
 ERROR 

There was 1 error:

---------
1) Failed to test the user rest api in UserAPICept (/mnt/workspace/yii2-book/tests/codeception/functional/UserAPICept.php)
Couldn't send head "users/3":
yii\web\UnauthorizedHttpException: You are requesting with an invalid credential.

Scenario Steps:
29. I send head "users/3"
28. I am http authenticated "user","something else"
27. I am going to authenticate to check my new password works
26. I see response code is 200
25. I see response contains "true"
24. I see response is json 
23. I send put "users/3",{"password":"something else","authkey":"updated"}

  [PHPUnit_Framework_ExceptionWrapper] You are requesting with an invalid credential.

FAILURES!
Tests: 1, Assertions: 14, Errors: 1.
```

The fact that the PUT returns true is probably more lazy programming on my end: I've dumped the content of `Yii::$app->request->getBodyParams();` and it's an empty array. (yes this is Yii2)
I've also replicated the scenario with Postman and using www-form-encoded params works as expected.

Anything I might have done wrong?

**Comment by Ragazzo** [comment] 2015-01-25 00:28
duplicate of https://github.com/Codeception/Codeception/issues/1666 Problem is the same

**Comment by ThePeach** [comment] 2015-01-25 11:05
Hi @Ragazzo sorry but can you please elaborate on why this is the same problem of #1666 ?
All I see here is that the REST module is not sending any parameters to the application.

This seems to be a much bigger issue than the inability to set the response code when it's failing.
Is there a workaround?

**Comment by DavertMik** [comment] 2015-02-02 02:33
@ThePeach it took some time to review the issue but thanks to you, there was enough details to say precisely what is happening here.

1. `sendPUT` works correctly, this step passes but `sendHEAD` fails. Maybe you thought that issue was with PUT because its step was listed in exception trace. However, steps were listed in reverse order and numbered, so you should have seen that 29th step is failing.

2. You are using `amHttpAuthenticated` method which does not belong to REST module. That's why it doesn't work with REST interactions. It is a part of PhpBrowser module which acts as a driver here. But PhpBrowser methods should not be used in API tests. I plan to solve this confusion in upcoming 2.1 release

For your case you should use something like `$I->haveHttpHeader`

**Closed by DavertMik** 2015-02-02 02:33 UTC

**Comment by ThePeach** [comment] 2015-02-03 12:33
Hi @DavertMik that's great to hear, and you're right I completely missed that `sendHEAD` was the culprit!

Unfortunately I can't test this one yet, as `haveHttpHeader()` doesn't seem to be working as expected: 
The related bug report is #1688.
